var searchData=
[
  ['c_0',['C',['../group__cpp.html',1,'C++'],['../group__pkg__edhoc__c.html',1,'EDHOC-C'],['../group__net__gnrc__sixlowpan__frag__sfr__congure__sfr.html',1,'gnrc_sixlowpan_frag_sfr_congure_sfr: Appendix C']]],
  ['c_2011_20wrapper_20for_20riot_1',['C++11 wrapper for RIOT',['../group__cpp11-compat.html',1,'']]],
  ['c_20compatibility_20with_20c11_20atomics_2',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['c_20constructor_20guards_20for_20static_20instances_3',['C++ constructor guards for static instances',['../group__sys__cxx__ctor__guards.html',1,'']]],
  ['c_20new_20and_20delete_20operator_20module_4',['C++ new and delete operator module',['../group__sys__cpp__new__delete.html',1,'']]],
  ['c_20unittests_5',['C++ Unittests',['../group__unittests__cpp.html',1,'']]],
  ['c030_20u201_6',['Ublox C030-U201',['../group__boards__ublox-c030-u201.html',1,'']]],
  ['c031c6_7',['STM32 Nucleo-C031C6',['../group__boards__nucleo-c031c6.html',1,'']]],
  ['c11_20atomics_8',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['c25519_20cryptographic_20library_9',['C25519 cryptographic library',['../group__pkg__c25519.html',1,'']]],
  ['c3_20boards_10',['ESP32-C3 Boards',['../group__boards__esp32c3.html',1,'']]],
  ['c3_20common_11',['ESP32-C3 Common',['../group__boards__common__esp32c3.html',1,'']]],
  ['c3_20devkit_20board_12',['ESP32-C3-DevKit Board',['../group__boards__esp32c3__devkit.html',1,'']]],
  ['c3_20family_13',['ESP32-C3 family',['../group__cpu__esp32__esp32c3.html',1,'']]],
  ['c3_20mini_14',['Wemos ESP32-C3 mini',['../group__boards__esp32c3__wemos__mini.html',1,'']]],
  ['c3_20soc_15',['ESP32 SDK Bluetooth library for the ESP32-C3 SoC',['../group__pkg__esp32__sdk__lib__bt__esp32c3.html',1,'']]],
  ['ca_20helper_16',['CSMA/CA helper',['../group__net__csma__sender.html',1,'']]],
  ['ca_20helper_20compile_20configurations_17',['CSMA/CA helper compile configurations',['../group__net__csma__sender__conf.html',1,'']]],
  ['cache_18',['Neighbor Cache',['../group__net__gnrc__ipv6__nib__nc.html',1,'']]],
  ['cache_19',['DNS cache',['../group__net__dns__cache.html',1,'']]],
  ['cache_20implementation_20',['nanoCoAP-Cache implementation',['../group__net__nanocoap__cache.html',1,'']]],
  ['callback_20extension_21',['Callback extension',['../group__net__gnrc__netapi__callbacks.html',1,'']]],
  ['callback_20multiplexer_22',['Callback multiplexer',['../group__sys__cb__mux.html',1,'']]],
  ['calliope_20mini_23',['Calliope mini',['../group__boards__calliope-mini.html',1,'']]],
  ['can_24',['CAN',['../group__drivers__periph__can.html',1,'CAN'],['../group__sys__can__isotp.html',1,'ISO transport protocol over CAN']]],
  ['can_20controller_25',['CAN controller',['../group__cpu__esp32__esp__can.html',1,'ESP32 CAN controller'],['../group__candev__stm32.html',1,'STM32 CAN controller']]],
  ['can_20controller_20area_20network_26',['CAN (Controller Area Network)',['../group__sys__can.html',1,'']]],
  ['can_20device_20driver_20interface_27',['CAN device driver interface',['../group__drivers__candev.html',1,'']]],
  ['can_20drivers_28',['CAN Drivers',['../group__drivers__can.html',1,'']]],
  ['can_20transceiver_29',['NCV7356 Single Wire CAN Transceiver',['../group__drivers__ncv7356.html',1,'']]],
  ['can_20transceiver_20interface_30',['CAN transceiver interface',['../group__drivers__can__trx.html',1,'']]],
  ['capacitance_20to_20digital_20converter_20driver_31',['AD7746 Capacitance-to-digital converter driver',['../group__drivers__ad7746.html',1,'']]],
  ['card_20driver_32',['SPI SD Card driver',['../group__drivers__sdcard__spi.html',1,'']]],
  ['cards_33',['MTD wrapper for SPI SD Cards',['../group__drivers__mtd__sdcard.html',1,'']]],
  ['carithmetic_34',['plain 64bit carithmetic',['../group__sys__ztimer__convert__muldiv64.html',1,'']]],
  ['cayenne_20low_20power_20payload_20lpp_35',['Cayenne Low Power Payload (LPP)',['../group__pkg__cayenne-lpp.html',1,'']]],
  ['cbor_36',['CBOR',['../group__fido2__ctap__cbor.html',1,'FIDO2 CTAP CBOR'],['../group__sys__psa__crypto__cbor__encoder.html',1,'Module for encoding PSA keys in CBOR'],['../group__sys__senml__cbor.html',1,'SenML CBOR']]],
  ['cbor_37',['cn-cbor',['../group__pkg__cn-cbor.html',1,'']]],
  ['cc_38',['CC',['../group__sys__congure__quic.html',1,'CongURE implementation of QUIC&apos;s CC'],['../group__net__gnrc__sixlowpan__frag__sfr__congure__quic.html',1,'gnrc_sixlowpan_frag_sfr_congure_quic: QUIC CC']]],
  ['cc1100_20cc1100e_20cc1101_20cc1200_20common_20code_39',['CC1100/CC1100e/CC1101/CC1200 common code',['../group__drivers__cc1xxx.html',1,'']]],
  ['cc1100_20cc1100e_20cc1101_20sub_20ghz_20transceiver_20driver_40',['CC1100 CC1100e CC1101 Sub GHz transceiver driver',['../group__drivers__cc110x.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc110x__config.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver']]],
  ['cc1100e_20cc1101_20cc1200_20common_20code_41',['CC1100/CC1100e/CC1101/CC1200 common code',['../group__drivers__cc1xxx.html',1,'']]],
  ['cc1100e_20cc1101_20sub_20ghz_20transceiver_20driver_42',['CC1100e CC1101 Sub GHz transceiver driver',['../group__drivers__cc110x.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc110x__config.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver']]],
  ['cc1101_20cc1200_20common_20code_43',['CC1100/CC1100e/CC1101/CC1200 common code',['../group__drivers__cc1xxx.html',1,'']]],
  ['cc1101_20sub_20ghz_20transceiver_20driver_44',['CC1101 Sub GHz transceiver driver',['../group__drivers__cc110x.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc110x__config.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver']]],
  ['cc1200_20common_20code_45',['CC1100/CC1100e/CC1101/CC1200 common code',['../group__drivers__cc1xxx.html',1,'']]],
  ['cc1312_20launchpad_46',['TI CC1312 LaunchPad',['../group__boards__cc1312__launchpad.html',1,'']]],
  ['cc1350_20launchpad_20xl_47',['TI CC1350 LaunchPad XL',['../group__boards__cc1350__launchpad.html',1,'']]],
  ['cc1352_20launchpad_48',['TI CC1352 LaunchPad',['../group__boards__cc1352__launchpad.html',1,'']]],
  ['cc1352p_20launchpad_49',['TI CC1352P LaunchPad',['../group__boards__cc1352p__launchpad.html',1,'']]],
  ['cc13x0_50',['TI CC26x0/CC13x0',['../group__cpu__cc26x0__cc13x0.html',1,'']]],
  ['cc13x0_20definitions_51',['TI CC26x0/CC13x0 definitions',['../group__cpu__cc26x0__cc13x0__definitions.html',1,'']]],
  ['cc13x0_20peripheral_20memory_20map_52',['TI CC26x0/CC13x0 peripheral memory map',['../group__cpu__specific__peripheral__memory__map.html',1,'']]],
  ['cc13x2_53',['TI CC26x2, CC13x2',['../group__cpu__cc26x2__cc13x2.html',1,'']]],
  ['cc13x2_20definitions_54',['TI CC26x2, CC13x2 definitions',['../group__cpu__cc26x2__cc13x2__definitions.html',1,'']]],
  ['cc13x2_20peripheral_20memory_20map_55',['TI CC26x2, CC13x2 peripheral memory map',['../group__cpu__cc26x2__cc13x2__peripheral__memory__map.html',1,'']]],
  ['cc13xx_20common_56',['CC13xx common',['../group__cpu__cc26xx__cc13xx.html',1,'CC26xx/CC13xx common'],['../group__cpu__cc26xx__cc13xx__definitions.html',1,'CC26xx/CC13xx common']]],
  ['cc2420_20radio_20driver_57',['CC2420 radio driver',['../group__drivers__cc2420.html',1,'']]],
  ['cc2538_58',['TI CC2538',['../group__cpu__cc2538.html',1,'']]],
  ['cc2538_59',['OpenMote-cc2538',['../group__boards__openmote-cc2538.html',1,'']]],
  ['cc2538_20adc_60',['CC2538 ADC',['../group__cpu__cc2538__adc.html',1,'']]],
  ['cc2538_20cc2592_20dk_20board_61',['Generic CC2538-CC2592-DK Board',['../group__boards__generic__cc2538__cc2592__dk.html',1,'']]],
  ['cc2538_20cmsis_20style_20headers_62',['TI CC2538 CMSIS-style Headers',['../group__cpu__cc2538__regs.html',1,'']]],
  ['cc2538_20configuration_20snippets_63',['cc2538 Configuration Snippets',['../group__boards__common__cc2538.html',1,'']]],
  ['cc2538_20general_20purpose_20i_20o_64',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['cc2538_20general_20purpose_20timer_65',['CC2538 General Purpose Timer',['../group__cpu__cc2538__gptimer.html',1,'']]],
  ['cc2538_20rf_20core_20interface_66',['CC2538 RF core interface',['../group__cpu__cc2538__rfcore.html',1,'']]],
  ['cc2538_20system_20control_67',['CC2538 System Control',['../group__cpu__cc2538__sysctrl.html',1,'']]],
  ['cc2538_20uart_68',['CC2538 UART',['../group__cpu__cc2538__uart.html',1,'']]],
  ['cc2538dk_69',['CC2538DK',['../group__boards__cc2538dk.html',1,'']]],
  ['cc2592_20dk_20board_70',['Generic CC2538-CC2592-DK Board',['../group__boards__generic__cc2538__cc2592__dk.html',1,'']]],
  ['cc2650_20launchpad_20xl_71',['TI CC2650 LaunchPad XL',['../group__boards__cc2650__launchpad.html',1,'']]],
  ['cc2650stk_72',['CC2650STK',['../group__boards__cc2650stk.html',1,'']]],
  ['cc26x0_20cc13x0_73',['TI CC26x0/CC13x0',['../group__cpu__cc26x0__cc13x0.html',1,'']]],
  ['cc26x0_20cc13x0_20definitions_74',['TI CC26x0/CC13x0 definitions',['../group__cpu__cc26x0__cc13x0__definitions.html',1,'']]],
  ['cc26x0_20cc13x0_20peripheral_20memory_20map_75',['TI CC26x0/CC13x0 peripheral memory map',['../group__cpu__specific__peripheral__memory__map.html',1,'']]],
  ['cc26x2_20cc13x2_76',['TI CC26x2, CC13x2',['../group__cpu__cc26x2__cc13x2.html',1,'']]],
  ['cc26x2_20cc13x2_20definitions_77',['TI CC26x2, CC13x2 definitions',['../group__cpu__cc26x2__cc13x2__definitions.html',1,'']]],
  ['cc26x2_20cc13x2_20peripheral_20memory_20map_78',['TI CC26x2, CC13x2 peripheral memory map',['../group__cpu__cc26x2__cc13x2__peripheral__memory__map.html',1,'']]],
  ['cc26xx_20cc13xx_20common_79',['CC26xx CC13xx common',['../group__cpu__cc26xx__cc13xx.html',1,'CC26xx/CC13xx common'],['../group__cpu__cc26xx__cc13xx__definitions.html',1,'CC26xx/CC13xx common']]],
  ['ccitt_80',['CRC16-CCITT',['../group__sys__checksum__crc16__ccitt.html',1,'']]],
  ['ccs_20811_20digital_20gas_20sensor_81',['CCS 811 digital gas sensor',['../group__drivers__ccs811.html',1,'']]],
  ['cdc_20abstract_20control_20model_82',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['cdc_20acm_83',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['cdc_20acm_20compile_20time_20configurations_84',['USBUS CDC ACM compile time configurations',['../group__usbus__cdc__acm__conf.html',1,'']]],
  ['cdc_20acm_20internals_85',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['cdc_20acm_20tinyusb_86',['STDIO over USB CDC-ACM (tinyUSB)',['../group__pkg__tinyusb__stdio__cdc__acm.html',1,'']]],
  ['cdc_20acm_20usbus_87',['STDIO over CDC ACM (usbus)',['../group__usbus__cdc__acm__stdio.html',1,'']]],
  ['cdc_20acm_20usbus_20cdc_20abstract_20control_20model_88',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['cdc_20ecm_20usbus_20cdc_20ethernet_20control_20model_89',['USBUS CDC ECM - USBUS CDC ethernet control model',['../group__usbus__cdc__ecm.html',1,'']]],
  ['cdc_20ethernet_20control_20model_90',['USBUS CDC ECM - USBUS CDC ethernet control model',['../group__usbus__cdc__ecm.html',1,'']]],
  ['cdc_20usb_20communications_20device_20class_91',['CDC - USB communications device class',['../group__usb__cdc.html',1,'']]],
  ['cell02_92',['ST P-L496G-CELL02',['../group__boards__p-l496g-cell02.html',1,'']]],
  ['central_20m4_20express_93',['Adafruit Grand Central M4 Express',['../group__boards__adafruit-grand-central-m4-express.html',1,'']]],
  ['chacha20poly1305_20aead_20cipher_94',['chacha20poly1305 AEAD cipher',['../group__sys__crypto__chacha20poly1305.html',1,'']]],
  ['checksum_95',['Checksum',['../group__sys__checksum.html',1,'Checksum'],['../group__net__inet__csum.html',1,'Internet Checksum']]],
  ['chip_96',['AT24MAC unique ID chip',['../group__drivers__at24mac.html',1,'']]],
  ['chunked_20ringbuffer_97',['chunked Ringbuffer',['../group__sys__chunk__buffer.html',1,'']]],
  ['cifra_20cryptographic_20library_98',['Cifra cryptographic library',['../group__pkg__cifra.html',1,'']]],
  ['cipher_99',['PSA Wrapper Functions: Cipher',['../group__sys__psa__crypto__cipher.html',1,'']]],
  ['cipher_100',['chacha20poly1305 AEAD cipher',['../group__sys__crypto__chacha20poly1305.html',1,'']]],
  ['ciphers_101',['Secure Element Symmetric Ciphers',['../group__se__cipher.html',1,'']]],
  ['class_102',['class',['../group__usb__cdc.html',1,'CDC - USB communications device class'],['../group__usb__hid.html',1,'HID - USB communications device class']]],
  ['class_20functions_103',['USBUS Mass Storage Class functions',['../group__usbus__msc.html',1,'']]],
  ['client_104',['Client',['../group__net__cord.html',1,'CoRE RD Endpoint and Lookup Client'],['../group__net__cord__lc.html',1,'CoRE RD Lookup Client']]],
  ['client_105',['DHCPv6 client',['../group__net__dhcpv6__client.html',1,'']]],
  ['client_20asymcute_106',['MQTT-SN Client (Asymcute)',['../group__net__asymcute.html',1,'']]],
  ['client_20compile_20configurations_107',['Client compile configurations',['../group__net__asymcute__conf.html',1,'Asymcute (MQTT-SN Client) compile configurations'],['../group__net__emcute__conf.html',1,'EmCute (MQTT-SN Client) compile configurations']]],
  ['client_20compile_20configurations_108',['MQTT client compile configurations',['../group__net__mqtt__conf.html',1,'']]],
  ['client_20configuration_109',['Wakaama LwM2M Client configuration',['../group__lwm2m__client__config.html',1,'']]],
  ['client_20configuration_110',['GCoAP DNS over CoAP client configuration',['../group__gcoap__dns__config.html',1,'']]],
  ['client_20emcute_111',['MQTT-SN Client (emCute)',['../group__net__emcute.html',1,'']]],
  ['client_20for_112',['gnrc_dhcpv6_client_simple_pd: DHCPv6 client for',['../group__net__dhcpv6__client__simple__pd.html',1,'']]],
  ['client_20for_20gnrc_206lowpan_20brs_113',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['client_20implementation_114',['DNS over CoAP client implementation',['../group__net__gcoap__dns.html',1,'']]],
  ['client_20implementation_20in_20gnrc_115',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['client_20using_20wakaama_116',['LwM2M Client using Wakaama',['../group__lwm2m__client.html',1,'']]],
  ['clock_117',['Clock',['../group__drivers__ds3231.html',1,'DS3231 Real Time Clock'],['../group__drivers__periph__ptp.html',1,'PTP-Clock']]],
  ['clock_118',['System core clock',['../group__sys__clk.html',1,'']]],
  ['clock_20backend_119',['ztimer mock clock backend',['../group__sys__ztimer__mock.html',1,'']]],
  ['clock_20rtc_120',['NXP QN908x Real-Time-Clock (RTC)',['../group__cpu__qn908x__rtc.html',1,'']]],
  ['clone_121',['WeMos Arduino Zero Clone',['../group__boards__wemos-zero.html',1,'']]],
  ['clones_122',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['clue_123',['Adafruit Clue',['../group__boards__adafruit-clue.html',1,'']]],
  ['cmsis_20definitions_124',['CMSIS Definitions',['../group__CC2538__cmsis.html',1,'CMSIS Definitions'],['../group__CC13x2__cmsis.html',1,'CMSIS Definitions']]],
  ['cmsis_20style_20headers_125',['TI CC2538 CMSIS-style Headers',['../group__cpu__cc2538__regs.html',1,'']]],
  ['cn_20cbor_126',['cn-cbor',['../group__pkg__cn-cbor.html',1,'']]],
  ['co_20kw41z_20mini_20256kib_20board_127',['openlabs.co kw41z-mini-256kib board',['../group__boards__openlabs-kw41z-mini-256kib.html',1,'']]],
  ['co_20kw41z_20mini_20board_128',['openlabs.co kw41z-mini board',['../group__boards__openlabs-kw41z-mini.html',1,'']]],
  ['co2_20sensor_129',['MH-Z19 CO2 sensor',['../group__drivers__mhz19.html',1,'']]],
  ['co2_20temperature_20and_20humidity_20sensor_130',['SCD30 CO2, temperature and humidity sensor',['../group__drivers__scd30.html',1,'']]],
  ['coap_20client_20configuration_131',['GCoAP DNS over CoAP client configuration',['../group__gcoap__dns__config.html',1,'']]],
  ['coap_20client_20implementation_132',['DNS over CoAP client implementation',['../group__net__gcoap__dns.html',1,'']]],
  ['coap_20compile_20configurations_133',['CoAP compile configurations',['../group__net__coap__conf.html',1,'']]],
  ['coap_20defines_134',['CoAP defines',['../group__net__coap.html',1,'']]],
  ['coap_20file_20server_135',['CoAP file server',['../group__net__nanocoap__fileserver.html',1,'']]],
  ['coap_20library_136',['nanoCoAP small CoAP library',['../group__net__nanocoap.html',1,'']]],
  ['coap_20transport_137',['SUIT firmware CoAP transport',['../group__sys__suit__transport__coap.html',1,'']]],
  ['code_138',['code',['../group__boards__common__blxxxpill.html',1,'Blackpill and Bluepill common code'],['../group__drivers__cc1xxx.html',1,'CC1100/CC1100e/CC1101/CC1200 common code'],['../group__boards__common__e104-bt50xxa-tb.html',1,'E104-BT50xxA-TB common code'],['../group__boards__common__weact-f4x1cx.html',1,'WeAct-F4x1Cx common code'],['../group__sys__coding__xor.html',1,'XOR code']]],
  ['code_20generator_139',['QR Code generator',['../group__pkg__qr-code-generator.html',1,'']]],
  ['code_20implementation_140',['small Reed-Solomon code implementation',['../group__pkg__nanors.html',1,'']]],
  ['coded_20decimal_141',['Binary coded decimal',['../group__sys__bcd.html',1,'']]],
  ['codes_142',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['codes_143',['Error correction codes',['../group__sys__coding.html',1,'']]],
  ['color_144',['Color',['../group__sys__color.html',1,'']]],
  ['color_20graphics_20library_20for_20embedded_20systems_145',['Color graphics library for embedded systems',['../group__pkg__ucglib.html',1,'']]],
  ['colored_20log_20module_146',['log_color: Colored log module',['../group__sys__log__color.html',1,'']]],
  ['command_20set_20library_147',['AT (Hayes) command set library',['../group__drivers__at.html',1,'']]],
  ['commands_148',['commands',['../group__sys__congure__test.html',1,'CongURE test framework shell commands'],['../group__sys__shell__commands.html',1,'Shell commands']]],
  ['common_149',['Common',['../group__boards__common__arduino-atmega.html',1,'Arduino Atmega Common'],['../group__boards__common__arduino__due.html',1,'Arduino Due Common'],['../group__boards__common__arduino-mkr.html',1,'Arduino MKR Common'],['../group__net__cord__common.html',1,'CoRE RD Common'],['../group__sys__entropy__source__common.html',1,'Entropy Source Common'],['../group__cpu__esp__common.html',1,'ESP Common'],['../group__boards__common__esp32.html',1,'ESP32 Common'],['../group__boards__common__esp32c3.html',1,'ESP32-C3 Common'],['../group__boards__common__esp32s2.html',1,'ESP32-S2 Common'],['../group__boards__common__esp32s3.html',1,'ESP32-S3 Common'],['../group__boards__common__esp32x.html',1,'ESP32x Common'],['../group__boards__common__esp8266.html',1,'ESP8266 Common'],['../group__boards__common__iotlab.html',1,'IoTlab Common'],['../group__boards__common__frdm.html',1,'NXP FRDM Common'],['../group__boards__common__silabs.html',1,'Silicon Labs Common'],['../group__boards__common__nucleo.html',1,'STM32 Nucleo Common']]],
  ['common_150',['common',['../group__cpu__cortexm__common.html',1,'ARM Cortex-M common'],['../group__cpu__arm7__common.html',1,'ARM7 CPU common'],['../group__boards__common__atmega.html',1,'ATmega common'],['../group__cpu__sam__common.html',1,'Atmel SAM common'],['../group__cpu__sam0__common.html',1,'Atmel SAM0 common'],['../group__boards__common__atxmega.html',1,'ATxmega common'],['../group__cpu__cc26xx__cc13xx.html',1,'CC26xx/CC13xx common'],['../group__cpu__cc26xx__cc13xx__definitions.html',1,'CC26xx/CC13xx common'],['../group__boards__common__kw41z.html',1,'KW41Z common'],['../group__boards__common__msb-430.html',1,'MSB-430 common'],['../group__boards__common__nrf51.html',1,'NRF51 common'],['../group__boards__common__nrf52.html',1,'nRF52 common'],['../group__boards__common__nrf52xxxdk.html',1,'NRF52 DK common'],['../group__boards__common__particle-mesh.html',1,'Particle Mesh common'],['../group__cpu__riscv__common.html',1,'RISC-V common'],['../group__sys__hashes__sha2xx__common.html',1,'SHA-2xx common'],['../group__sys__hashes__sha512__common.html',1,'SHA-512 common'],['../group__boards__common__sodaq.html',1,'SODAQ boards common'],['../group__boards__common__remote.html',1,'Zolertia Re-Mote common']]],
  ['common_20board_20groups_151',['Common Board Groups',['../group__boards__common.html',1,'']]],
  ['common_20code_152',['common code',['../group__boards__common__blxxxpill.html',1,'Blackpill and Bluepill common code'],['../group__drivers__cc1xxx.html',1,'CC1100/CC1100e/CC1101/CC1200 common code'],['../group__boards__common__e104-bt50xxa-tb.html',1,'E104-BT50xxA-TB common code'],['../group__boards__common__weact-f4x1cx.html',1,'WeAct-F4x1Cx common code']]],
  ['common_20compile_20configurations_153',['ESP common compile configurations',['../group__cpu__esp__common__conf.html',1,'']]],
  ['common_20configuration_154',['GD32V Common Configuration',['../group__boards__common__gd32v.html',1,'']]],
  ['common_20configuration_20snippets_20for_20msp430_20boards_155',['Common Configuration Snippets for MSP430 boards',['../group__boards__common__msp430.html',1,'']]],
  ['common_20definitions_156',['Common definitions',['../group__sys__can__common.html',1,'']]],
  ['common_20drivers_157',['Silicon Labs Common Drivers',['../group__boards__common__silabs__drivers.html',1,'']]],
  ['common_20events_158',['System Buses for common events',['../group__sys__bus.html',1,'']]],
  ['common_20files_159',['common files',['../group__cpu__atmega__common.html',1,'Atmel ATmega CPU: common files'],['../group__cpu__avr8__common.html',1,'Atmel AVR-8 CPU: common files']]],
  ['common_20files_20of_20arduino_20zero_20and_20clones_160',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['common_20lwm2m_20object_20functionalities_161',['Common LwM2M Object functionalities',['../group__lwm2m__objects__common.html',1,'']]],
  ['common_20mac_20module_162',['Common MAC module',['../group__net__gnrc__mac.html',1,'']]],
  ['common_20macros_163',['Common Macros',['../group__core__macros.html',1,'']]],
  ['common_20microbit_20led_20handling_164',['Common microbit LED handling',['../group__boards__common__microbit.html',1,'']]],
  ['common_20peripheral_20initialization_165',['Common peripheral initialization',['../group__drivers__periph__init.html',1,'']]],
  ['communication_166',['Arduino library for SDI-12 communication',['../group__pkg__arduino__sdi__12.html',1,'']]],
  ['communication_20controller_167',['Board communication controller',['../group__boards__common__silabs__drivers__bc.html',1,'']]],
  ['communication_20interface_168',['GNRC communication interface',['../group__net__gnrc__netapi.html',1,'']]],
  ['communications_20device_20class_169',['communications device class',['../group__usb__cdc.html',1,'CDC - USB communications device class'],['../group__usb__hid.html',1,'HID - USB communications device class']]],
  ['compass_170',['HMC5883L 3-axis digital compass',['../group__drivers__hmc5883l.html',1,'']]],
  ['compatibility_20with_20c11_20atomics_171',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['compile_20configuration_172',['compile configuration',['../group__drivers__seesaw__soil__config.html',1,'Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration'],['../group__drivers__ads101x__config.html',1,'ADS101 driver compile configuration'],['../group__drivers__at__config.html',1,'AT driver compile configuration'],['../group__drivers__at86rf215__config.html',1,'AT86RF215 driver compile configuration'],['../group__drivers__atca__config.html',1,'ATCA driver compile configuration'],['../group__drivers__bmx055__config.html',1,'BMX055 sensor driver compile configuration'],['../group__core__init__config.html',1,'Core initialization compile configuration'],['../group__drivers__kw2xrf__config.html',1,'CR20A and KW2xD radio driver compile configuration'],['../group__drivers__dose__config.html',1,'Differentially Operated Serial Ethernet (DOSE) driver compile configuration'],['../group__drivers__ds1307__config.html',1,'DS1307 RTC driver compile configuration'],['../group__drivers__ethos__config.html',1,'Ethernet-over-serial driver driver compile configuration'],['../group__drivers__fxos8700__config.html',1,'FXOS8700 accelerometer/magnetometer driver compile configuration'],['../group__net__gnrc__gomach__conf.html',1,'GNRC GoMacH compile configuration'],['../group__drivers__hdc1000__config.html',1,'HDC1000 Humidity and Temperature Sensor driver compile configuration'],['../group__drivers__isl29020__config.html',1,'ISL29020 light sensor driver compile configuration'],['../group__drivers__kw41zrf__config.html',1,'KW41Z, KW21Z in-cpu transceiver driver compile configuration'],['../group__drivers__l3g4200d__config.html',1,'L3G4200D gyroscope driver compile configuration'],['../group__drivers__lm75.html',1,'LM75 Temperature Sensor driver compile configuration'],['../group__drivers__lpsxxx__config.html',1,'LPS331AP/LPS25HB/LPS22HB/LPS22HH/LPS22CH driver compile configuration'],['../group__drivers__mag3110__config.html',1,'MAG3110 Magnetometer driver compile configuration'],['../group__drivers__mma8x5x__config.html',1,'MMA8x5x Accelerometer driver compile configuration'],['../group__drivers__motor__driver__config.html',1,'Motor_Driver driver compile configuration'],['../group__drivers__mpl3115a2__config.html',1,'MPL3115A2 Pressure Sensor driver compile configuration'],['../group__drivers__mrf24j40__config.html',1,'mrf24j40 driver compile configuration'],['../group__drivers__nrf52__802154__conf.html',1,'nrf802154 driver compile configuration'],['../group__drivers__opt3001__config.html',1,'OPT3001 Ambient Light Sensor driver compile configuration'],['../group__drivers__pir__config.html',1,'PIR Motion Sensor driver compile configuration'],['../group__drivers__pn532__config.html',1,'PN532 NFC Radio driver compile configuration'],['../group__drivers__rn2xx3__config.html',1,'RN2483/RN2903 Radio driver compile configuration'],['../group__drivers__mtd__sdcard__config.html',1,'SDCard driver compile configuration'],['../group__drivers__sx127x__config.html',1,'Semtech SX1272 and SX1276 driver compile configuration'],['../group__drivers__slipdev__config.html',1,'SLIP Network driver compile configuration'],['../group__net__sock__dtls__conf.html',1,'SOCK DTLS compile configuration'],['../group__drivers__softspi__config.html',1,'Software SPI driver compile configuration'],['../group__drivers__SPS30__config.html',1,'SPS30 PM Sensor driver compile configuration'],['../group__drivers__tcs37727__config.html',1,'TCS37727 RGB Light Sensor driver compile configuration'],['../group__drivers__tmp00x__config.html',1,'TMP006/TMP007 Infrared Thermopile Sensor driver compile configuration']]],
  ['compile_20configurations_173',['compile configurations',['../group__net__credman__conf.html',1,'(D)TLS Credential Manager compile configurations'],['../group__drivers__adcxx1c__config.html',1,'ADCXX1C driver compile configurations'],['../group__net__asymcute__conf.html',1,'Asymcute (MQTT-SN Client) compile configurations'],['../group__net__coap__conf.html',1,'CoAP compile configurations'],['../group__net__csma__sender__conf.html',1,'CSMA/CA helper compile configurations'],['../group__net__dhcpv6__conf.html',1,'DHCPv6 compile configurations'],['../group__net__emcute__conf.html',1,'EmCute (MQTT-SN Client) compile configurations'],['../group__sys__entropy__source__config.html',1,'Entropy Source compile configurations'],['../group__cpu__esp__common__conf.html',1,'ESP common compile configurations'],['../group__cpu__esp32__conf.html',1,'ESP32 compile configurations'],['../group__cpu__esp8266__conf.html',1,'ESP8266 compile configurations'],['../group__net__gcoap__conf.html',1,'GCoAP compile configurations'],['../group__net__gnrc__sixlowpan__config.html',1,'GNRC 6LoWPAN compile configurations'],['../group__net__gnrc__conf.html',1,'GNRC compile configurations'],['../group__net__gnrc__ipv6__blacklist__conf.html',1,'GNRC IPv6 address blacklisting compile configurations'],['../group__net__gnrc__ipv6__whitelist__conf.html',1,'GNRC IPv6 address whitelisting compile configurations'],['../group__net__gnrc__ipv6__conf.html',1,'GNRC IPv6 compile configurations'],['../group__net__gnrc__ipv6__ext__conf.html',1,'GNRC IPv6 extension header compile configurations'],['../group__net__gnrc__ipv6__nib__conf.html',1,'GNRC IPv6 NIB compile configurations'],['../group__net__gnrc__lorawan__conf.html',1,'GNRC LoRaWAN compile configurations'],['../group__net__gnrc__lwmac__conf.html',1,'GNRC LWMAC compile configurations'],['../group__net__gnrc__mac__conf.html',1,'GNRC MAC compile configurations'],['../group__net__gnrc__pktbuf__conf.html',1,'GNRC PKTBUF compile configurations'],['../group__net__gnrc__pktdump__conf.html',1,'GNRC PKTDUMP compile configurations'],['../group__net__gnrc__sock__conf.html',1,'GNRC sock implementation compile configurations'],['../group__net__gnrc__tcp__conf.html',1,'GNRC TCP compile configurations'],['../group__net__gnrc__udp__conf.html',1,'GNRC UDP compile configurations'],['../group__drivers__gp2y10xx__config.html',1,'GP2Y10xx driver compile configurations'],['../group__net__ieee802154__conf.html',1,'IEEE802.15.4 compile configurations'],['../group__net__l2filter__conf.html',1,'Link layer address filter compile configurations'],['../group__net__lora__conf.html',1,'LoRa modulation compile configurations'],['../group__net__loramac__conf.html',1,'LoRaMAC compile configurations'],['../group__lwm2m__objects__barometer__config.html',1,'LwM2M Barometer object compile configurations'],['../group__lwm2m__objects__current__config.html',1,'LwM2M Current Sensor object compile configurations'],['../group__lwm2m__objects__humidity__config.html',1,'LwM2M Humidity Sensor object compile configurations'],['../group__lwm2m__objects__illuminance__config.html',1,'LwM2M Illuminance Sensor object compile configurations'],['../group__lwm2m__objects__ipso__sensor__base__config.html',1,'LwM2M IPSO Sensor base object compile configurations'],['../group__lwm2m__objects__light__control__config.html',1,'LwM2M Light Control object compile configurations'],['../group__lwm2m__objects__security__config.html',1,'LwM2M Security object compile configurations'],['../group__lwm2m__objects__temperature__config.html',1,'LwM2M Temperature Sensor object compile configurations'],['../group__lwm2m__objects__voltage__config.html',1,'LwM2M Voltage Sensor object compile configurations'],['../group__pkg__mbedtls__config.html',1,'Mbed TLS package compile configurations'],['../group__net__mqtt__conf.html',1,'MQTT client compile configurations'],['../group__net__nanocoap__conf.html',1,'nanoCoAP compile configurations'],['../group__net__netif__conf.html',1,'Network interfaces compile configurations'],['../group__config__posix.html',1,'POSIX wrapper compile configurations'],['../group__drivers__sm__pwm__01c__conf.html',1,'SM_PWM_01C  compile configurations'],['../group__net__sock__conf.html',1,'SOCK compile configurations'],['../group__net__sock__util__conf.html',1,'SOCK utility functions compile configurations'],['../group__drivers__periph__wdt__conf.html',1,'WDT compile configurations']]],
  ['compile_20time_20configuration_174',['compile time configuration',['../group__sys__congure__config.html',1,'CongURE compile time configuration'],['../group__net__sock__dodtls__conf.html',1,'DNS over DTLS compile-time configuration'],['../group__pkg__libschc__config.html',1,'libSCHC compile-time configuration'],['../group__cpu__stm32__wl__config.html',1,'STM32WL compile time configuration'],['../group__tinydtls__config.html',1,'Tinydtls compile time configuration']]],
  ['compile_20time_20configurations_175',['Compile time configurations',['../group__config.html',1,'']]],
  ['compile_20time_20configurations_176',['compile time configurations',['../group__sys__shell__config.html',1,'Shell compile time configurations'],['../group__usb__conf.html',1,'USB peripheral compile time configurations'],['../group__usbus__cdc__acm__conf.html',1,'USBUS CDC ACM compile time configurations'],['../group__usb__usbus__conf.html',1,'USBUS compile time configurations']]],
  ['compliant_20temperature_20sensor_20driver_177',['JC42 compliant temperature sensor driver',['../group__drivers__jc42.html',1,'']]],
  ['compliant_20uuid_20s_178',['RFC 4122 compliant UUID&apos;s',['../group__sys__uuid.html',1,'']]],
  ['composer_179',['DNS message parser and composer',['../group__net__dns__msg.html',1,'']]],
  ['composition_20configuration_180',['DNS message parsing and composition configuration',['../group__net__dns__msg__conf.html',1,'']]],
  ['compression_181',['Pointer Compression',['../group__sys__util__zptr.html',1,'']]],
  ['compression_182',['Contexts for 6LoWPAN address compression',['../group__net__gnrc__sixlowpan__ctx.html',1,'']]],
  ['compression_20iphc_183',['IPv6 header compression (IPHC)',['../group__net__gnrc__sixlowpan__iphc.html',1,'']]],
  ['compression_20libraries_184',['Data Compression Libraries',['../group__sys__compression.html',1,'']]],
  ['compression_20library_185',['compression library',['../group__pkg__heatshrink.html',1,'Lightweight compression library'],['../group__pkg__lz4.html',1,'LZ4 compression library']]],
  ['condition_20variable_186',['Condition Variable',['../group__core__sync__cond.html',1,'']]],
  ['configuration_187',['Configuration',['../group__net__cord__config.html',1,'CoRE RD Configuration'],['../group__boards__common__gd32v.html',1,'GD32V Common Configuration'],['../group__core__internal.html',1,'Startup and Configuration']]],
  ['configuration_188',['configuration',['../group__drivers__seesaw__soil__config.html',1,'Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration'],['../group__drivers__ads101x__config.html',1,'ADS101 driver compile configuration'],['../group__drivers__at__config.html',1,'AT driver compile configuration'],['../group__drivers__at86rf215__config.html',1,'AT86RF215 driver compile configuration'],['../group__drivers__atca__config.html',1,'ATCA driver compile configuration'],['../group__drivers__bmx055__config.html',1,'BMX055 sensor driver compile configuration'],['../group__sys__congure__config.html',1,'CongURE compile time configuration'],['../group__core__init__config.html',1,'Core initialization compile configuration'],['../group__drivers__kw2xrf__config.html',1,'CR20A and KW2xD radio driver compile configuration'],['../group__drivers__dose__config.html',1,'Differentially Operated Serial Ethernet (DOSE) driver compile configuration'],['../group__net__dns__msg__conf.html',1,'DNS message parsing and composition configuration'],['../group__net__sock__dodtls__conf.html',1,'DNS over DTLS compile-time configuration'],['../group__drivers__ds1307__config.html',1,'DS1307 RTC driver compile configuration'],['../group__drivers__ethos__config.html',1,'Ethernet-over-serial driver driver compile configuration'],['../group__drivers__fxos8700__config.html',1,'FXOS8700 accelerometer/magnetometer driver compile configuration'],['../group__gcoap__dns__config.html',1,'GCoAP DNS over CoAP client configuration'],['../group__net__gnrc__gomach__conf.html',1,'GNRC GoMacH compile configuration'],['../group__drivers__hdc1000__config.html',1,'HDC1000 Humidity and Temperature Sensor driver compile configuration'],['../group__drivers__isl29020__config.html',1,'ISL29020 light sensor driver compile configuration'],['../group__drivers__kw41zrf__config.html',1,'KW41Z, KW21Z in-cpu transceiver driver compile configuration'],['../group__drivers__l3g4200d__config.html',1,'L3G4200D gyroscope driver compile configuration'],['../group__pkg__libschc__config.html',1,'libSCHC compile-time configuration'],['../group__drivers__lm75.html',1,'LM75 Temperature Sensor driver compile configuration'],['../group__drivers__lpsxxx__config.html',1,'LPS331AP/LPS25HB/LPS22HB/LPS22HH/LPS22CH driver compile configuration'],['../group__lwm2m__objects__device__config.html',1,'LwM2M Device Object configuration'],['../group__drivers__mag3110__config.html',1,'MAG3110 Magnetometer driver compile configuration'],['../group__drivers__mma8x5x__config.html',1,'MMA8x5x Accelerometer driver compile configuration'],['../group__drivers__motor__driver__config.html',1,'Motor_Driver driver compile configuration'],['../group__drivers__mpl3115a2__config.html',1,'MPL3115A2 Pressure Sensor driver compile configuration'],['../group__drivers__mrf24j40__config.html',1,'mrf24j40 driver compile configuration'],['../group__drivers__nrf52__802154__conf.html',1,'nrf802154 driver compile configuration'],['../group__drivers__opt3001__config.html',1,'OPT3001 Ambient Light Sensor driver compile configuration'],['../group__drivers__pir__config.html',1,'PIR Motion Sensor driver compile configuration'],['../group__drivers__pn532__config.html',1,'PN532 NFC Radio driver compile configuration'],['../group__drivers__rn2xx3__config.html',1,'RN2483/RN2903 Radio driver compile configuration'],['../group__drivers__mtd__sdcard__config.html',1,'SDCard driver compile configuration'],['../group__drivers__sx127x__config.html',1,'Semtech SX1272 and SX1276 driver compile configuration'],['../group__net__gnrc__ipv6__auto__subnets.html',1,'Simple-Subnet auto-configuration'],['../group__drivers__slipdev__config.html',1,'SLIP Network driver compile configuration'],['../group__net__sock__dtls__conf.html',1,'SOCK DTLS compile configuration'],['../group__drivers__softspi__config.html',1,'Software SPI driver compile configuration'],['../group__drivers__SPS30__config.html',1,'SPS30 PM Sensor driver compile configuration'],['../group__cpu__stm32__wl__config.html',1,'STM32WL compile time configuration'],['../group__drivers__tcs37727__config.html',1,'TCS37727 RGB Light Sensor driver compile configuration'],['../group__tinydtls__config.html',1,'Tinydtls compile time configuration'],['../group__drivers__tmp00x__config.html',1,'TMP006/TMP007 Infrared Thermopile Sensor driver compile configuration'],['../group__lwm2m__client__config.html',1,'Wakaama LwM2M Client configuration']]],
  ['configuration_20header_189',['NanoCBOR configuration header',['../group__nanocbor__config.html',1,'']]],
  ['configuration_20options_20for_20network_20apis_190',['Netopt - Configuration options for network APIs',['../group__net__netopt.html',1,'']]],
  ['configuration_20options_20for_20usb_20apis_191',['usbopt - Configuration options for USB APIs',['../group__usb__usbopt.html',1,'']]],
  ['configuration_20protocol_20for_20ipv6_20dhcpv6_192',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['configuration_20snippets_193',['Configuration Snippets',['../group__boards__common__cc2538.html',1,'cc2538 Configuration Snippets'],['../group__boards__common__stm32.html',1,'STM32 Configuration Snippets']]],
  ['configuration_20snippets_20for_20msp430_20boards_194',['Common Configuration Snippets for MSP430 boards',['../group__boards__common__msp430.html',1,'']]],
  ['configurations_195',['Configurations',['../group__config__drivers__actuators.html',1,'Actuator Device Configurations'],['../group__config__cpu.html',1,'CPU Configurations'],['../group__config__drivers__display.html',1,'Display Device Configurations'],['../group__config__drivers__misc.html',1,'Miscellaneous Device Configurations'],['../group__config__drivers__netdev.html',1,'Network Device Configurations'],['../group__config__drivers__sensors.html',1,'Sensor Device Configurations'],['../group__config__drivers__soft__periph.html',1,'Soft Peripheral Configurations'],['../group__config__drivers__storage.html',1,'Storage Device Configurations']]],
  ['configurations_196',['configurations',['../group__net__credman__conf.html',1,'(D)TLS Credential Manager compile configurations'],['../group__drivers__adcxx1c__config.html',1,'ADCXX1C driver compile configurations'],['../group__net__asymcute__conf.html',1,'Asymcute (MQTT-SN Client) compile configurations'],['../group__net__coap__conf.html',1,'CoAP compile configurations'],['../group__config.html',1,'Compile time configurations'],['../group__net__csma__sender__conf.html',1,'CSMA/CA helper compile configurations'],['../group__net__dhcpv6__conf.html',1,'DHCPv6 compile configurations'],['../group__net__emcute__conf.html',1,'EmCute (MQTT-SN Client) compile configurations'],['../group__sys__entropy__source__config.html',1,'Entropy Source compile configurations'],['../group__cpu__esp__common__conf.html',1,'ESP common compile configurations'],['../group__cpu__esp32__conf.html',1,'ESP32 compile configurations'],['../group__cpu__esp8266__conf.html',1,'ESP8266 compile configurations'],['../group__net__gcoap__conf.html',1,'GCoAP compile configurations'],['../group__net__gnrc__sixlowpan__config.html',1,'GNRC 6LoWPAN compile configurations'],['../group__net__gnrc__conf.html',1,'GNRC compile configurations'],['../group__net__gnrc__ipv6__blacklist__conf.html',1,'GNRC IPv6 address blacklisting compile configurations'],['../group__net__gnrc__ipv6__whitelist__conf.html',1,'GNRC IPv6 address whitelisting compile configurations'],['../group__net__gnrc__ipv6__conf.html',1,'GNRC IPv6 compile configurations'],['../group__net__gnrc__ipv6__ext__conf.html',1,'GNRC IPv6 extension header compile configurations'],['../group__net__gnrc__ipv6__nib__conf.html',1,'GNRC IPv6 NIB compile configurations'],['../group__net__gnrc__lorawan__conf.html',1,'GNRC LoRaWAN compile configurations'],['../group__net__gnrc__lwmac__conf.html',1,'GNRC LWMAC compile configurations'],['../group__net__gnrc__mac__conf.html',1,'GNRC MAC compile configurations'],['../group__net__gnrc__netif__conf.html',1,'GNRC network interface configurations'],['../group__net__gnrc__pktbuf__conf.html',1,'GNRC PKTBUF compile configurations'],['../group__net__gnrc__pktdump__conf.html',1,'GNRC PKTDUMP compile configurations'],['../group__net__gnrc__sock__conf.html',1,'GNRC sock implementation compile configurations'],['../group__net__gnrc__tcp__conf.html',1,'GNRC TCP compile configurations'],['../group__net__gnrc__udp__conf.html',1,'GNRC UDP compile configurations'],['../group__drivers__gp2y10xx__config.html',1,'GP2Y10xx driver compile configurations'],['../group__net__ieee802154__conf.html',1,'IEEE802.15.4 compile configurations'],['../group__net__l2filter__conf.html',1,'Link layer address filter compile configurations'],['../group__net__lora__conf.html',1,'LoRa modulation compile configurations'],['../group__net__loramac__conf.html',1,'LoRaMAC compile configurations'],['../group__lwm2m__objects__barometer__config.html',1,'LwM2M Barometer object compile configurations'],['../group__lwm2m__objects__current__config.html',1,'LwM2M Current Sensor object compile configurations'],['../group__lwm2m__objects__humidity__config.html',1,'LwM2M Humidity Sensor object compile configurations'],['../group__lwm2m__objects__illuminance__config.html',1,'LwM2M Illuminance Sensor object compile configurations'],['../group__lwm2m__objects__ipso__sensor__base__config.html',1,'LwM2M IPSO Sensor base object compile configurations'],['../group__lwm2m__objects__light__control__config.html',1,'LwM2M Light Control object compile configurations'],['../group__lwm2m__objects__security__config.html',1,'LwM2M Security object compile configurations'],['../group__lwm2m__objects__temperature__config.html',1,'LwM2M Temperature Sensor object compile configurations'],['../group__lwm2m__objects__voltage__config.html',1,'LwM2M Voltage Sensor object compile configurations'],['../group__pkg__mbedtls__config.html',1,'Mbed TLS package compile configurations'],['../group__net__mqtt__conf.html',1,'MQTT client compile configurations'],['../group__net__nanocoap__conf.html',1,'nanoCoAP compile configurations'],['../group__net__netif__conf.html',1,'Network interfaces compile configurations'],['../group__config__posix.html',1,'POSIX wrapper compile configurations'],['../group__sys__shell__config.html',1,'Shell compile time configurations'],['../group__drivers__sm__pwm__01c__conf.html',1,'SM_PWM_01C  compile configurations'],['../group__net__sock__conf.html',1,'SOCK compile configurations'],['../group__net__sock__util__conf.html',1,'SOCK utility functions compile configurations'],['../group__usb__conf.html',1,'USB peripheral compile time configurations'],['../group__usbus__cdc__acm__conf.html',1,'USBUS CDC ACM compile time configurations'],['../group__usb__usbus__conf.html',1,'USBUS compile time configurations'],['../group__drivers__periph__wdt__conf.html',1,'WDT compile configurations']]],
  ['congestion_20control_20for_206lowpan_20sfr_197',['Congestion control for 6LoWPAN SFR',['../group__net__gnrc__sixlowpan__frag__sfr__congure.html',1,'']]],
  ['congestion_20control_20framework_198',['CongURE - A Congestion control framework',['../group__sys__congure.html',1,'']]],
  ['congure_20a_20congestion_20control_20framework_199',['CongURE - A Congestion control framework',['../group__sys__congure.html',1,'']]],
  ['congure_20compile_20time_20configuration_200',['CongURE compile time configuration',['../group__sys__congure__config.html',1,'']]],
  ['congure_20implementation_20of_20quic_20s_20cc_201',['CongURE implementation of QUIC&apos;s CC',['../group__sys__congure__quic.html',1,'']]],
  ['congure_20implementation_20of_20tcp_20abe_202',['CongURE implementation of TCP ABE',['../group__sys__congure__abe.html',1,'']]],
  ['congure_20implementation_20of_20tcp_20reno_203',['CongURE implementation of TCP Reno',['../group__sys__congure__reno.html',1,'']]],
  ['congure_20mock_20implementation_204',['CongURE mock implementation',['../group__sys__congure__mock.html',1,'']]],
  ['congure_20tcp_20reno_205',['The send driver methods for CongURE TCP Reno',['../group__sys__congure__reno__methods.html',1,'']]],
  ['congure_20test_20framework_20shell_20commands_206',['CongURE test framework shell commands',['../group__sys__congure__test.html',1,'']]],
  ['connection_207',['Connection',['../group__sys__can__conn.html',1,'']]],
  ['connection_20state_20management_20for_20netif_208',['Connection State Management for netif',['../group__pkg__nimble__netif__conn.html',1,'']]],
  ['constfs_20static_20file_20system_209',['ConstFS static file system',['../group__sys__fs__constfs.html',1,'']]],
  ['constructor_20guards_20for_20static_20instances_210',['C++ constructor guards for static instances',['../group__sys__cxx__ctor__guards.html',1,'']]],
  ['container_211',['Universal Address Container',['../group__sys__universal__address.html',1,'']]],
  ['contexts_20for_206lowpan_20address_20compression_212',['Contexts for 6LoWPAN address compression',['../group__net__gnrc__sixlowpan__ctx.html',1,'']]],
  ['control_213',['Control',['../group__cpu__cc2538__sysctrl.html',1,'CC2538 System Control'],['../group__lwm2m__objects__light__control.html',1,'Light Control']]],
  ['control_20for_206lowpan_20sfr_214',['Congestion control for 6LoWPAN SFR',['../group__net__gnrc__sixlowpan__frag__sfr__congure.html',1,'']]],
  ['control_20for_20debugging_20profiling_215',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['control_20framework_216',['CongURE - A Congestion control framework',['../group__sys__congure.html',1,'']]],
  ['control_20model_217',['control model',['../group__usbus__cdc__acm.html',1,'USBUS CDC ACM - USBUS CDC abstract control model'],['../group__usbus__cdc__ecm.html',1,'USBUS CDC ECM - USBUS CDC ethernet control model']]],
  ['control_20object_20compile_20configurations_218',['LwM2M Light Control object compile configurations',['../group__lwm2m__objects__light__control__config.html',1,'']]],
  ['control_20on_20board_20leds_219',['Control on-board LEDs',['../group__drivers__led.html',1,'']]],
  ['controller_220',['Controller',['../group__cpu__sam0__common__sdhc.html',1,'sam0 SD Host Controller'],['../group__drivers__stmpe811.html',1,'STMPE811 Touchscreen Controller']]],
  ['controller_221',['controller',['../group__drivers__aip31068.html',1,'AIP31068 I2C LCD controller'],['../group__boards__common__silabs__drivers__bc.html',1,'Board communication controller'],['../group__cpu__esp32__esp__can.html',1,'ESP32 CAN controller'],['../group__drivers__mfrc522.html',1,'MFRC522 RFID controller'],['../group__drivers__my9221.html',1,'MY9221 LED controller'],['../group__drivers__pca9633.html',1,'PCA9633 I2C PWM controller'],['../group__drivers__pca9685.html',1,'PCA9685 I2C PWM controller'],['../group__candev__stm32.html',1,'STM32 CAN controller']]],
  ['controller_20area_20network_222',['CAN (Controller Area Network)',['../group__sys__can.html',1,'']]],
  ['conversion_20layer_223',['ztimer_convert_frac frequency conversion layer',['../group__sys__ztimer__convert__frac.html',1,'']]],
  ['conversion_20modules_224',['ztimer frequency conversion modules',['../group__sys__ztimer__convert.html',1,'']]],
  ['conversion_20using_20shifts_225',['conversion using shifts',['../group__sys__ztimer__convert__shift.html',1,'']]],
  ['conversion_20utilities_226',['Analog data conversion utilities',['../group__sys__analog__util.html',1,'']]],
  ['conversions_20as_20provided_20by_20most_20libcs_227',['endian conversions as provided by most libcs',['../group__sys__endian.html',1,'']]],
  ['converter_228',['NXP QN908x ADC - Analog to Digital converter',['../group__cpu__qn908x__adc.html',1,'']]],
  ['converter_20driver_229',['MAX31855 Thermocouple-to-Digital Converter driver',['../group__drivers__max31855.html',1,'']]],
  ['converter_20driver_230',['AD7746 Capacitance-to-digital converter driver',['../group__drivers__ad7746.html',1,'']]],
  ['core_231',['Spark-Core',['../group__boards__spark-core.html',1,'']]],
  ['core_232',['mynewt-core',['../group__pkg__mynewt__core.html',1,'']]],
  ['core_20clock_233',['System core clock',['../group__sys__clk.html',1,'']]],
  ['core_20driver_20for_20decawave_20dw1000_20transceiver_234',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['core_20initialization_20compile_20configuration_235',['Core initialization compile configuration',['../group__core__init__config.html',1,'']]],
  ['core_20interface_236',['CC2538 RF core interface',['../group__cpu__cc2538__rfcore.html',1,'']]],
  ['core_20link_20format_237',['CoRE Link Format',['../group__sys__clif.html',1,'']]],
  ['core_20rd_20common_238',['CoRE RD Common',['../group__net__cord__common.html',1,'']]],
  ['core_20rd_20configuration_239',['CoRE RD Configuration',['../group__net__cord__config.html',1,'']]],
  ['core_20rd_20endpoint_240',['CoRE RD Endpoint',['../group__net__cord__ep.html',1,'']]],
  ['core_20rd_20endpoint_20and_20lookup_20client_241',['CoRE RD Endpoint and Lookup Client',['../group__net__cord.html',1,'']]],
  ['core_20rd_20endpoint_20standalone_20extension_242',['CoRE RD Endpoint Standalone Extension',['../group__net__cord__ep__standalone.html',1,'']]],
  ['core_20rd_20lookup_20client_243',['CoRE RD Lookup Client',['../group__net__cord__lc.html',1,'']]],
  ['core_20rd_20simple_20registration_20endpoint_244',['CoRE RD Simple Registration Endpoint',['../group__net__cord__epsim.html',1,'']]],
  ['corejson_245',['FreeRTOS coreJSON',['../group__pkg__corejson.html',1,'']]],
  ['corerf_246',['Microduino CoreRF',['../group__boards__microduino-corerf.html',1,'']]],
  ['cores_247',['Hardware independent layer of the Arduino cores',['../group__pkg__arduino__api.html',1,'']]],
  ['correction_20codes_248',['Error correction codes',['../group__sys__coding.html',1,'']]],
  ['cortex_20m_20common_249',['ARM Cortex-M common',['../group__cpu__cortexm__common.html',1,'']]],
  ['coulomb_20counter_250',['LTC4150 coulomb counter',['../group__drivers__ltc4150.html',1,'']]],
  ['counter_251',['counter',['../group__drivers__ltc4150.html',1,'LTC4150 coulomb counter'],['../group__drivers__pulse__counter.html',1,'Pulse counter']]],
  ['counter_20timers_20ctimer_252',['NXP QN908x Standard counter/timers (CTIMER)',['../group__cpu__qn908x__timer.html',1,'']]],
  ['cpu_253',['CPU',['../group__cpu.html',1,'']]],
  ['cpu_20common_254',['ARM7 CPU common',['../group__cpu__arm7__common.html',1,'']]],
  ['cpu_20configurations_255',['CPU Configurations',['../group__config__cpu.html',1,'']]],
  ['cpu_20transceiver_20driver_20compile_20configuration_256',['KW41Z, KW21Z in-cpu transceiver driver compile configuration',['../group__drivers__kw41zrf__config.html',1,'']]],
  ['cpu_3a_20common_20files_257',['CPU: common files',['../group__cpu__atmega__common.html',1,'Atmel ATmega CPU: common files'],['../group__cpu__avr8__common.html',1,'Atmel AVR-8 CPU: common files']]],
  ['cpu_5fspecific_5fperipheral_5fmemory_5fmap_258',['Cpu_specific_Peripheral_memory_map',['../group__cpu__specific__Peripheral__memory__map.html',1,'']]],
  ['cpuid_259',['CPUID',['../group__drivers__periph__cpuid.html',1,'CPUID'],['../group__cpu__kinetis__cpuid.html',1,'Kinetis CPUID'],['../group__cpu__qn908x__cpuid.html',1,'NXP QN908x CPUID']]],
  ['cr20a_20and_20kw2xd_20radio_20driver_20compile_20configuration_260',['CR20A and KW2xD radio driver compile configuration',['../group__drivers__kw2xrf__config.html',1,'']]],
  ['crc_208_261',['CRC-8',['../group__sys__checksum__crc8.html',1,'']]],
  ['crc16_20ccitt_262',['CRC16-CCITT',['../group__sys__checksum__crc16__ccitt.html',1,'']]],
  ['crc16_20lightweight_263',['CRC16 (lightweight)',['../group__sys__checksum__ucrc16.html',1,'']]],
  ['crc32_264',['CRC32',['../group__sys__checksum__crc32.html',1,'']]],
  ['credential_20manager_265',['(D)TLS Credential Manager',['../group__net__credman.html',1,'']]],
  ['credential_20manager_20compile_20configurations_266',['(D)TLS Credential Manager compile configurations',['../group__net__credman__conf.html',1,'']]],
  ['credentials_20api_267',['DTLS sock credentials API',['../group__net__sock__dtls__creds.html',1,'']]],
  ['cross_20platform_20fixed_20point_20maths_20library_268',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['crypto_269',['Crypto',['../group__sys__crypto.html',1,'']]],
  ['crypto_270',['FIDO2 CTAP crypto',['../group__fido2__ctap__crypto.html',1,'']]],
  ['crypto_20algorithm_20dispatcher_271',['PSA Crypto Algorithm Dispatcher',['../group__sys__psa__crypto__alg__disp.html',1,'']]],
  ['crypto_20key_20slot_20management_272',['PSA Crypto Key Slot Management',['../group__sys__psa__crypto__slot__mgmt.html',1,'']]],
  ['crypto_20library_273',['tinycrypt crypto library',['../group__pkg__tinycrypt.html',1,'']]],
  ['crypto_20location_20dispatcher_274',['PSA Crypto Location Dispatcher',['../group__sys__psa__crypto__loc__disp.html',1,'']]],
  ['crypto_20persistent_20storage_20api_275',['PSA Crypto Persistent Storage API',['../group__sys__psa__crypto__pers__stor.html',1,'']]],
  ['crypto_20se_20management_276',['PSA Crypto SE Management',['../group__psa__crypto__se__mgmt.html',1,'']]],
  ['crypto_20secure_20element_20wrapper_277',['PSA Crypto Secure Element Wrapper',['../group__sys__psa__crypto__se__driver.html',1,'']]],
  ['cryptoauthentication_20library_278',['Microchip CryptoAuthentication Library',['../group__pkg__cryptoauthlib.html',1,'']]],
  ['cryptocell_20310_20driver_279',['ARM CryptoCell 310 Driver',['../group__pkg__driver__cryptocell__310.html',1,'']]],
  ['cryptographic_20api_280',['PSA Cryptographic API',['../group__sys__psa__crypto.html',1,'']]],
  ['cryptographic_20hash_20functions_281',['cryptographic hash functions',['../group__sys__hashes__keyed.html',1,'Keyed cryptographic hash functions'],['../group__sys__hashes__non__crypto.html',1,'Non-cryptographic hash functions'],['../group__sys__hashes__unkeyed.html',1,'Unkeyed cryptographic hash functions']]],
  ['cryptographic_20library_282',['HACL* High Assurance Cryptographic Library',['../group__pkg__hacl.html',1,'']]],
  ['cryptographic_20library_283',['cryptographic library',['../group__pkg__c25519.html',1,'C25519 cryptographic library'],['../group__pkg__cifra.html',1,'Cifra cryptographic library'],['../group__pkg__libhydrogen.html',1,'LibHydrogen cryptographic library'],['../group__pkg__monocypher.html',1,'Monocypher cryptographic library'],['../group__pkg__tweetnacl.html',1,'TweetNaCl high-security cryptographic library']]],
  ['cryptography_284',['Secure Element Asymmetric Cryptography',['../group__se__asymmetric.html',1,'']]],
  ['csma_20ca_20helper_285',['CSMA/CA helper',['../group__net__csma__sender.html',1,'']]],
  ['csma_20ca_20helper_20compile_20configurations_286',['CSMA/CA helper compile configurations',['../group__net__csma__sender__conf.html',1,'']]],
  ['cst816s_20touch_20screen_20driver_287',['Cst816S touch screen driver',['../group__drivers__cst816s.html',1,'']]],
  ['ctap_288',['CTAP',['../group__fido2__ctap.html',1,'CTAP'],['../group__fido2__ctap__ctap.html',1,'FIDO2 CTAP']]],
  ['ctap_20cbor_289',['FIDO2 CTAP CBOR',['../group__fido2__ctap__cbor.html',1,'']]],
  ['ctap_20crypto_290',['FIDO2 CTAP crypto',['../group__fido2__ctap__crypto.html',1,'']]],
  ['ctap_20flash_291',['FIDO2 CTAP flash',['../group__fido2__ctap__mem.html',1,'']]],
  ['ctap_20transport_292',['FIDO2 CTAP transport',['../group__fido2__ctap__transport.html',1,'']]],
  ['ctap_20utils_293',['FIDO2 CTAP utils',['../group__fido2__ctap__utils.html',1,'']]],
  ['ctaphid_294',['FIDO2 CTAPHID',['../group__fido2__ctap__transport__hid.html',1,'']]],
  ['ctimer_295',['NXP QN908x Standard counter/timers (CTIMER)',['../group__cpu__qn908x__timer.html',1,'']]],
  ['ctuator_20u_20ber_20l_20ayer_296',['[S]ensor [A]ctuator [U]ber [L]ayer',['../group__drivers__saul.html',1,'']]],
  ['current_297',['Current',['../group__lwm2m__objects__current.html',1,'']]],
  ['current_20power_20monitor_298',['current power monitor',['../group__drivers__ina2xx.html',1,'INA2XX current/power monitor'],['../group__drivers__ina3221.html',1,'INA3221 current/power monitor']]],
  ['current_20sensor_20object_20compile_20configurations_299',['LwM2M Current Sensor object compile configurations',['../group__lwm2m__objects__current__config.html',1,'']]],
  ['custom_20ethertype_300',['Custom ethertype',['../group__net__ethertype__custom__config.html',1,'']]]
];
