var searchData=
[
  ['d_20tls_20credential_20manager_0',['(D)TLS Credential Manager',['../group__net__credman.html',1,'']]],
  ['d_20tls_20credential_20manager_20compile_20configurations_1',['(D)TLS Credential Manager compile configurations',['../group__net__credman__conf.html',1,'']]],
  ['d10_20xplained_20mini_2',['Atmel SAM D10 Xplained Mini',['../group__boards__samd10-xmini.html',1,'']]],
  ['d20_20xplained_20pro_3',['Atmel SAM D20 Xplained Pro',['../group__boards__samd20-xpro.html',1,'']]],
  ['d21_20xplained_20pro_4',['Atmel SAM D21 Xplained Pro',['../group__boards__samd21-xpro.html',1,'']]],
  ['d32_20pro_5',['Wemos LOLIN D32 Pro',['../group__boards__esp32__wemos-lolin-d32-pro.html',1,'']]],
  ['dac_6',['DAC',['../group__drivers__periph__dac.html',1,'']]],
  ['dac_20direct_20digital_20synthesis_7',['DAC Direct Digital Synthesis',['../group__drivers__dac__dds.html',1,'']]],
  ['dac_20with_20i2c_20interface_8',['MCP47xx DAC with I2C interface',['../group__drivers__mcp47xx.html',1,'']]],
  ['data_9',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['data_20ad_20processing_10',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['data_20compression_20libraries_11',['Data Compression Libraries',['../group__sys__compression.html',1,'']]],
  ['data_20conversion_20utilities_12',['Analog data conversion utilities',['../group__sys__analog__util.html',1,'']]],
  ['data_20link_20layer_13',['Data Link Layer',['../group__sys__can__dll.html',1,'Data Link Layer'],['../group__net__ppp.html',1,'Point-to-Point Protocol (PPP) Data Link Layer']]],
  ['database_20for_20flash_14',['FlashDB: Database for Flash',['../group__pkg__flashdb.html',1,'']]],
  ['daughter_20board_20drivers_15',['Shields - hardware extension daughter board drivers',['../group__drivers__shield.html',1,'']]],
  ['dc_20motor_20driver_16',['DC Motor Driver',['../group__drivers__motor.html',1,'']]],
  ['dcf77_20long_20wave_20receiver_20with_2077_205_20khz_17',['DCF77 long wave receiver with 77,5 kHz',['../group__drivers__dcf77.html',1,'']]],
  ['debug_20helper_18',['IRQ Disable Debug helper',['../group__debug__irq__disable.html',1,'']]],
  ['debug_20pins_19',['debug pins',['../group__cpu__stm32__wl__debug__subghz__radio.html',1,'STM32WL Sub-GHz Radio debug pins'],['../group__cpu__stm32__wl__debug__subghz__spi.html',1,'STM32WL Sub-GHz SPI debug pins']]],
  ['debug_20serial_20jtag_20',['STDIO over ESP32 Debug Serial/JTAG',['../group__stdio__usb__serial__jtag.html',1,'']]],
  ['debugging_21',['STM32WL hardware debugging',['../group__cpu__stm32__wl__debug.html',1,'']]],
  ['debugging_20profiling_22',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['decawave_20dw1000_20transceiver_23',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['decawave_20dwm1001_24',['Decawave DWM1001',['../group__boards__dwm1001.html',1,'']]],
  ['decawave_20impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_25',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['decimal_26',['Binary coded decimal',['../group__sys__bcd.html',1,'']]],
  ['decoder_27',['base64 encoder decoder',['../group__sys__base64.html',1,'']]],
  ['decoder_20qdec_28',['Quadrature Decoder (QDEC)',['../group__drivers__periph__qdec.html',1,'']]],
  ['decoding_20encoding_20library_29',['Lightweight ASN.1 decoding/encoding library',['../group__pkg__tiny-asn1.html',1,'']]],
  ['deduplication_30',['Link-layer Broadcast deduplication',['../group__net__gnrc__netif__dedup.html',1,'']]],
  ['defines_31',['MQTT-SN Defines',['../group__net__mqttsn.html',1,'']]],
  ['defines_32',['defines',['../group__net__coap.html',1,'CoAP defines'],['../group__net__dns.html',1,'DNS defines'],['../group__net__dns__mock.html',1,'DNS defines'],['../group__ble__defs.html',1,'Generic BLE defines']]],
  ['definitions_33',['Definitions',['../group__cpu__atmega1281__definitions.html',1,'Atmel ATmega1281 Definitions'],['../group__cpu__atmega1284p__definitions.html',1,'Atmel ATmega1284p Definitions'],['../group__cpu__atmega2560__definitions.html',1,'Atmel ATmega2560 Definitions'],['../group__cpu__atmega328p__definitions.html',1,'Atmel ATmega328p Definitions'],['../group__cpu__atmega32u4__definitions.html',1,'Atmel ATmega32u4 Definitions'],['../group__cpu__atmega8__definitions.html',1,'Atmel ATmega8 Definitions'],['../group__CC2538__cmsis.html',1,'CMSIS Definitions'],['../group__CC13x2__cmsis.html',1,'CMSIS Definitions']]],
  ['definitions_34',['definitions',['../group__sys__can__common.html',1,'Common definitions'],['../group__net__ieee802154__header.html',1,'IEEE 802.15.4 frame headers and definitions'],['../group__net__gnrc__ipv6__hdr.html',1,'IPv6 header definitions'],['../group__cpu__cc26x0__cc13x0__definitions.html',1,'TI CC26x0/CC13x0 definitions'],['../group__cpu__cc26x2__cc13x2__definitions.html',1,'TI CC26x2, CC13x2 definitions']]],
  ['delete_20operator_20module_35',['C++ new and delete operator module',['../group__sys__cpp__new__delete.html',1,'']]],
  ['demo_20board_36',['STM32F030F4 Demo Board',['../group__boards__stm32f030f4-demo.html',1,'']]],
  ['demonstration_37',['Talking LEDs - Arduino library for demonstration',['../group__pkg__talking__leds.html',1,'']]],
  ['deprecated_38',['xtimer high level timer abstraction layer (deprecated)',['../group__sys__xtimer.html',1,'']]],
  ['derfmega128_20modules_20from_20dresden_20elektronik_39',['deRFmega128 modules from Dresden Elektronik',['../group__boards__deRFmega128.html',1,'']]],
  ['derfmega256_20modules_20from_20dresden_20elektronik_40',['deRFmega256 modules from Dresden Elektronik',['../group__boards__deRFmega256.html',1,'']]],
  ['derivation_20and_20agreement_41',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['descriptor_20formatter_20functions_42',['USBUS descriptor formatter functions',['../group__usb__usbus__fmt.html',1,'']]],
  ['descriptor_20helpers_43',['USB HID descriptor helpers',['../group__usb__hid__descriptor.html',1,'']]],
  ['descriptors_44',['USB descriptors',['../group__usb__descriptor.html',1,'']]],
  ['destination_20and_20hop_20by_20hop_20options_45',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['destructive_20uri_20parser_46',['A minimal, non-destructive URI parser',['../group__sys__uri__parser.html',1,'']]],
  ['dev_47',['Olimex MOD-WIFI-ESP8266-DEV',['../group__boards__esp8266__olimex-mod.html',1,'']]],
  ['development_20board_20stm32wle5jc_48',['LoRa-E5 Development Board - STM32WLE5JC',['../group__boards__lora-e5-dev.html',1,'']]],
  ['development_20kit_49',['Development Kit',['../group__boards__nrf51dk.html',1,'nRF51DK Development Kit'],['../group__boards__nrf6310.html',1,'NRF6310 (Nordic NRF Hardware Development Kit)']]],
  ['development_20kit_50',['development kit',['../group__boards__mbed__lpc1768.html',1,'mbed LPC1768 development kit'],['../group__boards__seeduino__arch-pro.html',1,'Seeeduino Arch Pro development kit']]],
  ['devfs_20device_20file_20system_51',['DevFS device file system',['../group__sys__fs__devfs.html',1,'']]],
  ['device_52',['Memory Technology Device',['../group__drivers__mtd.html',1,'']]],
  ['device_53',['device',['../group__drivers__slipdev.html',1,'SLIP network device'],['../group__drivers__usbdev__mock.html',1,'USBdev mockup device']]],
  ['device_20and_20endpoint_20manager_54',['USBUS device and endpoint manager',['../group__usb__usbus.html',1,'']]],
  ['device_20api_20sdmmc_55',['SDIO/SD/MMC Device API (SDMMC)',['../group__drivers__sdmmc.html',1,'']]],
  ['device_20class_56',['device class',['../group__usb__cdc.html',1,'CDC - USB communications device class'],['../group__usb__hid.html',1,'HID - USB communications device class']]],
  ['device_20configurations_57',['Device Configurations',['../group__config__drivers__actuators.html',1,'Actuator Device Configurations'],['../group__config__drivers__display.html',1,'Display Device Configurations'],['../group__config__drivers__misc.html',1,'Miscellaneous Device Configurations'],['../group__config__drivers__netdev.html',1,'Network Device Configurations'],['../group__config__drivers__sensors.html',1,'Sensor Device Configurations'],['../group__config__drivers__storage.html',1,'Storage Device Configurations']]],
  ['device_20driver_58',['device driver',['../group__drivers__adcxx1c.html',1,'ADCXX1C ADC device driver'],['../group__drivers__ads101x.html',1,'ADS101x/111x ADC device driver'],['../group__drivers__gp2y10xx.html',1,'GP2Y10xx Optical Dust Sensor device driver'],['../group__drivers__ph__oem.html',1,'pH OEM sensor device driver']]],
  ['device_20driver_20api_59',['Device Driver API',['../group__drivers__netdev__api.html',1,'Netdev - Network Device Driver API'],['../group__drivers__periph__usbdev.html',1,'usbdev - USB Device Driver API']]],
  ['device_20driver_20interface_60',['CAN device driver interface',['../group__drivers__candev.html',1,'']]],
  ['device_20driver_20model_20for_20the_20decawave_20impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_61',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['device_20drivers_62',['Device Drivers',['../group__drivers__actuators.html',1,'Actuator Device Drivers'],['../group__drivers__display.html',1,'Display Device Drivers'],['../group__drivers__multimedia.html',1,'Multimedia Device Drivers'],['../group__drivers__netdev.html',1,'Network Device Drivers'],['../group__drivers__sensors.html',1,'Sensor Device Drivers'],['../group__drivers__storage.html',1,'Storage Device Drivers']]],
  ['device_20file_20system_63',['DevFS device file system',['../group__sys__fs__devfs.html',1,'']]],
  ['device_20firmware_64',['Initialization of USB Device Firmware',['../group__sys__riotboot__usb__dfu.html',1,'']]],
  ['device_20firmware_20upgrade_65',['Device Firmware Upgrade',['../group__usb__dfu.html',1,'DFU - USB Device Firmware Upgrade'],['../group__usbus__dfu.html',1,'USBUS DFU - USB Device Firmware Upgrade']]],
  ['device_20generic_20api_66',['device generic API',['../group__drivers__disp__dev.html',1,'Display device generic API'],['../group__drivers__screen__dev.html',1,'Screen device generic API'],['../group__drivers__touch__dev.html',1,'Touch device generic API']]],
  ['device_20gesture_20recognition_67',['Touch device gesture recognition',['../group__drivers__touch__dev__gestures.html',1,'']]],
  ['device_20initialisation_68',['SAUL Device Initialisation',['../group__drivers__saul__init__devs.html',1,'']]],
  ['device_20level_69',['Packet interface on device level',['../group__net__packet.html',1,'']]],
  ['device_20lwm2m_20object_70',['Device LwM2M object',['../group__lwm2m__objects__device.html',1,'']]],
  ['device_20object_20configuration_71',['LwM2M Device Object configuration',['../group__lwm2m__objects__device__config.html',1,'']]],
  ['device_20processing_72',['device processing',['../group__test__utils__netdev__eth__minimal.html',1,'Minimal netdev Ethernet device processing'],['../group__test__utils__netdev__ieee802154__minimal.html',1,'Minimal netdev IEEE 802.15.4 device processing']]],
  ['devices_73',['devices',['../group__drivers__mtd__emulated.html',1,'MTD wrapper for emulated MTD devices'],['../group__drivers__mtd__flashpage.html',1,'MTD wrapper for Flashpage devices'],['../group__drivers__mtd__sam0__sdhc.html',1,'MTD wrapper for SAM0 SDHC devices'],['../group__drivers__mtd__sdmmc.html',1,'MTD wrapper for SD/MMC devices']]],
  ['devkit_20board_74',['DevKit Board',['../group__boards__esp32c3__devkit.html',1,'ESP32-C3-DevKit Board'],['../group__boards__esp32s2__devkit.html',1,'ESP32-S2-DevKit Board'],['../group__boards__esp32s3__devkit.html',1,'ESP32-S3-DevKit Board']]],
  ['dfplayer_20mini_20mp3_20player_75',['DFPlayer Mini MP3 Player',['../group__drivers__dfplayer.html',1,'']]],
  ['dfu_76',['DFU',['../group__bootloader__riotboot__dfu.html',1,'riotboot DFU'],['../group__pkg__tinyusb__dfu.html',1,'riotboot tinyUSB DFU']]],
  ['dfu_20usb_20device_20firmware_20upgrade_77',['DFU USB Device Firmware Upgrade',['../group__usb__dfu.html',1,'DFU - USB Device Firmware Upgrade'],['../group__usbus__dfu.html',1,'USBUS DFU - USB Device Firmware Upgrade']]],
  ['dhcpv6_78',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['dhcpv6_20client_79',['DHCPv6 client',['../group__net__dhcpv6__client.html',1,'']]],
  ['dhcpv6_20client_20for_80',['gnrc_dhcpv6_client_simple_pd: DHCPv6 client for',['../group__net__dhcpv6__client__simple__pd.html',1,'']]],
  ['dhcpv6_20client_20implementation_20in_20gnrc_81',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['dhcpv6_20compile_20configurations_82',['DHCPv6 compile configurations',['../group__net__dhcpv6__conf.html',1,'']]],
  ['dhcpv6_20relay_20agent_83',['DHCPv6 relay agent',['../group__net__dhcpv6__relay.html',1,'']]],
  ['dht_20family_20of_20humidity_20and_20temperature_20sensors_84',['DHT Family of Humidity and Temperature Sensors',['../group__drivers__dht.html',1,'']]],
  ['differential_20pressure_20sensor_85',['SDP3x temperature and differential pressure sensor',['../group__drivers__sdp3x.html',1,'']]],
  ['differentially_20operated_20serial_20ethernet_86',['Differentially Operated Serial Ethernet',['../group__drivers__dose.html',1,'']]],
  ['differentially_20operated_20serial_20ethernet_20dose_20driver_20compile_20configuration_87',['Differentially Operated Serial Ethernet (DOSE) driver compile configuration',['../group__drivers__dose__config.html',1,'']]],
  ['digital_20compass_88',['HMC5883L 3-axis digital compass',['../group__drivers__hmc5883l.html',1,'']]],
  ['digital_20converter_89',['NXP QN908x ADC - Analog to Digital converter',['../group__cpu__qn908x__adc.html',1,'']]],
  ['digital_20converter_20driver_90',['MAX31855 Thermocouple-to-Digital Converter driver',['../group__drivers__max31855.html',1,'']]],
  ['digital_20converter_20driver_91',['AD7746 Capacitance-to-digital converter driver',['../group__drivers__ad7746.html',1,'']]],
  ['digital_20gas_20sensor_92',['CCS 811 digital gas sensor',['../group__drivers__ccs811.html',1,'']]],
  ['digital_20humidity_20sensor_93',['ST HTS221 digital Humidity Sensor',['../group__drivers__hts221.html',1,'']]],
  ['digital_20magnetic_20sensor_94',['QMC5883L 3-Axis Digital Magnetic Sensor',['../group__drivers__qmc5883l.html',1,'']]],
  ['digital_20magnetometer_95',['MAG3110 3-Axis Digital Magnetometer',['../group__drivers__mag3110.html',1,'']]],
  ['digital_20synthesis_96',['DAC Direct Digital Synthesis',['../group__drivers__dac__dds.html',1,'']]],
  ['direct_20digital_20synthesis_97',['DAC Direct Digital Synthesis',['../group__drivers__dac__dds.html',1,'']]],
  ['direct_20pin_20control_20for_20debugging_20profiling_98',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['disable_20debug_20helper_99',['IRQ Disable Debug helper',['../group__debug__irq__disable.html',1,'']]],
  ['disc1_100',['STM32F429I-DISC1',['../group__boards__stm32f429i-disc1.html',1,'']]],
  ['disco_101',['DISCO',['../group__boards__stm32f429i-disco.html',1,'STM32F429I-DISCO'],['../group__boards__stm32f469i-disco.html',1,'STM32F469I-DISCO'],['../group__boards__stm32f746g-disco.html',1,'STM32F746G-DISCO'],['../group__boards__stm32g0316-disco.html',1,'STM32G0316-DISCO'],['../group__boards__stm32l0538-disco.html',1,'STM32L0538-DISCO'],['../group__boards__stm32l476g-disco.html',1,'STM32L476G-DISCO'],['../group__boards__stm32l496g-disco.html',1,'STM32L496G-DISCO']]],
  ['disco_20board_102',['DISCO board',['../group__boards__stm32f723e-disco.html',1,'STM32F723E-DISCO board'],['../group__boards__stm32f769i-disco.html',1,'STM32F769I-DISCO board']]],
  ['discovery_103',['6LoWPAN Neighbor Discovery',['../group__net__sixlowpan__nd.html',1,'']]],
  ['discovery_104',['discovery',['../group__net__gnrc__sixlowpan__nd.html',1,'6LoWPAN neighbor discovery'],['../group__net__ndp.html',1,'IPv6 neighbor discovery'],['../group__boards__b-l072z-lrwan1.html',1,'ST B-L072Z-LRWAN1 LoRa discovery']]],
  ['discovery_20of_20p2p_20routes_20in_20llns_105',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['discovery_20v2_106',['IPv6 neighbor discovery (v2)',['../group__net__gnrc__ndp.html',1,'']]],
  ['disk_20io_20driver_107',['Disk IO Driver',['../group__drivers__diskio.html',1,'']]],
  ['dispatcher_108',['Dispatcher',['../group__sys__psa__crypto__alg__disp.html',1,'PSA Crypto Algorithm Dispatcher'],['../group__sys__psa__crypto__loc__disp.html',1,'PSA Crypto Location Dispatcher']]],
  ['display_20device_20configurations_109',['Display Device Configurations',['../group__config__drivers__display.html',1,'']]],
  ['display_20device_20drivers_110',['Display Device Drivers',['../group__drivers__display.html',1,'']]],
  ['display_20device_20generic_20api_111',['Display device generic API',['../group__drivers__disp__dev.html',1,'']]],
  ['display_20driver_112',['display driver',['../group__drivers__epd__bw__spi.html',1,'Generic black/white e-paper/e-ink SPI display driver.'],['../group__drivers__ili9341.html',1,'ILI9341 display driver'],['../group__drivers__lcd.html',1,'LCD display driver'],['../group__drivers__st77xx.html',1,'ST77xx display driver']]],
  ['displays_113',['U8G2 graphic library for monochome displays',['../group__pkg__u8g2.html',1,'']]],
  ['division_20functions_114',['Integer division functions',['../group__sys__div.html',1,'']]],
  ['djb2_115',['Bernstein hash djb2',['../group__sys__hashes__djb2.html',1,'']]],
  ['dk_116',['DK',['../group__boards__nrf52dk.html',1,'nRF52 DK'],['../group__boards__nrf52840dk.html',1,'nRF52840 DK'],['../group__boards__stm32f750n8-dk.html',1,'STM32F750N8-DK']]],
  ['dk_20board_117',['Generic CC2538-CC2592-DK Board',['../group__boards__generic__cc2538__cc2592__dk.html',1,'']]],
  ['dk_20common_118',['NRF52 DK common',['../group__boards__common__nrf52xxxdk.html',1,'']]],
  ['dk2_20board_119',['STM32MP157C-DK2 board',['../group__boards__stm32mp157c-dk2.html',1,'']]],
  ['dns_20cache_120',['DNS cache',['../group__net__dns__cache.html',1,'']]],
  ['dns_20defines_121',['DNS defines',['../group__net__dns.html',1,'DNS defines'],['../group__net__dns__mock.html',1,'DNS defines']]],
  ['dns_20message_20parser_20and_20composer_122',['DNS message parser and composer',['../group__net__dns__msg.html',1,'']]],
  ['dns_20message_20parsing_20and_20composition_20configuration_123',['DNS message parsing and composition configuration',['../group__net__dns__msg__conf.html',1,'']]],
  ['dns_20over_20coap_20client_20configuration_124',['GCoAP DNS over CoAP client configuration',['../group__gcoap__dns__config.html',1,'']]],
  ['dns_20over_20coap_20client_20implementation_125',['DNS over CoAP client implementation',['../group__net__gcoap__dns.html',1,'']]],
  ['dns_20over_20dtls_20compile_20time_20configuration_126',['DNS over DTLS compile-time configuration',['../group__net__sock__dodtls__conf.html',1,'']]],
  ['dns_20over_20dtls_20sock_20api_127',['DNS over DTLS sock API',['../group__net__sock__dodtls.html',1,'']]],
  ['dns_20sock_20api_128',['DNS sock API',['../group__net__sock__dns.html',1,'']]],
  ['donald_20e_20knuth_129',['Donald E. Knuth',['../group__sys__hashes__dek.html',1,'']]],
  ['dongle_130',['Dongle',['../group__boards__nrf51dongle.html',1,'nRF51 Dongle'],['../group__boards__nrf52840-mdk-dongle.html',1,'nRF52840 MDK USB Dongle'],['../group__boards__nrf52840dongle.html',1,'nRF52840-Dongle']]],
  ['dos_20line_20endings_20in_20stdio_20uart_131',['Support for DOS line endings in STDIO-UART',['../group__sys__stdio__uart__onlcr.html',1,'']]],
  ['dose_20driver_20compile_20configuration_132',['Differentially Operated Serial Ethernet (DOSE) driver compile configuration',['../group__drivers__dose__config.html',1,'']]],
  ['dragino_20lsn50_20lora_20sensor_20node_133',['Dragino LSN50 LoRa Sensor Node',['../group__boards__lsn50.html',1,'']]],
  ['dresden_20elektronik_134',['Dresden Elektronik',['../group__boards__deRFmega128.html',1,'deRFmega128 modules from Dresden Elektronik'],['../group__boards__deRFmega256.html',1,'deRFmega256 modules from Dresden Elektronik']]],
  ['driver_135',['Driver',['../group__pkg__adafruit__sensor.html',1,'Adafruit Unified Sensor Driver'],['../group__pkg__driver__cryptocell__310.html',1,'ARM CryptoCell 310 Driver'],['../group__drivers__motor.html',1,'DC Motor Driver'],['../group__drivers__diskio.html',1,'Disk IO Driver'],['../group__drivers__uart__half__duplex.html',1,'half-duplex UART Driver'],['../group__drivers__gpio__linux.html',1,'Linux User Mode GPIO Driver'],['../group__drivers__spidev__linux.html',1,'Linux User Mode SPI Driver'],['../group__drivers__lpsxxx.html',1,'LPS331AP/LPS25HB/LPS22HB Pressure Sensors Driver'],['../group__drivers__servo.html',1,'Servo Motor Driver'],['../group__stm32__eth.html',1,'STM32 Peripheral Ethernet Driver']]],
  ['driver_136',['driver',['../group__drivers__ad7746.html',1,'AD7746 Capacitance-to-digital converter driver'],['../group__drivers__adcxx1c.html',1,'ADCXX1C ADC device driver'],['../group__drivers__ads101x.html',1,'ADS101x/111x ADC device driver'],['../group__boards__common__silabs__drivers__aem.html',1,'Advanced energy monitor driver'],['../group__drivers__atwinc15x0.html',1,'ATWINC15x0 WiFi module driver'],['../group__drivers__cc110x.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc110x__config.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc2420.html',1,'CC2420 radio driver'],['../group__drivers__cst816s.html',1,'Cst816S touch screen driver'],['../group__drivers__ds18.html',1,'DS18 temperature sensor driver'],['../group__drivers__dynamixel.html',1,'Dynamixel driver'],['../group__drivers__periph__eeprom.html',1,'EEPROM driver'],['../group__drivers__ethos.html',1,'Ethernet-over-serial driver'],['../group__drivers__feetech.html',1,'Feetech driver'],['../group__drivers__periph__flashpage.html',1,'Flash page driver'],['../group__drivers__ft5x06.html',1,'FocalTech FT5x06 touch panel driver'],['../group__drivers__epd__bw__spi.html',1,'Generic black/white e-paper/e-ink SPI display driver.'],['../group__drivers__gp2y10xx.html',1,'GP2Y10xx Optical Dust Sensor device driver'],['../group__drivers__hd44780.html',1,'HD44780 LCD driver'],['../group__drivers__ili9341.html',1,'ILI9341 display driver'],['../group__drivers__jc42.html',1,'JC42 compliant temperature sensor driver'],['../group__drivers__kw2xrf.html',1,'KW2x radio-driver'],['../group__drivers__kw41zrf.html',1,'KW41Z radio-driver'],['../group__drivers__lcd.html',1,'LCD display driver'],['../group__drivers__sx1280.html',1,'LoRa radio driver'],['../group__drivers__max31855.html',1,'MAX31855 Thermocouple-to-Digital Converter driver'],['../group__sys__netdev__test.html',1,'netdev dummy test driver'],['../group__drivers__nrf5x__nrfble.html',1,'NRF BLE radio driver'],['../group__drivers__nrf5x__nrfmin.html',1,'NRF minimal radio driver'],['../group__drivers__nrf24l01p__ng.html',1,'NRF24L01+ (NG) 2.4 GHz trasceiver driver'],['../group__drivers__pcd8544.html',1,'PCD8544 LCD driver'],['../group__drivers__servo__timer.html',1,'periph_timer_periodic based servo driver'],['../group__drivers__ph__oem.html',1,'pH OEM sensor device driver'],['../group__boards__common__silabs__drivers__pic.html',1,'Power-and-interrupt driver'],['../group__drivers__servo__pwm.html',1,'PWM based servo driver'],['../group__drivers__rn2xx3.html',1,'RN2483/RN2903 LoRa module driver'],['../group__drivers__servo__saul.html',1,'SAUL integration of the servo driver'],['../group__drivers__sx127x.html',1,'Semtech SX1272 and SX1276 radios driver'],['../group__drivers__candev__linux.html',1,'SocketCAN driver'],['../group__drivers__sdcard__spi.html',1,'SPI SD Card driver'],['../group__drivers__st77xx.html',1,'ST77xx display driver'],['../group__sys__stdio__null.html',1,'STDIO null driver'],['../group__cpu__stm32__lcd__fmc.html',1,'STM32 FMC/FSMC LCD low-level parallel interface driver'],['../group__cpu__stm32__periph__fmc.html',1,'STM32 FMC/FSMC peripheral driver'],['../group__pkg__driver__sx126x.html',1,'SX1261/2 LoRa radio driver'],['../group__drivers__sx126x.html',1,'SX1261/2/8 and LLCC68 LoRa radio driver'],['../group__pkg__tinyusb__netdev.html',1,'TinyUSB netdev driver'],['../group__drivers__w5100.html',1,'W5100 ethernet driver'],['../group__drivers__shield__w5100.html',1,'W5100 Ethernet Shield driver'],['../group__drivers__w5500.html',1,'W5500 ethernet driver'],['../group__drivers__xbee.html',1,'XBee driver']]],
  ['driver_20api_137',['Driver API',['../group__drivers__netdev__api.html',1,'Netdev - Network Device Driver API'],['../group__drivers__periph__usbdev.html',1,'usbdev - USB Device Driver API']]],
  ['driver_20auto_20initialization_138',['Multimedia driver auto-initialization',['../group__sys__auto__init__multimedia.html',1,'']]],
  ['driver_20compile_20configuration_139',['driver compile configuration',['../group__drivers__seesaw__soil__config.html',1,'Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration'],['../group__drivers__ads101x__config.html',1,'ADS101 driver compile configuration'],['../group__drivers__at__config.html',1,'AT driver compile configuration'],['../group__drivers__at86rf215__config.html',1,'AT86RF215 driver compile configuration'],['../group__drivers__atca__config.html',1,'ATCA driver compile configuration'],['../group__drivers__bmx055__config.html',1,'BMX055 sensor driver compile configuration'],['../group__drivers__kw2xrf__config.html',1,'CR20A and KW2xD radio driver compile configuration'],['../group__drivers__dose__config.html',1,'Differentially Operated Serial Ethernet (DOSE) driver compile configuration'],['../group__drivers__ds1307__config.html',1,'DS1307 RTC driver compile configuration'],['../group__drivers__ethos__config.html',1,'Ethernet-over-serial driver driver compile configuration'],['../group__drivers__fxos8700__config.html',1,'FXOS8700 accelerometer/magnetometer driver compile configuration'],['../group__drivers__hdc1000__config.html',1,'HDC1000 Humidity and Temperature Sensor driver compile configuration'],['../group__drivers__isl29020__config.html',1,'ISL29020 light sensor driver compile configuration'],['../group__drivers__kw41zrf__config.html',1,'KW41Z, KW21Z in-cpu transceiver driver compile configuration'],['../group__drivers__l3g4200d__config.html',1,'L3G4200D gyroscope driver compile configuration'],['../group__drivers__lm75.html',1,'LM75 Temperature Sensor driver compile configuration'],['../group__drivers__lpsxxx__config.html',1,'LPS331AP/LPS25HB/LPS22HB/LPS22HH/LPS22CH driver compile configuration'],['../group__drivers__mag3110__config.html',1,'MAG3110 Magnetometer driver compile configuration'],['../group__drivers__mma8x5x__config.html',1,'MMA8x5x Accelerometer driver compile configuration'],['../group__drivers__motor__driver__config.html',1,'Motor_Driver driver compile configuration'],['../group__drivers__mpl3115a2__config.html',1,'MPL3115A2 Pressure Sensor driver compile configuration'],['../group__drivers__mrf24j40__config.html',1,'mrf24j40 driver compile configuration'],['../group__drivers__nrf52__802154__conf.html',1,'nrf802154 driver compile configuration'],['../group__drivers__opt3001__config.html',1,'OPT3001 Ambient Light Sensor driver compile configuration'],['../group__drivers__pir__config.html',1,'PIR Motion Sensor driver compile configuration'],['../group__drivers__pn532__config.html',1,'PN532 NFC Radio driver compile configuration'],['../group__drivers__rn2xx3__config.html',1,'RN2483/RN2903 Radio driver compile configuration'],['../group__drivers__mtd__sdcard__config.html',1,'SDCard driver compile configuration'],['../group__drivers__sx127x__config.html',1,'Semtech SX1272 and SX1276 driver compile configuration'],['../group__drivers__slipdev__config.html',1,'SLIP Network driver compile configuration'],['../group__drivers__softspi__config.html',1,'Software SPI driver compile configuration'],['../group__drivers__SPS30__config.html',1,'SPS30 PM Sensor driver compile configuration'],['../group__drivers__tcs37727__config.html',1,'TCS37727 RGB Light Sensor driver compile configuration'],['../group__drivers__tmp00x__config.html',1,'TMP006/TMP007 Infrared Thermopile Sensor driver compile configuration']]],
  ['driver_20compile_20configurations_140',['driver compile configurations',['../group__drivers__adcxx1c__config.html',1,'ADCXX1C driver compile configurations'],['../group__drivers__gp2y10xx__config.html',1,'GP2Y10xx driver compile configurations']]],
  ['driver_20driver_20compile_20configuration_141',['Ethernet-over-serial driver driver compile configuration',['../group__drivers__ethos__config.html',1,'']]],
  ['driver_20for_20decawave_20dw1000_20transceiver_142',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['driver_20for_20getting_20mac_20address_20out_20of_20atmel_20edbg_143',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['driver_20for_20nrf52840_20socs_144',['IEEE802.15.4 Driver for nRF52840 SoCs',['../group__drivers__nrf52__802154.html',1,'']]],
  ['driver_20implementation_20for_20the_20uwb_20core_20driver_20for_20decawave_20dw1000_20transceiver_145',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['driver_20initialization_146',['Secure Element Driver Initialization',['../group__se__init.html',1,'']]],
  ['driver_20interface_147',['Driver Interface',['../group__drivers__periph.html',1,'Peripheral Driver Interface'],['../group__drivers__soft__periph.html',1,'Soft Peripheral Driver Interface']]],
  ['driver_20interface_148',['driver interface',['../group__drivers__candev.html',1,'CAN device driver interface'],['../group__drivers__nrf24l01p.html',1,'NRF24L01+ driver interface']]],
  ['driver_20methods_20for_20congure_20tcp_20reno_149',['The send driver methods for CongURE TCP Reno',['../group__sys__congure__reno__methods.html',1,'']]],
  ['driver_20model_20for_20the_20decawave_20impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_150',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['driver_20package_151',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['driver_20package_20for_20i2c_20spi_20bme680_20sensor_152',['Driver package for I2C/SPI BME680 sensor',['../group__pkg__driver__bme680.html',1,'']]],
  ['driver_20registration_153',['Secure Element Driver Registration',['../group__se__registration.html',1,'']]],
  ['drivers_154',['Drivers',['../group__drivers__actuators.html',1,'Actuator Device Drivers'],['../group__drivers__can.html',1,'CAN Drivers'],['../group__drivers__display.html',1,'Display Device Drivers'],['../group__drivers.html',1,'Drivers'],['../group__pkg__lv__drivers.html',1,'LVGL Drivers'],['../group__drivers__misc.html',1,'Miscellaneous Drivers'],['../group__drivers__multimedia.html',1,'Multimedia Device Drivers'],['../group__drivers__netdev.html',1,'Network Device Drivers'],['../group__drivers__power.html',1,'Power Supply Drivers'],['../group__drivers__sensors.html',1,'Sensor Device Drivers'],['../group__boards__common__silabs__drivers.html',1,'Silicon Labs Common Drivers'],['../group__drivers__storage.html',1,'Storage Device Drivers']]],
  ['drivers_155',['drivers',['../group__drivers__netdev__ieee802154.html',1,'802.15.4 radio drivers'],['../group__drivers__at86rf215.html',1,'AT86RF215 based drivers'],['../group__drivers__at86rf2xx.html',1,'AT86RF2xx based drivers'],['../group__cpu__efm32__drivers.html',1,'EFM32 specific drivers'],['../group__drivers__netdev__eth.html',1,'Ethernet drivers'],['../group__drivers__netdev__lora.html',1,'LoRa drivers'],['../group__drivers__mrf24j40.html',1,'MRF24J40 based drivers'],['../group__drivers__shield.html',1,'Shields - hardware extension daughter board drivers'],['../group__drivers__netdev__wifi.html',1,'Wi-Fi drivers']]],
  ['drivers_20auto_20initialization_156',['drivers auto initialization',['../group__sys__auto__init__gnrc__netif.html',1,'GNRC netif drivers auto-initialization'],['../group__sys__auto__init__lwip__netif.html',1,'lwIP netif drivers auto-initialization'],['../group__sys__auto__init__saul.html',1,'SAUL drivers auto-initialization']]],
  ['ds1307_20rtc_157',['DS1307 RTC',['../group__drivers__ds1307.html',1,'']]],
  ['ds1307_20rtc_20driver_20compile_20configuration_158',['DS1307 RTC driver compile configuration',['../group__drivers__ds1307__config.html',1,'']]],
  ['ds18_20temperature_20sensor_20driver_159',['DS18 temperature sensor driver',['../group__drivers__ds18.html',1,'']]],
  ['ds3231_20real_20time_20clock_160',['DS3231 Real Time Clock',['../group__drivers__ds3231.html',1,'']]],
  ['ds3234_20extremely_20accurate_20spi_20rtc_161',['DS3234 Extremely Accurate SPI RTC',['../group__drivers__ds3234.html',1,'']]],
  ['ds75lx_20temperature_20sensor_162',['Maxim DS75LX temperature sensor',['../group__drivers__ds75lx.html',1,'']]],
  ['dsm_163',['DTLS Session Management (DSM)',['../group__net__dsm.html',1,'']]],
  ['dsme_164',['openDSME - IEEE 802.15.4 DSME',['../group__pkg__opendsme.html',1,'']]],
  ['dsme_20message_20interface_20implementation_165',['DSME Message interface implementation.',['../group__pkg__opendsme__dsmemessage.html',1,'']]],
  ['dsme_20platform_20interface_20implementation_166',['DSME Platform interface implementation.',['../group__pkg__opendsme__dsmeplatform.html',1,'']]],
  ['dsp0401_167',['DSP0401',['../group__drivers__dsp0401.html',1,'']]],
  ['dtls_168',['DTLS',['../group__net__dtls.html',1,'']]],
  ['dtls_20compile_20configuration_169',['SOCK DTLS compile configuration',['../group__net__sock__dtls__conf.html',1,'']]],
  ['dtls_20compile_20time_20configuration_170',['DNS over DTLS compile-time configuration',['../group__net__sock__dodtls__conf.html',1,'']]],
  ['dtls_20session_20management_20dsm_171',['DTLS Session Management (DSM)',['../group__net__dsm.html',1,'']]],
  ['dtls_20sock_20api_172',['DTLS sock API',['../group__net__sock__dodtls.html',1,'DNS over DTLS sock API'],['../group__net__sock__dtls.html',1,'DTLS sock API']]],
  ['dtls_20sock_20credentials_20api_173',['DTLS sock credentials API',['../group__net__sock__dtls__creds.html',1,'']]],
  ['due_174',['Arduino Due',['../group__boards__arduino-due.html',1,'']]],
  ['due_20common_175',['Arduino Due Common',['../group__boards__common__arduino__due.html',1,'']]],
  ['duemilanove_176',['Arduino Duemilanove',['../group__boards__arduino-duemilanove.html',1,'']]],
  ['dummy_20test_20driver_177',['netdev dummy test driver',['../group__sys__netdev__test.html',1,'']]],
  ['dump_178',['Object dump',['../group__sys__od.html',1,'']]],
  ['dump_20network_20packets_179',['Dump Network Packets',['../group__net__gnrc__pktdump.html',1,'']]],
  ['duplex_20uart_20driver_180',['half-duplex UART Driver',['../group__drivers__uart__half__duplex.html',1,'']]],
  ['dust_20sensor_181',['SDS011 Laser Dust Sensor',['../group__drivers__sds011.html',1,'']]],
  ['dust_20sensor_182',['SM_PWM_01C dust sensor',['../group__drivers__sm__pwm__01c.html',1,'']]],
  ['dust_20sensor_20device_20driver_183',['GP2Y10xx Optical Dust Sensor device driver',['../group__drivers__gp2y10xx.html',1,'']]],
  ['dw1000_20transceiver_184',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['dwm1001_185',['Decawave DWM1001',['../group__boards__dwm1001.html',1,'']]],
  ['dynamic_20host_20configuration_20protocol_20for_20ipv6_20dhcpv6_186',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['dynamixel_20driver_187',['Dynamixel driver',['../group__drivers__dynamixel.html',1,'']]]
];
