var searchData=
[
  ['h_20tt_0',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['h1611_1',['Olimex MSP430-H1611',['../group__boards__olimex__msp430__h1611.html',1,'']]],
  ['h2618_2',['Olimex MSP430-H2618',['../group__boards__olimex__msp430__h2618.html',1,'']]],
  ['hacl_20high_20assurance_20cryptographic_20library_3',['HACL* High Assurance Cryptographic Library',['../group__pkg__hacl.html',1,'']]],
  ['hal_4',['Nordic nrfx HAL',['../group__pkg__nrfx.html',1,'']]],
  ['half_20duplex_20uart_20driver_5',['half-duplex UART Driver',['../group__drivers__uart__half__duplex.html',1,'']]],
  ['half_20processor_6',['Half Processor',['../group__sys__bhp.html',1,'Bottom Half Processor'],['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['hamilton_7',['HamiltonIoT Hamilton',['../group__boards__hamilton.html',1,'']]],
  ['hamiltoniot_20hamilton_8',['HamiltonIoT Hamilton',['../group__boards__hamilton.html',1,'']]],
  ['handling_9',['IRQ Handling',['../group__core__irq.html',1,'']]],
  ['handling_10',['Common microbit LED handling',['../group__boards__common__microbit.html',1,'']]],
  ['hardware_20abstraction_20layer_11',['IEEE802.15.4 Radio Hardware Abstraction Layer',['../group__drivers__ieee802154__hal.html',1,'']]],
  ['hardware_20debugging_12',['STM32WL hardware debugging',['../group__cpu__stm32__wl__debug.html',1,'']]],
  ['hardware_20development_20kit_13',['NRF6310 (Nordic NRF Hardware Development Kit)',['../group__boards__nrf6310.html',1,'']]],
  ['hardware_20extension_20daughter_20board_20drivers_14',['Shields - hardware extension daughter board drivers',['../group__drivers__shield.html',1,'']]],
  ['hardware_20independent_20layer_20of_20the_20arduino_20cores_15',['Hardware independent layer of the Arduino cores',['../group__pkg__arduino__api.html',1,'']]],
  ['hash_20djb2_16',['Bernstein hash djb2',['../group__sys__hashes__djb2.html',1,'']]],
  ['hash_20functions_17',['hash functions',['../group__sys__hashes__keyed.html',1,'Keyed cryptographic hash functions'],['../group__sys__hashes__non__crypto.html',1,'Non-cryptographic hash functions'],['../group__sys__hashes__unkeyed.html',1,'Unkeyed cryptographic hash functions']]],
  ['hashes_18',['Hashes',['../group__sys__hashes.html',1,'Hashes'],['../group__sys__psa__crypto__hashes.html',1,'PSA Wrapper Functions: Hashes']]],
  ['hashing_20library_19',['BLAKE2 hashing library',['../group__pkg__libb2.html',1,'']]],
  ['hayes_20command_20set_20library_20',['AT (Hayes) command set library',['../group__drivers__at.html',1,'']]],
  ['hci_20for_20nimble_20host_21',['ESP32 Bluetooth LE HCI for NimBLE host',['../group__cpu__esp32__esp__ble__nimble.html',1,'']]],
  ['hd44780_20lcd_20driver_22',['HD44780 LCD driver',['../group__drivers__hd44780.html',1,'']]],
  ['hdc1000_20humidity_20and_20temperature_20sensor_23',['HDC1000 Humidity and Temperature Sensor',['../group__drivers__hdc1000.html',1,'']]],
  ['hdc1000_20humidity_20and_20temperature_20sensor_20driver_20compile_20configuration_24',['HDC1000 Humidity and Temperature Sensor driver compile configuration',['../group__drivers__hdc1000__config.html',1,'']]],
  ['header_25',['Point-to-Point Protocol Header',['../group__net__ppphdr.html',1,'']]],
  ['header_26',['header',['../group__net__ethernet__hdr.html',1,'Ethernet header'],['../group__net__gnrc__netif__hdr.html',1,'Generic network interface header'],['../group__net__ipv4__hdr.html',1,'IPv4 header'],['../group__net__ipv6__hdr.html',1,'IPv6 header'],['../group__net__lorawan__hdr.html',1,'LoRaWAN header'],['../group__nanocbor__config.html',1,'NanoCBOR configuration header']]],
  ['header_20compile_20configurations_27',['GNRC IPv6 extension header compile configurations',['../group__net__gnrc__ipv6__ext__conf.html',1,'']]],
  ['header_20compression_20iphc_28',['IPv6 header compression (IPHC)',['../group__net__gnrc__sixlowpan__iphc.html',1,'']]],
  ['header_20definitions_29',['IPv6 header definitions',['../group__net__gnrc__ipv6__hdr.html',1,'']]],
  ['header_20extension_30',['header extension',['../group__net__ipv6__ext__rh.html',1,'IPv6 routing header extension'],['../group__net__gnrc__rpl__srh.html',1,'RPL source routing header extension'],['../group__net__gnrc__ipv6__ext__rh.html',1,'Support for IPv6 routing header extension']]],
  ['header_20helpers_20and_20tools_31',['RIOT header helpers and tools',['../group__sys__riotboot__hdr.html',1,'']]],
  ['headers_32',['TI CC2538 CMSIS-style Headers',['../group__cpu__cc2538__regs.html',1,'']]],
  ['headers_33',['headers',['../group__net__ipv6__ext.html',1,'IPv6 extension headers'],['../group__net__gnrc__ipv6__ext.html',1,'IPv6 extension headers.'],['../group__net__gnrc__ipv6__ext__opt.html',1,'Support for IPv6 option extension headers']]],
  ['headers_20and_20definitions_34',['IEEE 802.15.4 frame headers and definitions',['../group__net__ieee802154__header.html',1,'']]],
  ['heap_20memory_20usage_20monitor_35',['Heap Memory Usage Monitor',['../group__sys__malloc__monitor.html',1,'']]],
  ['heap_20memory_20usage_20monitor_20internals_36',['Heap Memory Usage Monitor internals',['../group__sys__malloc__monitor__internals.html',1,'']]],
  ['helper_37',['Helper',['../group__pkg__nimble__addr.html',1,'Address Helper'],['../group__ble__bluetil__addr.html',1,'BLE Address Helper'],['../group__pkg__nimble__scanlist.html',1,'Scan Result Helper'],['../group__pkg__nimble__scanner.html',1,'Scanner Helper']]],
  ['helper_38',['helper',['../group__net__csma__sender.html',1,'CSMA/CA helper'],['../group__debug__irq__disable.html',1,'IRQ Disable Debug helper']]],
  ['helper_20compile_20configurations_39',['CSMA/CA helper compile configurations',['../group__net__csma__sender__conf.html',1,'']]],
  ['helper_20functions_40',['helper functions',['../group__net__utils.html',1,'Network helper functions'],['../group__sys__vfs__util.html',1,'VFS helper functions']]],
  ['helpers_41',['Test Utils Result Output Helpers',['../group__turo__helpers.html',1,'']]],
  ['helpers_42',['helpers',['../group__busy__wait.html',1,'Busy Waiting low-level helpers'],['../group__sys__rtc__utils.html',1,'RTC helpers'],['../group__usb__hid__descriptor.html',1,'USB HID descriptor helpers']]],
  ['helpers_20and_20tools_43',['RIOT header helpers and tools',['../group__sys__riotboot__hdr.html',1,'']]],
  ['helpers_20for_20ipv6_20over_20x_44',['Stack-independent helpers for IPv6 over X',['../group__net__l2util.html',1,'']]],
  ['helpers_20for_20pointer_20tagging_45',['Helpers for pointer tagging',['../group__sys__ptrtag.html',1,'']]],
  ['helpers_20for_20synchronizing_20with_20transmission_46',['Helpers for synchronizing with transmission.',['../group__net__gnrc__tx__sync.html',1,'']]],
  ['helpers_20for_20volatile_20accesses_47',['Helpers for volatile accesses',['../group__sys__atomic__utils__volatile.html',1,'']]],
  ['helpers_20to_20manipulate_20partitions_20slots_20on_20internal_20flash_48',['Helpers to manipulate partitions (slots) on internal flash',['../group__sys__riotboot__slot.html',1,'']]],
  ['heltec_20wifi_20lora_2032_20v2_20boards_49',['Heltec WiFi LoRa 32 V2 boards',['../group__boards__esp32__heltec-lora32-v2.html',1,'']]],
  ['hid_50',['USBUS HID',['../group__usbus__hid.html',1,'']]],
  ['hid_20descriptor_20helpers_51',['USB HID descriptor helpers',['../group__usb__hid__descriptor.html',1,'']]],
  ['hid_20io_52',['USBUS HID IO',['../group__usbus__hid__io.html',1,'']]],
  ['hid_20usage_20tables_53',['USB HID usage tables',['../group__usb__hid__usage.html',1,'']]],
  ['hid_20usb_20communications_20device_20class_54',['HID - USB communications device class',['../group__usb__hid.html',1,'']]],
  ['hifive1_20risc_20v_20board_55',['SiFive HiFive1 RISC-V board',['../group__boards__hifive1.html',1,'']]],
  ['hifive1b_20risc_20v_20board_56',['SiFive HiFive1b RISC-V board',['../group__boards__hifive1b.html',1,'']]],
  ['high_20assurance_20cryptographic_20library_57',['HACL* High Assurance Cryptographic Library',['../group__pkg__hacl.html',1,'']]],
  ['high_20level_20timer_20abstraction_20layer_58',['ztimer high level timer abstraction layer',['../group__sys__ztimer.html',1,'']]],
  ['high_20level_20timer_20abstraction_20layer_20deprecated_59',['xtimer high level timer abstraction layer (deprecated)',['../group__sys__xtimer.html',1,'']]],
  ['high_20security_20cryptographic_20library_60',['TweetNaCl high-security cryptographic library',['../group__pkg__tweetnacl.html',1,'']]],
  ['hih6130_20humidity_20and_20temperature_20sensor_61',['HIH6130 humidity and temperature sensor',['../group__drivers__hih6130.html',1,'']]],
  ['hint_62',['Fragment size hint',['../group__net__gnrc__sixlowpan__frag__hint.html',1,'']]],
  ['hip_20badge_63',['HiP Badge',['../group__boards__hip__badge.html',1,'']]],
  ['hm330x_20laser_20particulate_20matter_20sensor_64',['HM330X Laser Particulate Matter Sensor',['../group__drivers__hm330x.html',1,'']]],
  ['hmc5883l_203_20axis_20digital_20compass_65',['HMC5883L 3-axis digital compass',['../group__drivers__hmc5883l.html',1,'']]],
  ['hop_20by_20hop_20options_66',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['hop_20options_67',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['host_68',['ESP32 Bluetooth LE HCI for NimBLE host',['../group__cpu__esp32__esp__ble__nimble.html',1,'']]],
  ['host_20configuration_20protocol_20for_20ipv6_20dhcpv6_69',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['host_20controller_70',['sam0 SD Host Controller',['../group__cpu__sam0__common__sdhc.html',1,'']]],
  ['hs_20peripheral_71',['stm32 USB OTG FS/HS peripheral',['../group__cpu__stm32__usbdev.html',1,'']]],
  ['hsc_20temperature_20and_20pressure_20sensor_72',['HSC temperature and pressure sensor',['../group__drivers__hsc.html',1,'']]],
  ['hts221_20digital_20humidity_20sensor_73',['ST HTS221 digital Humidity Sensor',['../group__drivers__hts221.html',1,'']]],
  ['humidity_74',['Humidity',['../group__lwm2m__objects__humidity.html',1,'']]],
  ['humidity_20and_20temperature_20sensor_75',['Humidity and Temperature Sensor',['../group__drivers__hdc1000.html',1,'HDC1000 Humidity and Temperature Sensor'],['../group__drivers__sht1x.html',1,'SHT10/SHT11/SHT15 Humidity and Temperature Sensor']]],
  ['humidity_20and_20temperature_20sensor_76',['SHT2x Humidity and Temperature sensor',['../group__drivers__sht2x.html',1,'']]],
  ['humidity_20and_20temperature_20sensor_77',['HIH6130 humidity and temperature sensor',['../group__drivers__hih6130.html',1,'']]],
  ['humidity_20and_20temperature_20sensor_20driver_20compile_20configuration_78',['HDC1000 Humidity and Temperature Sensor driver compile configuration',['../group__drivers__hdc1000__config.html',1,'']]],
  ['humidity_20and_20temperature_20sensor_20series_79',['SHT3x Humidity and Temperature Sensor Series',['../group__drivers__sht3x.html',1,'']]],
  ['humidity_20and_20temperature_20sensors_80',['DHT Family of Humidity and Temperature Sensors',['../group__drivers__dht.html',1,'']]],
  ['humidity_20pressure_20gas_20sensor_81',['BME680 Temperature/Humidity/Pressure/Gas sensor',['../group__drivers__bme680.html',1,'']]],
  ['humidity_20sensor_82',['ST HTS221 digital Humidity Sensor',['../group__drivers__hts221.html',1,'']]],
  ['humidity_20sensor_83',['humidity sensor',['../group__drivers__bmx280.html',1,'BMP280/BME280 temperature, pressure and humidity sensor'],['../group__drivers__scd30.html',1,'SCD30 CO2, temperature and humidity sensor'],['../group__drivers__shtcx.html',1,'SHTCX Temperature and humidity sensor']]],
  ['humidity_20sensor_20object_20compile_20configurations_84',['LwM2M Humidity Sensor object compile configurations',['../group__lwm2m__objects__humidity__config.html',1,'']]],
  ['humidity_20sensors_85',['Si7006/13/20/21/5x temperature and humidity sensors',['../group__drivers__si70xx.html',1,'']]],
  ['hwrng_20abstraction_86',['HWRNG Abstraction',['../group__drivers__periph__hwrng.html',1,'']]]
];
