var searchData=
[
  ['b_0',['RE-Mote Revision B',['../group__boards__remote-revb.html',1,'']]],
  ['b_1',['OpenMote-b',['../group__boards__openmote-b.html',1,'']]],
  ['b_20l072z_20lrwan1_20lora_20discovery_2',['ST B-L072Z-LRWAN1 LoRa discovery',['../group__boards__b-l072z-lrwan1.html',1,'']]],
  ['b_20l475e_20iot01a_3',['ST B-L475E-IOT01A',['../group__boards__b-l475e-iot01a.html',1,'']]],
  ['b_20u585i_20iot02a_4',['STM32 B-U585I-IOT02A',['../group__boards__b-u585i-iot02a.html',1,'']]],
  ['backend_5',['backend',['../group__sys__suit__storage__ram.html',1,'ram storage backend'],['../group__sys__suit__storage__flashwrite.html',1,'riotboot flashwrite storage backend'],['../group__sys__suit__storage__vfs.html',1,'riotboot vfs storage backend'],['../group__sys__ztimer__mock.html',1,'ztimer mock clock backend'],['../group__sys__ztimer__periph__ptp.html',1,'ztimer periph/ptp backend'],['../group__sys__ztimer__periph__rtc.html',1,'ztimer periph/rtc backend'],['../group__sys__ztimer__periph__rtt.html',1,'ztimer periph/rtt backend'],['../group__sys__ztimer__periph__timer.html',1,'ztimer periph/timer backend']]],
  ['backtrace_20only_20under_20native_6',['Stack backtrace (only under native)',['../group__backtrace.html',1,'']]],
  ['backup_20battery_20monitoring_7',['backup battery monitoring',['../group__drivers__periph__vbat.html',1,'']]],
  ['badge_8',['HiP Badge',['../group__boards__hip__badge.html',1,'']]],
  ['bar_9',['A terminal progress bar',['../group__sys__progress__bar.html',1,'']]],
  ['barometer_10',['Barometer',['../group__lwm2m__objects__barometer.html',1,'']]],
  ['barometer_20object_20compile_20configurations_11',['LwM2M Barometer object compile configurations',['../group__lwm2m__objects__barometer__config.html',1,'']]],
  ['base_20board_12',['QN9080DK base board',['../group__boards__qn9080dk.html',1,'']]],
  ['base_20fib_13',['Forwarding Information Base (FIB)',['../group__net__fib.html',1,'']]],
  ['base_20for_20ipv6_14',['Neighbor Information Base for IPv6',['../group__net__gnrc__ipv6__nib.html',1,'']]],
  ['base_20object_15',['IPSO Sensor base object',['../group__lwm2m__objects__ipso__sensor__base.html',1,'']]],
  ['base_20object_20compile_20configurations_16',['LwM2M IPSO Sensor base object compile configurations',['../group__lwm2m__objects__ipso__sensor__base__config.html',1,'']]],
  ['base64_20encoder_20decoder_17',['base64 encoder decoder',['../group__sys__base64.html',1,'']]],
  ['based_20bluepill_18',['STM32F030C8 based Bluepill',['../group__boards__bluepill-stm32f030c8.html',1,'']]],
  ['based_20boards_19',['ESP-12x based boards',['../group__boards__esp8266__esp-12x.html',1,'']]],
  ['based_20drivers_20',['based drivers',['../group__drivers__at86rf215.html',1,'AT86RF215 based drivers'],['../group__drivers__at86rf2xx.html',1,'AT86RF2xx based drivers'],['../group__drivers__mrf24j40.html',1,'MRF24J40 based drivers']]],
  ['based_20implementation_20of_20bottom_20half_20processor_21',['based implementation of Bottom Half Processor',['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['based_20led_20strip_22',['LPD8808 based LED Strip',['../group__drivers__lpd8808.html',1,'']]],
  ['based_20malloc_23',['TLSF-based malloc.',['../group__pkg__tlsf__malloc.html',1,'']]],
  ['based_20servo_20driver_24',['based servo driver',['../group__drivers__servo__timer.html',1,'periph_timer_periodic based servo driver'],['../group__drivers__servo__pwm.html',1,'PWM based servo driver']]],
  ['based_20zep_25',['Socket-based ZEP',['../group__drivers__socket__zep.html',1,'']]],
  ['basic_20client_20for_20gnrc_206lowpan_20brs_26',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['basic_20dhcpv6_20client_20implementation_20in_20gnrc_27',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['basic_20telnet_20server_20implementation_28',['basic Telnet server implementation',['../group__net__telnet.html',1,'']]],
  ['basics_29',['LoRa Basics',['../group__pkg__lorabasicsmodem.html',1,'']]],
  ['bastwan_20board_30',['BastWAN board',['../group__boards__bastwan.html',1,'']]],
  ['battery_20monitoring_31',['backup battery monitoring',['../group__drivers__periph__vbat.html',1,'']]],
  ['bbc_20micro_3abit_32',['BBC micro:bit',['../group__boards__microbit.html',1,'']]],
  ['bbc_20micro_3abit_20v2_33',['BBC micro:bit v2',['../group__boards__microbit__v2.html',1,'']]],
  ['beacon_34',['Airfy Beacon',['../group__boards__airfy-beacon.html',1,'']]],
  ['beam_35',['TTGO T-Beam',['../group__boards__esp32__ttgo-t-beam.html',1,'']]],
  ['benchmark_36',['Benchmark',['../group__sys__benchmark.html',1,'']]],
  ['benchmark_37',['UDP benchmark',['../group__test__utils__benchmark__udp.html',1,'']]],
  ['ber_20l_20ayer_38',['[S]ensor [A]ctuator [U]ber [L]ayer',['../group__drivers__saul.html',1,'']]],
  ['bernstein_20hash_20djb2_39',['Bernstein hash djb2',['../group__sys__hashes__djb2.html',1,'']]],
  ['bh1750fvi_20light_20sensor_40',['BH1750FVI Light Sensor',['../group__drivers__bh1750fvi.html',1,'']]],
  ['bh1900nux_20temperature_20sensor_41',['BH1900NUX Temperature sensor',['../group__drivers__bh1900nux.html',1,'']]],
  ['binary_20coded_20decimal_42',['Binary coded decimal',['../group__sys__bcd.html',1,'']]],
  ['bit_20manipulation_20engine_20bme_43',['Kinetis Bit Manipulation Engine (BME)',['../group__cpu__kinetis__bme.html',1,'']]],
  ['bit_20xtimer_20wrapper_44',['ztimer64_xtimer_compat: 64 Bit xtimer wrapper',['../group__sys__ztimer64__xtimer__compat.html',1,'']]],
  ['bitfields_45',['Bitfields',['../group__sys__bitfield.html',1,'']]],
  ['black_20white_20e_20paper_20e_20ink_20spi_20display_20driver_46',['Generic black/white e-paper/e-ink SPI display driver.',['../group__drivers__epd__bw__spi.html',1,'']]],
  ['blacklist_47',['IPv6 address blacklist',['../group__net__gnrc__ipv6__blacklist.html',1,'']]],
  ['blacklisting_20compile_20configurations_48',['GNRC IPv6 address blacklisting compile configurations',['../group__net__gnrc__ipv6__blacklist__conf.html',1,'']]],
  ['blackpill_20and_20bluepill_20common_20code_49',['Blackpill and Bluepill common code',['../group__boards__common__blxxxpill.html',1,'']]],
  ['blackpill_20stm32f103c8_20board_50',['Blackpill STM32F103C8 board',['../group__boards__blackpill__stm32f103c8.html',1,'']]],
  ['blackpill_20stm32f103cb_20board_20128kib_20flash_51',['Blackpill STM32F103CB board (128KiB flash)',['../group__boards__blackpill__stm32f103cb.html',1,'']]],
  ['blake2_20hashing_20library_52',['BLAKE2 hashing library',['../group__pkg__libb2.html',1,'']]],
  ['ble_53',['BLE',['../group__boards__arduino-nano-33-ble.html',1,'Arduino Nano 33 BLE'],['../group__ble.html',1,'Bluetooth Low Energy (BLE)']]],
  ['ble_20address_20helper_54',['BLE Address Helper',['../group__ble__bluetil__addr.html',1,'']]],
  ['ble_20advertising_20data_20ad_20processing_55',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['ble_20defines_56',['Generic BLE defines',['../group__ble__defs.html',1,'']]],
  ['ble_20for_20nimble_57',['RPL-over-BLE for NimBLE',['../group__pkg__nimble__rpble.html',1,'']]],
  ['ble_20mode_58',['netdev BLE mode',['../group__drivers__netdev__ble.html',1,'']]],
  ['ble_20radio_20driver_59',['NRF BLE radio driver',['../group__drivers__nrf5x__nrfble.html',1,'']]],
  ['ble_20sense_60',['Arduino Nano 33 BLE sense',['../group__boards__arduino-nano-33-ble-sense.html',1,'']]],
  ['blob_20file_20module_61',['Blob file module',['../group__utils__blob.html',1,'']]],
  ['bloom_20filter_62',['Bloom filter',['../group__sys__bloom.html',1,'']]],
  ['bluepill_63',['STM32F030C8 based Bluepill',['../group__boards__bluepill-stm32f030c8.html',1,'']]],
  ['bluepill_20common_20code_64',['Blackpill and Bluepill common code',['../group__boards__common__blxxxpill.html',1,'']]],
  ['bluepill_20stm32f103c8_20board_65',['Bluepill STM32F103C8 board',['../group__boards__bluepill__stm32f103c8.html',1,'']]],
  ['bluepill_20stm32f103cb_20board_20128kib_20flash_66',['Bluepill STM32F103CB board (128KiB flash)',['../group__boards__bluepill__stm32f103cb.html',1,'']]],
  ['bluetil_67',['Bluetil',['../group__ble__bluetil.html',1,'']]],
  ['bluetooth_20le_20hci_20for_20nimble_20host_68',['ESP32 Bluetooth LE HCI for NimBLE host',['../group__cpu__esp32__esp__ble__nimble.html',1,'']]],
  ['bluetooth_20library_20for_20the_20esp32_20c3_20soc_69',['ESP32 SDK Bluetooth library for the ESP32-C3 SoC',['../group__pkg__esp32__sdk__lib__bt__esp32c3.html',1,'']]],
  ['bluetooth_20library_20for_20the_20esp32_20soc_70',['ESP32 SDK Bluetooth library for the ESP32 SoC',['../group__pkg__esp32__sdk__lib__bt__esp32.html',1,'']]],
  ['bluetooth_20low_20energy_20ble_71',['Bluetooth Low Energy (BLE)',['../group__ble.html',1,'']]],
  ['bme_72',['Kinetis Bit Manipulation Engine (BME)',['../group__cpu__kinetis__bme.html',1,'']]],
  ['bme280_20temperature_20pressure_20and_20humidity_20sensor_73',['BMP280/BME280 temperature, pressure and humidity sensor',['../group__drivers__bmx280.html',1,'']]],
  ['bme680_20sensor_74',['Driver package for I2C/SPI BME680 sensor',['../group__pkg__driver__bme680.html',1,'']]],
  ['bme680_20temperature_20humidity_20pressure_20gas_20sensor_75',['BME680 Temperature/Humidity/Pressure/Gas sensor',['../group__drivers__bme680.html',1,'']]],
  ['bmp180_20temperature_20and_20pressure_20sensor_76',['BMP180 temperature and pressure sensor',['../group__drivers__bmp180.html',1,'']]],
  ['bmp280_20bme280_20temperature_20pressure_20and_20humidity_20sensor_77',['BMP280/BME280 temperature, pressure and humidity sensor',['../group__drivers__bmx280.html',1,'']]],
  ['bmx055_209_20axis_20sensor_78',['BMX055 9-axis sensor',['../group__drivers__bmx055.html',1,'']]],
  ['bmx055_20sensor_20driver_20compile_20configuration_79',['BMX055 sensor driver compile configuration',['../group__drivers__bmx055__config.html',1,'']]],
  ['board_80',['Board',['../group__boards__e104-bt5010a-tb.html',1,'E104-BT5010A Test Board'],['../group__boards__e104-bt5011a-tb.html',1,'E104-BT5011A Test Board'],['../group__boards__e180-zg120b-tb.html',1,'Ebyte E180-ZG120B-TB Test Board'],['../group__boards__esp32s3__pros3.html',1,'ESP32 ProS3 Board'],['../group__boards__esp32c3__devkit.html',1,'ESP32-C3-DevKit Board'],['../group__boards__esp32__esp-ethernet-kit-v1__0.html',1,'ESP32-Ethernet-Kit V1.0 Board'],['../group__boards__esp32__esp-ethernet-kit-v1__1.html',1,'ESP32-Ethernet-Kit V1.1 Board'],['../group__boards__esp32__esp-ethernet-kit-v1__2.html',1,'ESP32-Ethernet-Kit V1.2 Board'],['../group__boards__esp32s2__devkit.html',1,'ESP32-S2-DevKit Board'],['../group__boards__esp32s3__devkit.html',1,'ESP32-S3-DevKit Board'],['../group__boards__esp32s3__usb__otg.html',1,'ESP32-S3-USB-OTG Board'],['../group__boards__firefly.html',1,'Firefly Board'],['../group__boards__frdm-kw41z.html',1,'Freescale FRDM-KW41Z Board'],['../group__boards__generic__cc2538__cc2592__dk.html',1,'Generic CC2538-CC2592-DK Board'],['../group__boards__esp32s2__lilygo__ttgo__t8.html',1,'LILYGO TTGO T8 ESP32-S2 Board'],['../group__boards__mcb2388.html',1,'MCB2388 Evaluation Board'],['../group__boards__native.html',1,'Native Board'],['../group__boards__native64.html',1,'Native64 Board'],['../group__boards__frdm-k22f.html',1,'NXP FRDM-K22F Board'],['../group__boards__frdm-k64f.html',1,'NXP FRDM-K64F Board'],['../group__boards__frdm-kl43z.html',1,'NXP FRDM-KL43Z Board'],['../group__boards__usb-kw41z.html',1,'NXP USB-KW41Z Board'],['../group__boards__pba-d-01-kw2x.html',1,'phyWAVE-KW22 Board'],['../group__boards__stm32f030f4-demo.html',1,'STM32F030F4 Demo Board'],['../group__boards__esp32s2-wemos-mini.html',1,'Wemos S2 mini Board']]],
  ['board_81',['board',['../group__boards__yarm.html',1,'Acmesystems YARM board'],['../group__drivers__io1__xplained.html',1,'Atmel IO1 Xplained Extension board'],['../group__boards__atxmega-a1-xplained.html',1,'ATxmega-A1 Xplained board'],['../group__boards__atxmega-a1u-xpro.html',1,'ATxmega-A1U Xplained Pro board'],['../group__boards__atxmega-a3bu-xplained.html',1,'ATxmega-A3BU Xplained board'],['../group__boards__bastwan.html',1,'BastWAN board'],['../group__boards__blackpill__stm32f103c8.html',1,'Blackpill STM32F103C8 board'],['../group__boards__bluepill__stm32f103c8.html',1,'Bluepill STM32F103C8 board'],['../group__boards__openlabs-kw41z-mini.html',1,'openlabs.co kw41z-mini board'],['../group__boards__openlabs-kw41z-mini-256kib.html',1,'openlabs.co kw41z-mini-256kib board'],['../group__boards__reel.html',1,'Phytec reel board'],['../group__boards__qn9080dk.html',1,'QN9080DK base board'],['../group__boards__seeedstudio-gd32.html',1,'SeeedStudio GD32 RISC-V board'],['../group__boards__hifive1.html',1,'SiFive HiFive1 RISC-V board'],['../group__boards__hifive1b.html',1,'SiFive HiFive1b RISC-V board'],['../group__boards__i-nucleo-lrwan1.html',1,'ST I-NUCLEO-LRWAN1 LoRa board'],['../group__boards__stm32f723e-disco.html',1,'STM32F723E-DISCO board'],['../group__boards__stm32f769i-disco.html',1,'STM32F769I-DISCO board'],['../group__boards__stm32mp157c-dk2.html',1,'STM32MP157C-DK2 board'],['../group__boards__weact-f401cc.html',1,'WeAct-F401CC board'],['../group__boards__weact-f401ce.html',1,'WeAct-F401CE board'],['../group__boards__weact-f411ce.html',1,'WeAct-F411CE board'],['../group__boards__weact-g030f6.html',1,'WeAct-G030F6 board']]],
  ['board_20128kib_20flash_82',['board 128KiB flash',['../group__boards__blackpill__stm32f103cb.html',1,'Blackpill STM32F103CB board (128KiB flash)'],['../group__boards__bluepill__stm32f103cb.html',1,'Bluepill STM32F103CB board (128KiB flash)']]],
  ['board_20communication_20controller_83',['Board communication controller',['../group__boards__common__silabs__drivers__bc.html',1,'']]],
  ['board_20drivers_84',['Shields - hardware extension daughter board drivers',['../group__drivers__shield.html',1,'']]],
  ['board_20groups_85',['Common Board Groups',['../group__boards__common.html',1,'']]],
  ['board_20leds_86',['Control on-board LEDs',['../group__drivers__led.html',1,'']]],
  ['board_20reset_20via_20usb_20cdc_20acm_87',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['board_20reset_20via_20usb_20cdc_20acm_20internals_88',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['board_20stm32wle5jc_89',['LoRa-E5 Development Board - STM32WLE5JC',['../group__boards__lora-e5-dev.html',1,'']]],
  ['board_5fsoftware_5freset_90',['board_software_reset',['../group__pseudomodule__board__software__reset.html',1,'']]],
  ['boards_91',['Boards',['../group__boards.html',1,'Boards'],['../group__boards__esp32.html',1,'ESP32 Boards'],['../group__boards__esp32c3.html',1,'ESP32-C3 Boards'],['../group__boards__esp32s2.html',1,'ESP32-S2 Boards'],['../group__boards__esp32s3.html',1,'ESP32-S3 Boards'],['../group__boards__esp8266.html',1,'ESP8266 Boards']]],
  ['boards_92',['boards',['../group__boards__common__msp430.html',1,'Common Configuration Snippets for MSP430 boards'],['../group__boards__esp8266__esp-12x.html',1,'ESP-12x based boards'],['../group__boards__esp32__wroom-32.html',1,'Generic ESP32-WROOM-32 boards'],['../group__boards__esp32__heltec-lora32-v2.html',1,'Heltec WiFi LoRa 32 V2 boards']]],
  ['boards_20common_93',['SODAQ boards common',['../group__boards__common__sodaq.html',1,'']]],
  ['bootloader_94',['riotboot serial bootloader',['../group__bootloader__riotboot__serial.html',1,'']]],
  ['bootloader_20protocol_95',['Serial Bootloader Protocol',['../group__sys__riotboot__serial.html',1,'']]],
  ['bootloaders_96',['Bootloaders',['../group__bootloaders.html',1,'']]],
  ['border_20router_20list_97',['Authoritative border router list',['../group__net__gnrc__ipv6__nib__abr.html',1,'']]],
  ['boron_98',['Particle Boron',['../group__boards__particle-boron.html',1,'']]],
  ['bottom_20half_20processor_99',['Bottom Half Processor',['../group__sys__bhp.html',1,'Bottom Half Processor'],['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['box_100',['ESP32-S3-Box',['../group__boards__esp32s3__box.html',1,'']]],
  ['bq2429x_101',['BQ2429x',['../group__drivers__bq2429x.html',1,'']]],
  ['broadcast_20deduplication_102',['Link-layer Broadcast deduplication',['../group__net__gnrc__netif__dedup.html',1,'']]],
  ['brs_103',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['bt5010a_20test_20board_104',['E104-BT5010A Test Board',['../group__boards__e104-bt5010a-tb.html',1,'']]],
  ['bt5011a_20test_20board_105',['E104-BT5011A Test Board',['../group__boards__e104-bt5011a-tb.html',1,'']]],
  ['bt50xxa_20tb_20common_20code_106',['E104-BT50xxA-TB common code',['../group__boards__common__e104-bt50xxa-tb.html',1,'']]],
  ['buffer_107',['buffer',['../group__net__gnrc__sixlowpan__frag__fb.html',1,'6LoWPAN fragmentation buffer'],['../group__net__gnrc__sixlowpan__frag__rb.html',1,'6LoWPAN reassembly buffer'],['../group__net__gnrc__pktbuf.html',1,'Packet buffer'],['../group__net__gnrc__sixlowpan__frag__vrb.html',1,'Virtual reassembly buffer']]],
  ['buffers_20library_108',['small Protocol Buffers library',['../group__pkg__nanopb.html',1,'']]],
  ['buses_20for_20common_20events_109',['System Buses for common events',['../group__sys__bus.html',1,'']]],
  ['busy_20waiting_20low_20level_20helpers_110',['Busy Waiting low-level helpers',['../group__busy__wait.html',1,'']]],
  ['by_20hop_20options_111',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['by_20most_20libcs_112',['endian conversions as provided by most libcs',['../group__sys__endian.html',1,'']]]
];
