var searchData=
[
  ['m_20common_0',['ARM Cortex-M common',['../group__cpu__cortexm__common.html',1,'']]],
  ['m0_1',['Adafruit Feather M0',['../group__boards__feather-m0.html',1,'']]],
  ['m0_20lora_2',['Adafruit Feather M0 LoRa',['../group__boards__feather-m0-lora.html',1,'']]],
  ['m0_20wifi_3',['Adafruit Feather M0 WiFi',['../group__boards__feather-m0-wifi.html',1,'']]],
  ['m3_20open_20node_4',['M3 open node',['../group__boards__iotlab-a8-m3.html',1,'IoT-LAB A8 M3 open node'],['../group__boards__iotlab-m3.html',1,'IoT-LAB M3 open node']]],
  ['m4_5',['Adafruit-Itsybitsy-M4',['../group__boards__adafruit-itsybitsy-m4.html',1,'']]],
  ['m4_20express_6',['Adafruit Grand Central M4 Express',['../group__boards__adafruit-grand-central-m4-express.html',1,'']]],
  ['mac_7',['PSA Wrapper Functions: MAC',['../group__sys__psa__crypto__mac.html',1,'']]],
  ['mac_20address_20out_20of_20atmel_20edbg_8',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['mac_20compile_20configurations_9',['GNRC MAC compile configurations',['../group__net__gnrc__mac__conf.html',1,'']]],
  ['mac_20module_10',['Common MAC module',['../group__net__gnrc__mac.html',1,'']]],
  ['machine_11',['LwM2M - Lightweight Machine to Machine',['../group__pkg__wakaama.html',1,'']]],
  ['machine_20to_20machine_12',['LwM2M - Lightweight Machine to Machine',['../group__pkg__wakaama.html',1,'']]],
  ['macros_13',['Common Macros',['../group__core__macros.html',1,'']]],
  ['macros_20and_20types_20for_14',['Utility functions, macros, and types for',['../group__sys__flash__utils.html',1,'']]],
  ['mag3110_203_20axis_20digital_20magnetometer_15',['MAG3110 3-Axis Digital Magnetometer',['../group__drivers__mag3110.html',1,'']]],
  ['mag3110_20magnetometer_20driver_20compile_20configuration_16',['MAG3110 Magnetometer driver compile configuration',['../group__drivers__mag3110__config.html',1,'']]],
  ['magic_20values_20for_20riotboot_17',['Magic values for riotboot',['../group__sys__riotboot__magic.html',1,'']]],
  ['magnetic_20sensor_18',['QMC5883L 3-Axis Digital Magnetic Sensor',['../group__drivers__qmc5883l.html',1,'']]],
  ['magnetometer_19',['MAG3110 3-Axis Digital Magnetometer',['../group__drivers__mag3110.html',1,'']]],
  ['magnetometer_20',['magnetometer',['../group__drivers__fxos8700.html',1,'FXOS8700 3-axis accelerometer/magnetometer'],['../group__drivers__lis3mdl.html',1,'LIS3MDL 3-axis magnetometer'],['../group__drivers__lsm303agr.html',1,'LSM303AGR 3D accelerometer/magnetometer'],['../group__drivers__lsm303dlhc.html',1,'LSM303DLHC 3D accelerometer/magnetometer']]],
  ['magnetometer_20driver_20compile_20configuration_21',['MAG3110 Magnetometer driver compile configuration',['../group__drivers__mag3110__config.html',1,'']]],
  ['magnetometer_20driver_20compile_20configuration_22',['FXOS8700 accelerometer/magnetometer driver compile configuration',['../group__drivers__fxos8700__config.html',1,'']]],
  ['magnetometer_20gyroscope_23',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['mailbox_20ipc_20extension_24',['Mailbox IPC extension',['../group__net__gnrc__netapi__mbox.html',1,'']]],
  ['mailboxes_25',['Mailboxes',['../group__core__mbox.html',1,'']]],
  ['malloc_26',['malloc',['../group__oneway__malloc.html',1,'Oneway malloc'],['../group__pkg__tlsf__malloc.html',1,'TLSF-based malloc.']]],
  ['malloc_20and_20friends_27',['Thread-safe wrappers for malloc and friends',['../group__sys__malloc__ts.html',1,'']]],
  ['malloc_5ftracing_28',['malloc_tracing',['../group__pseudomodule__malloc__tracing.html',1,'']]],
  ['management_29',['Management',['../group__drivers__periph__pm.html',1,'Power Management'],['../group__sys__psa__crypto__slot__mgmt.html',1,'PSA Crypto Key Slot Management'],['../group__psa__crypto__se__mgmt.html',1,'PSA Crypto SE Management'],['../group__se__key__management.html',1,'Secure Element Key Management']]],
  ['management_30',['Memory management',['../group__sys__memory__management.html',1,'']]],
  ['management_20dsm_31',['DTLS Session Management (DSM)',['../group__net__dsm.html',1,'']]],
  ['management_20for_20netif_32',['Connection State Management for netif',['../group__pkg__nimble__netif__conn.html',1,'']]],
  ['manager_33',['(D)TLS Credential Manager',['../group__net__credman.html',1,'']]],
  ['manager_34',['USBUS device and endpoint manager',['../group__usb__usbus.html',1,'']]],
  ['manager_20compile_20configurations_35',['(D)TLS Credential Manager compile configurations',['../group__net__credman__conf.html',1,'']]],
  ['manipulate_20partitions_20slots_20on_20internal_20flash_36',['Helpers to manipulate partitions (slots) on internal flash',['../group__sys__riotboot__slot.html',1,'']]],
  ['manipulation_20engine_20bme_37',['Kinetis Bit Manipulation Engine (BME)',['../group__cpu__kinetis__bme.html',1,'']]],
  ['map_38',['map',['../group__cpu__specific__peripheral__memory__map.html',1,'TI CC26x0/CC13x0 peripheral memory map'],['../group__cpu__cc26x2__cc13x2__peripheral__memory__map.html',1,'TI CC26x2, CC13x2 peripheral memory map']]],
  ['maple_20mini_39',['maple-mini',['../group__boards__maple-mini.html',1,'']]],
  ['mapper_40',['MTD address mapper',['../group__drivers__mtd__mapper.html',1,'']]],
  ['mass_20storage_20class_20functions_41',['USBUS Mass Storage Class functions',['../group__usbus__msc.html',1,'']]],
  ['math_20functions_42',['imath: Integer Math functions',['../group__sys__imath.html',1,'']]],
  ['math_20libraries_20and_20utilities_43',['Math libraries and utilities',['../group__sys__math.html',1,'']]],
  ['mathematical_20statistics_20library_44',['Matstat - Integer mathematical statistics library',['../group__sys__matstat.html',1,'']]],
  ['maths_20library_45',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['matrix_20keypad_46',['Matrix Keypad',['../group__drivers__matrix__keypad.html',1,'']]],
  ['matrix_20multiplication_20library_47',['GEMM (General Matrix Multiplication) library',['../group__pkg__gemmlowp.html',1,'']]],
  ['matrix_20multiplication_20library_48',['The ruy matrix multiplication library',['../group__pkg__ruy.html',1,'']]],
  ['matstat_20integer_20mathematical_20statistics_20library_49',['Matstat - Integer mathematical statistics library',['../group__sys__matstat.html',1,'']]],
  ['matter_20sensor_50',['Matter Sensor',['../group__drivers__hm330x.html',1,'HM330X Laser Particulate Matter Sensor'],['../group__drivers__sps30.html',1,'SPS30 Particulate Matter Sensor']]],
  ['max31855_20thermocouple_20to_20digital_20converter_20driver_51',['MAX31855 Thermocouple-to-Digital Converter driver',['../group__drivers__max31855.html',1,'']]],
  ['maxim_20ds75lx_20temperature_20sensor_52',['Maxim DS75LX temperature sensor',['../group__drivers__ds75lx.html',1,'']]],
  ['mbed_20lpc1768_20development_20kit_53',['mbed LPC1768 development kit',['../group__boards__mbed__lpc1768.html',1,'']]],
  ['mbed_20tls_54',['Mbed TLS',['../group__pkg__mbedtls.html',1,'ARM Mbed TLS'],['../group__pkg__mbedtls__entropy__sources.html',1,'Entropy source API to Mbed TLS']]],
  ['mbed_20tls_20entropy_20module_55',['Access API to Mbed TLS entropy module',['../group__pkg__mbedtls__entropy.html',1,'']]],
  ['mbed_20tls_20package_20compile_20configurations_56',['Mbed TLS package compile configurations',['../group__pkg__mbedtls__config.html',1,'']]],
  ['mcb2388_20evaluation_20board_57',['MCB2388 Evaluation Board',['../group__boards__mcb2388.html',1,'']]],
  ['mcg_58',['Kinetis MCG',['../group__cpu__kinetis__mcg.html',1,'']]],
  ['mcp2515_59',['MCP2515',['../group__drivers__mcp2515.html',1,'']]],
  ['mcp47xx_20dac_20with_20i2c_20interface_60',['MCP47xx DAC with I2C interface',['../group__drivers__mcp47xx.html',1,'']]],
  ['mcu_61',['MCU',['../group__cpu__atxmega.html',1,'Atmel ATxmega MCU'],['../group__cpu__nrf51.html',1,'Nordic nRF51 MCU'],['../group__cpu__nrf52.html',1,'Nordic nRF52 MCU'],['../group__cpu__nrf53.html',1,'Nordic nRF53 MCU'],['../group__cpu__nrf5x__common.html',1,'Nordic nRF5x MCU'],['../group__cpu__nrf9160.html',1,'Nordic nRF9160 MCU']]],
  ['mcu_20family_62',['MCU family',['../group__cpu__msp430__f2xx__g2xx.html',1,'MSP430 F2xx/G2xx MCU family'],['../group__cpu__msp430__x1xx.html',1,'MSP430 x1xx MCU family']]],
  ['mcu_20peripherals_63',['Atmel ATxmega MCU Peripherals',['../group__cpu__atxmega__periph.html',1,'']]],
  ['mcu_20software_20interface_20standard_64',['Nuclei MCU Software Interface Standard',['../group__pkg__nmsis__sdk.html',1,'']]],
  ['mcu_20support_65',['MCU support',['../group__pkg__esp32__sdk.html',1,'ESP32 SDK for the ESP32 MCU support'],['../group__pkg__esp8266__sdk.html',1,'ESP8266 RTOS SDK for the ESP8266 MCU support']]],
  ['mcu_20with_20samd21_66',['SenseBox MCU with SAMD21',['../group__boards__sensebox__samd21.html',1,'']]],
  ['mcufont_67',['MCUFont',['../group__pkg__mcufont.html',1,'']]],
  ['mcus_68',['MCUs',['../group__cpu__rpx0xx.html',1,'RPx0xx MCUs'],['../group__pkg__gecko__sdk.html',1,'Vendor library for EFM/EFR/EZR32 MCUs']]],
  ['md5_69',['MD5',['../group__sys__hashes__md5.html',1,'']]],
  ['mdk_70',['MDK',['../group__boards__nrf52832-mdk.html',1,'nRF52832-MDK'],['../group__boards__nrf52840-mdk.html',1,'nRF52840-MDK']]],
  ['mdk_20usb_20dongle_71',['nRF52840 MDK USB Dongle',['../group__boards__nrf52840-mdk-dongle.html',1,'']]],
  ['media_20independent_20interface_20mii_72',['Ethernet Media-Independent Interface (MII)',['../group__drivers__mii.html',1,'']]],
  ['meets_20eddy_73',['Skald meets Eddy',['../group__ble__skald__eddystone.html',1,'']]],
  ['mega_202560_74',['Arduino Mega 2560',['../group__boards__arduino-mega2560.html',1,'']]],
  ['mega1284p_20xplained_75',['Mega1284P-Xplained',['../group__boards__mega-xplained.html',1,'']]],
  ['memory_76',['Low-Power RTC Memory',['../group__drivers__periph__rtc__mem.html',1,'']]],
  ['memory_20access_20methods_77',['unaligned memory access methods',['../group__sys__unaligned.html',1,'']]],
  ['memory_20allocator_78',['Two-Level Segregated Fit memory allocator',['../group__pkg__tlsf.html',1,'']]],
  ['memory_20array_20allocator_79',['memory array allocator',['../group__sys__memarray.html',1,'']]],
  ['memory_20management_80',['Memory management',['../group__sys__memory__management.html',1,'']]],
  ['memory_20map_81',['memory map',['../group__cpu__specific__peripheral__memory__map.html',1,'TI CC26x0/CC13x0 peripheral memory map'],['../group__cpu__cc26x2__cc13x2__peripheral__memory__map.html',1,'TI CC26x2, CC13x2 peripheral memory map']]],
  ['memory_20technology_20device_82',['Memory Technology Device',['../group__drivers__mtd.html',1,'']]],
  ['memory_20usage_20monitor_83',['Heap Memory Usage Monitor',['../group__sys__malloc__monitor.html',1,'']]],
  ['memory_20usage_20monitor_20internals_84',['Heap Memory Usage Monitor internals',['../group__sys__malloc__monitor__internals.html',1,'']]],
  ['mesh_20common_85',['Particle Mesh common',['../group__boards__common__particle-mesh.html',1,'']]],
  ['message_20authentication_20codes_86',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['message_20based_20implementation_20of_20bottom_20half_20processor_87',['Message based implementation of Bottom Half Processor',['../group__sys__bhp__msg.html',1,'']]],
  ['message_20interface_20implementation_88',['DSME Message interface implementation.',['../group__pkg__opendsme__dsmemessage.html',1,'']]],
  ['message_20parser_20and_20composer_89',['DNS message parser and composer',['../group__net__dns__msg.html',1,'']]],
  ['message_20parsing_20and_20composition_20configuration_90',['DNS message parsing and composition configuration',['../group__net__dns__msg__conf.html',1,'']]],
  ['messages_91',['messages',['../group__net__gnrc__icmpv6__echo.html',1,'ICMPv6 echo messages'],['../group__net__gnrc__icmpv6__error.html',1,'ICMPv6 error messages']]],
  ['messaging_20ipc_92',['Messaging / IPC',['../group__core__msg.html',1,'']]],
  ['methods_93',['unaligned memory access methods',['../group__sys__unaligned.html',1,'']]],
  ['methods_20for_20congure_20tcp_20reno_94',['The send driver methods for CongURE TCP Reno',['../group__sys__congure__reno__methods.html',1,'']]],
  ['mfrc522_20rfid_20controller_95',['MFRC522 RFID controller',['../group__drivers__mfrc522.html',1,'']]],
  ['mh_20et_20live_20minikit_96',['MH-ET LIVE MiniKit',['../group__boards__esp32__mh-et-live-minikit.html',1,'']]],
  ['mh_20z19_20co2_20sensor_97',['MH-Z19 CO2 sensor',['../group__drivers__mhz19.html',1,'']]],
  ['micro_98',['Tensorflow Lite Micro',['../group__pkg__tflite-micro.html',1,'']]],
  ['micro_20ecc_20for_20riot_99',['Micro-ECC for RIOT',['../group__pkg__micro__ecc.html',1,'']]],
  ['micro_20runtime_100',['WebAssembly Micro Runtime',['../group__pkg__wamr.html',1,'']]],
  ['micro_3abit_101',['BBC micro:bit',['../group__boards__microbit.html',1,'']]],
  ['micro_3abit_20v2_102',['BBC micro:bit v2',['../group__boards__microbit__v2.html',1,'']]],
  ['microbit_20led_20handling_103',['Common microbit LED handling',['../group__boards__common__microbit.html',1,'']]],
  ['microchip_20ata8520e_20transceiver_104',['Microchip ATA8520E transceiver',['../group__drivers__ata8520e.html',1,'']]],
  ['microchip_20cryptoauthentication_20library_105',['Microchip CryptoAuthentication Library',['../group__pkg__cryptoauthlib.html',1,'']]],
  ['microchip_20sam_20e54_20xplained_20pro_106',['Microchip SAM E54 Xplained Pro',['../group__boards__same54-xpro.html',1,'']]],
  ['microchip_20sam_20r34_20xplained_20pro_107',['Microchip SAM R34 Xplained Pro',['../group__boards__samr34-xpro.html',1,'']]],
  ['microchip_20samd5x_20same5x_108',['Microchip SAMD5x/SAME5x',['../group__cpu__samd5x.html',1,'']]],
  ['microchip_20saml10_20saml11_109',['Microchip SAML10/SAML11',['../group__cpu__saml1x.html',1,'']]],
  ['microchip_20saml10_20xplained_20pro_110',['Microchip SAML10 Xplained Pro',['../group__boards__saml10-xpro.html',1,'']]],
  ['microchip_20saml11_20xplained_20pro_111',['Microchip SAML11 Xplained Pro',['../group__boards__saml11-xpro.html',1,'']]],
  ['microchip_20saml1x_112',['Microchip SAML1X',['../group__boards__common__saml1x.html',1,'']]],
  ['microduino_20corerf_113',['Microduino CoreRF',['../group__boards__microduino-corerf.html',1,'']]],
  ['micropython_20riot_20port_114',['MicroPython RIOT port',['../group__pkg__micropython.html',1,'']]],
  ['mii_115',['Ethernet Media-Independent Interface (MII)',['../group__drivers__mii.html',1,'']]],
  ['millisecond_20interval_20event_20timers_116',['Millisecond interval event timers',['../group__sys__evtimer.html',1,'']]],
  ['mineplex_117',['5x5 Font &apos;Mineplex&apos;',['../group__sys__mineplex.html',1,'']]],
  ['mini_118',['Mini',['../group__boards__atmega328p__xplained__mini.html',1,'ATmega328p Xplained Mini'],['../group__boards__samd10-xmini.html',1,'Atmel SAM D10 Xplained Mini']]],
  ['mini_119',['mini',['../group__boards__calliope-mini.html',1,'Calliope mini'],['../group__boards__maple-mini.html',1,'maple-mini'],['../group__boards__esp32c3__wemos__mini.html',1,'Wemos ESP32-C3 mini']]],
  ['mini_20256kib_20board_120',['openlabs.co kw41z-mini-256kib board',['../group__boards__openlabs-kw41z-mini-256kib.html',1,'']]],
  ['mini_20board_121',['Wemos S2 mini Board',['../group__boards__esp32s2-wemos-mini.html',1,'']]],
  ['mini_20board_122',['openlabs.co kw41z-mini board',['../group__boards__openlabs-kw41z-mini.html',1,'']]],
  ['mini_20mp3_20player_123',['DFPlayer Mini MP3 Player',['../group__drivers__dfplayer.html',1,'']]],
  ['minikit_124',['MH-ET LIVE MiniKit',['../group__boards__esp32__mh-et-live-minikit.html',1,'']]],
  ['minimal_20fragment_20forwarding_125',['Minimal fragment forwarding',['../group__net__gnrc__sixlowpan__frag__minfwd.html',1,'']]],
  ['minimal_20netdev_20ethernet_20device_20processing_126',['Minimal netdev Ethernet device processing',['../group__test__utils__netdev__eth__minimal.html',1,'']]],
  ['minimal_20netdev_20ieee_20802_2015_204_20device_20processing_127',['Minimal netdev IEEE 802.15.4 device processing',['../group__test__utils__netdev__ieee802154__minimal.html',1,'']]],
  ['minimal_20non_20destructive_20uri_20parser_128',['A minimal, non-destructive URI parser',['../group__sys__uri__parser.html',1,'']]],
  ['minimal_20radio_20driver_129',['NRF minimal radio driver',['../group__drivers__nrf5x__nrfmin.html',1,'']]],
  ['miscellaneous_20device_20configurations_130',['Miscellaneous Device Configurations',['../group__config__drivers__misc.html',1,'']]],
  ['miscellaneous_20drivers_131',['Miscellaneous Drivers',['../group__drivers__misc.html',1,'']]],
  ['missing_20in_20tt_20string_20h_20tt_132',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['mjson_133',['mjson',['../group__pkg__mjson.html',1,'']]],
  ['mkr_20common_134',['Arduino MKR Common',['../group__boards__common__arduino-mkr.html',1,'']]],
  ['mkr_20wan_201300_135',['Arduino MKR WAN 1300',['../group__boards__arduino-mkrwan1300.html',1,'']]],
  ['mkr1000_136',['Arduino MKR1000',['../group__boards__arduino-mkr1000.html',1,'']]],
  ['mkrfox1200_137',['Arduino MKRFOX1200',['../group__boards__arduino-mkrfox1200.html',1,'']]],
  ['mkrzero_138',['Arduino MKRZERO',['../group__boards__arduino-mkrzero.html',1,'']]],
  ['mma7660_20accelerometer_139',['MMA7660 Accelerometer',['../group__drivers__mma7660.html',1,'']]],
  ['mma8x5x_20accelerometer_140',['MMA8x5x Accelerometer',['../group__drivers__mma8x5x.html',1,'']]],
  ['mma8x5x_20accelerometer_20driver_20compile_20configuration_141',['MMA8x5x Accelerometer driver compile configuration',['../group__drivers__mma8x5x__config.html',1,'']]],
  ['mmc_20device_20api_20sdmmc_142',['SDIO/SD/MMC Device API (SDMMC)',['../group__drivers__sdmmc.html',1,'']]],
  ['mmc_20devices_143',['MTD wrapper for SD/MMC devices',['../group__drivers__mtd__sdmmc.html',1,'']]],
  ['mock_20clock_20backend_144',['ztimer mock clock backend',['../group__sys__ztimer__mock.html',1,'']]],
  ['mock_20implementation_145',['CongURE mock implementation',['../group__sys__congure__mock.html',1,'']]],
  ['mock_20transport_146',['SUIT secure firmware OTA mock transport',['../group__sys__suit__transport__mock.html',1,'']]],
  ['mockup_20device_147',['USBdev mockup device',['../group__drivers__usbdev__mock.html',1,'']]],
  ['mod_20wifi_20esp8266_20dev_148',['Olimex MOD-WIFI-ESP8266-DEV',['../group__boards__esp8266__olimex-mod.html',1,'']]],
  ['mode_149',['netdev BLE mode',['../group__drivers__netdev__ble.html',1,'']]],
  ['mode_20gpio_20driver_150',['Linux User Mode GPIO Driver',['../group__drivers__gpio__linux.html',1,'']]],
  ['mode_20spi_20driver_151',['Linux User Mode SPI Driver',['../group__drivers__spidev__linux.html',1,'']]],
  ['model_152',['model',['../group__usbus__cdc__acm.html',1,'USBUS CDC ACM - USBUS CDC abstract control model'],['../group__usbus__cdc__ecm.html',1,'USBUS CDC ECM - USBUS CDC ethernet control model']]],
  ['model_20for_20the_20decawave_20impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_153',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['modulation_154',['LoRa modulation',['../group__net__lora.html',1,'']]],
  ['modulation_20compile_20configurations_155',['LoRa modulation compile configurations',['../group__net__lora__conf.html',1,'']]],
  ['module_156',['module',['../group__pkg__mbedtls__entropy.html',1,'Access API to Mbed TLS entropy module'],['../group__utils__blob.html',1,'Blob file module'],['../group__sys__cpp__new__delete.html',1,'C++ new and delete operator module'],['../group__net__gnrc__mac.html',1,'Common MAC module'],['../group__sys__log__color.html',1,'log_color: Colored log module'],['../group__sys__log__printfnoformat.html',1,'log_printfnoformat: puts log module'],['../group__net__netstats.html',1,'Packet statistics per module'],['../group__drivers__vl6180x.html',1,'VL6180X Ranging and Ambient Light Sensing (ALS) module']]],
  ['module_20driver_157',['module driver',['../group__drivers__atwinc15x0.html',1,'ATWINC15x0 WiFi module driver'],['../group__drivers__rn2xx3.html',1,'RN2483/RN2903 LoRa module driver']]],
  ['module_20for_20encoding_20psa_20keys_20in_20cbor_158',['Module for encoding PSA keys in CBOR',['../group__sys__psa__crypto__cbor__encoder.html',1,'']]],
  ['module_20vendor_20driver_20package_159',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['modules_160',['modules',['../group__boards__ikea-tradfri.html',1,'IKEA TRÅDFRI modules'],['../group__sys__auto__init__utils.html',1,'Utilities to influence the order of auto-initialized modules'],['../group__sys__ztimer__convert.html',1,'ztimer frequency conversion modules']]],
  ['modules_20from_20dresden_20elektronik_161',['modules from Dresden Elektronik',['../group__boards__deRFmega128.html',1,'deRFmega128 modules from Dresden Elektronik'],['../group__boards__deRFmega256.html',1,'deRFmega256 modules from Dresden Elektronik']]],
  ['moisture_20and_20temperature_20sensor_162',['Adafruit Seesaw Soil Moisture and Temperature Sensor',['../group__drivers__seesaw__soil.html',1,'']]],
  ['moisture_20and_20temperature_20sensor_20driver_20compile_20configuration_163',['Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration',['../group__drivers__seesaw__soil__config.html',1,'']]],
  ['monitor_164',['Heap Memory Usage Monitor',['../group__sys__malloc__monitor.html',1,'']]],
  ['monitor_165',['monitor',['../group__drivers__ina2xx.html',1,'INA2XX current/power monitor'],['../group__drivers__ina3221.html',1,'INA3221 current/power monitor']]],
  ['monitor_20driver_166',['Advanced energy monitor driver',['../group__boards__common__silabs__drivers__aem.html',1,'']]],
  ['monitor_20internals_167',['Heap Memory Usage Monitor internals',['../group__sys__malloc__monitor__internals.html',1,'']]],
  ['monitoring_168',['backup battery monitoring',['../group__drivers__periph__vbat.html',1,'']]],
  ['monochome_20displays_169',['U8G2 graphic library for monochome displays',['../group__pkg__u8g2.html',1,'']]],
  ['monocypher_20cryptographic_20library_170',['Monocypher cryptographic library',['../group__pkg__monocypher.html',1,'']]],
  ['morse_20encoder_171',['Lightweight Morse encoder',['../group__pkg__umorse.html',1,'']]],
  ['most_20libcs_172',['endian conversions as provided by most libcs',['../group__sys__endian.html',1,'']]],
  ['mote_20common_173',['Zolertia Re-Mote common',['../group__boards__common__remote.html',1,'']]],
  ['mote_20prototype_20a_174',['RE-Mote Prototype A',['../group__boards__remote-pa.html',1,'']]],
  ['mote_20revision_20a_175',['RE-Mote Revision A',['../group__boards__remote-reva.html',1,'']]],
  ['mote_20revision_20b_176',['RE-Mote Revision B',['../group__boards__remote-revb.html',1,'']]],
  ['motion_20sensor_177',['PIR Motion Sensor',['../group__drivers__pir.html',1,'']]],
  ['motion_20sensor_20driver_20compile_20configuration_178',['PIR Motion Sensor driver compile configuration',['../group__drivers__pir__config.html',1,'']]],
  ['motor_20driver_179',['Motor Driver',['../group__drivers__motor.html',1,'DC Motor Driver'],['../group__drivers__servo.html',1,'Servo Motor Driver']]],
  ['motor_5fdriver_20driver_20compile_20configuration_180',['Motor_Driver driver compile configuration',['../group__drivers__motor__driver__config.html',1,'']]],
  ['mp3_20player_181',['DFPlayer Mini MP3 Player',['../group__drivers__dfplayer.html',1,'']]],
  ['mpl3115a2_20pressure_20sensor_182',['MPL3115A2 Pressure Sensor',['../group__drivers__mpl3115a2.html',1,'']]],
  ['mpl3115a2_20pressure_20sensor_20driver_20compile_20configuration_183',['MPL3115A2 Pressure Sensor driver compile configuration',['../group__drivers__mpl3115a2__config.html',1,'']]],
  ['mpu_209x50_20mpu9150_20and_20mpu9250_20accelerometer_20magnetometer_20gyroscope_184',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['mpu9150_20and_20mpu9250_20accelerometer_20magnetometer_20gyroscope_185',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['mpu9250_20accelerometer_20magnetometer_20gyroscope_186',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['mpu_5fnoexec_5fram_187',['mpu_noexec_ram',['../group__pseudomodule__mpu__noexec__ram.html',1,'']]],
  ['mpu_5fstack_5fguard_188',['mpu_stack_guard',['../group__pseudomodule__mpu__stack__guard.html',1,'']]],
  ['mq_203_20alcohol_20tester_189',['MQ-3 Alcohol Tester',['../group__drivers__mq3.html',1,'']]],
  ['mqtt_20client_20compile_20configurations_190',['MQTT client compile configurations',['../group__net__mqtt__conf.html',1,'']]],
  ['mqtt_20framework_191',['PAHO MQTT framework',['../group__pkg__paho__mqtt.html',1,'']]],
  ['mqtt_20sn_20client_20asymcute_192',['MQTT-SN Client (Asymcute)',['../group__net__asymcute.html',1,'']]],
  ['mqtt_20sn_20client_20compile_20configurations_193',['MQTT SN Client compile configurations',['../group__net__asymcute__conf.html',1,'Asymcute (MQTT-SN Client) compile configurations'],['../group__net__emcute__conf.html',1,'EmCute (MQTT-SN Client) compile configurations']]],
  ['mqtt_20sn_20client_20emcute_194',['MQTT-SN Client (emCute)',['../group__net__emcute.html',1,'']]],
  ['mqtt_20sn_20defines_195',['MQTT-SN Defines',['../group__net__mqttsn.html',1,'']]],
  ['mr_20fsk_20phy_196',['AT86RF215 MR-FSK PHY',['../group__drivers__at86rf215__fsk.html',1,'']]],
  ['mr_20o_20qpsk_20phy_197',['AT86RF215 MR-O-QPSK PHY',['../group__drivers__at86rf215__oqpsk.html',1,'']]],
  ['mr_20ofdm_20phy_198',['AT86RF215 MR-OFDM PHY',['../group__drivers__at86rf215__ofdm.html',1,'']]],
  ['mrf24j40_20based_20drivers_199',['MRF24J40 based drivers',['../group__drivers__mrf24j40.html',1,'']]],
  ['mrf24j40_20driver_20compile_20configuration_200',['mrf24j40 driver compile configuration',['../group__drivers__mrf24j40__config.html',1,'']]],
  ['msb_20430_201',['MSB-430',['../group__boards__msb430.html',1,'']]],
  ['msb_20430_20common_202',['MSB-430 common',['../group__boards__common__msb-430.html',1,'']]],
  ['msb_20430h_203',['MSB-430H',['../group__boards__msb430h.html',1,'']]],
  ['msb_20a2_204',['MSB-A2',['../group__boards__msba2.html',1,'']]],
  ['msb_20iot_205',['MSB-IoT',['../group__boards__msbiot.html',1,'']]],
  ['msp430_206',['TI MSP430',['../group__cpu__msp430.html',1,'']]],
  ['msp430_20boards_207',['Common Configuration Snippets for MSP430 boards',['../group__boards__common__msp430.html',1,'']]],
  ['msp430_20f2xx_20g2xx_20mcu_20family_208',['MSP430 F2xx/G2xx MCU family',['../group__cpu__msp430__f2xx__g2xx.html',1,'']]],
  ['msp430_20h1611_209',['Olimex MSP430-H1611',['../group__boards__olimex__msp430__h1611.html',1,'']]],
  ['msp430_20h2618_210',['Olimex MSP430-H2618',['../group__boards__olimex__msp430__h2618.html',1,'']]],
  ['msp430_20x1xx_20mcu_20family_211',['MSP430 x1xx MCU family',['../group__cpu__msp430__x1xx.html',1,'']]],
  ['mtd_212',['Native MTD',['../group__drivers__mtd__native.html',1,'']]],
  ['mtd_20address_20mapper_213',['MTD address mapper',['../group__drivers__mtd__mapper.html',1,'']]],
  ['mtd_20devices_214',['MTD wrapper for emulated MTD devices',['../group__drivers__mtd__emulated.html',1,'']]],
  ['mtd_20wrapper_20for_20at24cxxx_20family_20of_20i2c_20eeproms_215',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['mtd_20wrapper_20for_20at25xxx_20family_20of_20spi_20eeproms_216',['MTD wrapper for AT25xxx family of SPI-EEPROMs',['../group__drivers__mtd__at25xxx.html',1,'']]],
  ['mtd_20wrapper_20for_20emulated_20mtd_20devices_217',['MTD wrapper for emulated MTD devices',['../group__drivers__mtd__emulated.html',1,'']]],
  ['mtd_20wrapper_20for_20flashpage_20devices_218',['MTD wrapper for Flashpage devices',['../group__drivers__mtd__flashpage.html',1,'']]],
  ['mtd_20wrapper_20for_20sam0_20sdhc_20devices_219',['MTD wrapper for SAM0 SDHC devices',['../group__drivers__mtd__sam0__sdhc.html',1,'']]],
  ['mtd_20wrapper_20for_20sd_20mmc_20devices_220',['MTD wrapper for SD/MMC devices',['../group__drivers__mtd__sdmmc.html',1,'']]],
  ['mtd_20wrapper_20for_20spi_20sd_20cards_221',['MTD wrapper for SPI SD Cards',['../group__drivers__mtd__sdcard.html',1,'']]],
  ['mulle_222',['Eistec Mulle',['../group__boards__mulle.html',1,'']]],
  ['multimedia_20device_20drivers_223',['Multimedia Device Drivers',['../group__drivers__multimedia.html',1,'']]],
  ['multimedia_20driver_20auto_20initialization_224',['Multimedia driver auto-initialization',['../group__sys__auto__init__multimedia.html',1,'']]],
  ['multiplexer_225',['Callback multiplexer',['../group__sys__cb__mux.html',1,'']]],
  ['multiplication_20library_226',['GEMM (General Matrix Multiplication) library',['../group__pkg__gemmlowp.html',1,'']]],
  ['multiplication_20library_227',['The ruy matrix multiplication library',['../group__pkg__ruy.html',1,'']]],
  ['mutex_228',['Mutex',['../group__core__sync__mutex.html',1,'Mutex'],['../group__core__sync__rmutex.html',1,'Recursive Mutex']]],
  ['my9221_20led_20controller_229',['MY9221 LED controller',['../group__drivers__my9221.html',1,'']]],
  ['mynewt_20core_230',['mynewt-core',['../group__pkg__mynewt__core.html',1,'']]]
];
