var searchData=
[
  ['r2_0',['Serpente R2',['../group__boards__serpente.html',1,'']]],
  ['r21_20xplained_20pro_1',['Atmel SAM R21 Xplained Pro',['../group__boards__samr21-xpro.html',1,'']]],
  ['r30_20xplained_20pro_2',['Atmel SAM R30 Xplained Pro',['../group__boards__samr30-xpro.html',1,'']]],
  ['r34_20xplained_20pro_3',['Microchip SAM R34 Xplained Pro',['../group__boards__samr34-xpro.html',1,'']]],
  ['radio_20debug_20pins_4',['STM32WL Sub-GHz Radio debug pins',['../group__cpu__stm32__wl__debug__subghz__radio.html',1,'']]],
  ['radio_20driver_5',['radio driver',['../group__drivers__cc2420.html',1,'CC2420 radio driver'],['../group__drivers__kw2xrf.html',1,'KW2x radio-driver'],['../group__drivers__kw41zrf.html',1,'KW41Z radio-driver'],['../group__drivers__sx1280.html',1,'LoRa radio driver'],['../group__drivers__nrf5x__nrfble.html',1,'NRF BLE radio driver'],['../group__drivers__nrf5x__nrfmin.html',1,'NRF minimal radio driver'],['../group__pkg__driver__sx126x.html',1,'SX1261/2 LoRa radio driver'],['../group__drivers__sx126x.html',1,'SX1261/2/8 and LLCC68 LoRa radio driver']]],
  ['radio_20driver_20compile_20configuration_6',['Radio driver compile configuration',['../group__drivers__pn532__config.html',1,'PN532 NFC Radio driver compile configuration'],['../group__drivers__rn2xx3__config.html',1,'RN2483/RN2903 Radio driver compile configuration']]],
  ['radio_20driver_20compile_20configuration_7',['CR20A and KW2xD radio driver compile configuration',['../group__drivers__kw2xrf__config.html',1,'']]],
  ['radio_20drivers_8',['802.15.4 radio drivers',['../group__drivers__netdev__ieee802154.html',1,'']]],
  ['radio_20hardware_20abstraction_20layer_9',['IEEE802.15.4 Radio Hardware Abstraction Layer',['../group__drivers__ieee802154__hal.html',1,'']]],
  ['radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_10',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['radios_20driver_11',['Semtech SX1272 and SX1276 radios driver',['../group__drivers__sx127x.html',1,'']]],
  ['ram_12',['Non-volatile RAM',['../group__drivers__nvram.html',1,'']]],
  ['ram_20storage_20backend_13',['ram storage backend',['../group__sys__suit__storage__ram.html',1,'']]],
  ['random_14',['Random',['../group__sys__random.html',1,'']]],
  ['random_20number_20generator_15',['SHAX random number generator',['../group__sys__random__shaxprng.html',1,'']]],
  ['range_20finder_16',['srf04 ultra sonic range finder',['../group__drivers__srf04.html',1,'']]],
  ['range_20sensor_17',['range sensor',['../group__drivers__srf02.html',1,'SRF02 ultrasonic range sensor'],['../group__drivers__srf08.html',1,'SRF08 ultrasonic range sensor']]],
  ['ranges_18',['IANA Port Ranges',['../group__net__iana__portrange.html',1,'']]],
  ['ranging_20and_20ambient_20light_20sensing_20als_20module_19',['VL6180X Ranging and Ambient Light Sensing (ALS) module',['../group__drivers__vl6180x.html',1,'']]],
  ['raspberry_20pi_20pico_20',['Raspberry Pi Pico',['../group__boards__rpi__pico.html',1,'']]],
  ['raspberry_20pi_20pico_20w_21',['Raspberry Pi Pico W',['../group__boards__rpi__pico__w.html',1,'']]],
  ['raw_20ipv4_20ipv6_20sock_20api_22',['Raw IPv4/IPv6 sock API',['../group__net__sock__ip.html',1,'']]],
  ['rd_20common_23',['CoRE RD Common',['../group__net__cord__common.html',1,'']]],
  ['rd_20configuration_24',['CoRE RD Configuration',['../group__net__cord__config.html',1,'']]],
  ['rd_20endpoint_25',['CoRE RD Endpoint',['../group__net__cord__ep.html',1,'']]],
  ['rd_20endpoint_20and_20lookup_20client_26',['CoRE RD Endpoint and Lookup Client',['../group__net__cord.html',1,'']]],
  ['rd_20endpoint_20standalone_20extension_27',['CoRE RD Endpoint Standalone Extension',['../group__net__cord__ep__standalone.html',1,'']]],
  ['rd_20lookup_20client_28',['CoRE RD Lookup Client',['../group__net__cord__lc.html',1,'']]],
  ['rd_20simple_20registration_20endpoint_29',['CoRE RD Simple Registration Endpoint',['../group__net__cord__epsim.html',1,'']]],
  ['re_20mote_20common_30',['Zolertia Re-Mote common',['../group__boards__common__remote.html',1,'']]],
  ['re_20mote_20prototype_20a_31',['RE-Mote Prototype A',['../group__boards__remote-pa.html',1,'']]],
  ['re_20mote_20revision_20a_32',['RE-Mote Revision A',['../group__boards__remote-reva.html',1,'']]],
  ['re_20mote_20revision_20b_33',['RE-Mote Revision B',['../group__boards__remote-revb.html',1,'']]],
  ['reactive_20discovery_20of_20p2p_20routes_20in_20llns_34',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['read_20timeouts_20with_20isr_20pipe_35',['Read timeouts with ISR pipe',['../group__isr__pipe__read__timeout.html',1,'']]],
  ['reader_36',['PN532 NFC Reader',['../group__drivers__pn532.html',1,'']]],
  ['real_20time_20clock_37',['DS3231 Real Time Clock',['../group__drivers__ds3231.html',1,'']]],
  ['real_20time_20clock_20rtc_38',['NXP QN908x Real-Time-Clock (RTC)',['../group__cpu__qn908x__rtc.html',1,'']]],
  ['reassembly_20buffer_39',['reassembly buffer',['../group__net__gnrc__sixlowpan__frag__rb.html',1,'6LoWPAN reassembly buffer'],['../group__net__gnrc__sixlowpan__frag__vrb.html',1,'Virtual reassembly buffer']]],
  ['reassembly_20statistics_40',['Fragmentation and reassembly statistics',['../group__net__gnrc__sixlowpan__frag__stats.html',1,'']]],
  ['receiver_41',['IR NEC Remote receiver',['../group__drivers__ir__nec.html',1,'']]],
  ['receiver_20with_2077_205_20khz_42',['DCF77 long wave receiver with 77,5 kHz',['../group__drivers__dcf77.html',1,'']]],
  ['recognition_43',['Touch device gesture recognition',['../group__drivers__touch__dev__gestures.html',1,'']]],
  ['recovery_44',['recovery',['../group__net__gnrc__sixlowpan__frag__sfr.html',1,'6LoWPAN selective fragment recovery'],['../group__net__sixlowpan__sfr.html',1,'6LoWPAN selective fragment recovery']]],
  ['recursive_20mutex_45',['Recursive Mutex',['../group__core__sync__rmutex.html',1,'']]],
  ['reed_20solomon_20code_20implementation_46',['small Reed-Solomon code implementation',['../group__pkg__nanors.html',1,'']]],
  ['reel_20board_47',['Phytec reel board',['../group__boards__reel.html',1,'']]],
  ['ref_20net_5fgnrc_5fnetif_48',['Send queue for @ref net_gnrc_netif',['../group__net__gnrc__netif__pktq.html',1,'']]],
  ['registration_49',['Secure Element Driver Registration',['../group__se__registration.html',1,'']]],
  ['registration_50',['EEPROM registration',['../group__sys__eepreg.html',1,'']]],
  ['registration_20endpoint_51',['CoRE RD Simple Registration Endpoint',['../group__net__cord__epsim.html',1,'']]],
  ['registry_52',['registry',['../group__net__gnrc__netreg.html',1,'Network protocol registry'],['../group__sys__saul__reg.html',1,'SAUL registry']]],
  ['relay_20agent_53',['DHCPv6 relay agent',['../group__net__dhcpv6__relay.html',1,'']]],
  ['relic_20toolkit_20for_20riot_54',['Relic toolkit for RIOT',['../group__pkg__relic.html',1,'']]],
  ['remote_20receiver_55',['IR NEC Remote receiver',['../group__drivers__ir__nec.html',1,'']]],
  ['reno_56',['Reno',['../group__sys__congure__reno.html',1,'CongURE implementation of TCP Reno'],['../group__net__gnrc__sixlowpan__frag__sfr__congure__reno.html',1,'gnrc_sixlowpan_frag_sfr_congure_reno: TCP Reno'],['../group__sys__congure__reno__methods.html',1,'The send driver methods for CongURE TCP Reno']]],
  ['reno_20with_20abe_57',['gnrc_sixlowpan_frag_sfr_congure_abe: TCP Reno with ABE',['../group__net__gnrc__sixlowpan__frag__sfr__congure__abe.html',1,'']]],
  ['reporting_58',['Error reporting',['../group__net__gnrc__neterr.html',1,'']]],
  ['representations_59',['Time unit representations',['../group__sys__time__units.html',1,'']]],
  ['reset_20via_20usb_20cdc_20acm_60',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['reset_20via_20usb_20cdc_20acm_20internals_61',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['resolution_20protocol_20arp_62',['Address resolution protocol (ARP)',['../group__net__arp.html',1,'']]],
  ['result_20helper_63',['Scan Result Helper',['../group__pkg__nimble__scanlist.html',1,'']]],
  ['result_20output_64',['Test result output',['../group__test__utils__result__output.html',1,'']]],
  ['result_20output_20helpers_65',['Test Utils Result Output Helpers',['../group__turo__helpers.html',1,'']]],
  ['result_20output_20implementation_20api_66',['Test Utils Result Output Implementation API',['../group__turo__API.html',1,'']]],
  ['result_20output_20plain_20text_67',['Test result output plain text',['../group__test__utils__result__output__txt.html',1,'']]],
  ['result_20output_20structure_68',['Test result output structure',['../group__test__utils__result__output__check.html',1,'']]],
  ['result_20output_20with_20json_69',['Test result output with JSON',['../group__test__utils__result__output__json.html',1,'']]],
  ['revision_20a_70',['RE-Mote Revision A',['../group__boards__remote-reva.html',1,'']]],
  ['revision_20b_71',['RE-Mote Revision B',['../group__boards__remote-revb.html',1,'']]],
  ['rf_20core_20interface_72',['CC2538 RF core interface',['../group__cpu__cc2538__rfcore.html',1,'']]],
  ['rfc_204122_20compliant_20uuid_20s_73',['RFC 4122 compliant UUID&apos;s',['../group__sys__uuid.html',1,'']]],
  ['rfid_20controller_74',['MFRC522 RFID controller',['../group__drivers__mfrc522.html',1,'']]],
  ['rgb_20led_75',['APA102 RGB LED',['../group__drivers__apa102.html',1,'']]],
  ['rgb_20led_20neopixel_76',['WS2812/SK6812 RGB LED (NeoPixel)',['../group__drivers__ws281x.html',1,'']]],
  ['rgb_20light_20sensor_77',['TCS37727 RGB Light Sensor',['../group__drivers__tcs37727.html',1,'']]],
  ['rgb_20light_20sensor_78',['ISL29125 RGB light sensor',['../group__drivers__isl29125.html',1,'']]],
  ['rgb_20light_20sensor_20driver_20compile_20configuration_79',['TCS37727 RGB Light Sensor driver compile configuration',['../group__drivers__tcs37727__config.html',1,'']]],
  ['ringbuffer_80',['chunked Ringbuffer',['../group__sys__chunk__buffer.html',1,'']]],
  ['ringbuffer_81',['Thread safe ringbuffer',['../group__sys__tsrb.html',1,'']]],
  ['riot_82',['RIOT',['../group__cpp11-compat.html',1,'C++11 wrapper for RIOT'],['../group__pkg__libcose.html',1,'libcose for RIOT'],['../group__pkg__lua.html',1,'Lua ported to RIOT'],['../group__pkg__micro__ecc.html',1,'Micro-ECC for RIOT'],['../group__posix.html',1,'POSIX wrapper for RIOT'],['../group__pkg__qcbor.html',1,'QCBOR for RIOT'],['../group__pkg__relic.html',1,'Relic toolkit for RIOT'],['../group__pkg__tinydtls.html',1,'TinyDTLS for RIOT']]],
  ['riot_20header_20helpers_20and_20tools_83',['RIOT header helpers and tools',['../group__sys__riotboot__hdr.html',1,'']]],
  ['riot_20integration_84',['RIOT Integration',['../group__pkg__nimble__contrib.html',1,'']]],
  ['riot_20port_85',['MicroPython RIOT port',['../group__pkg__micropython.html',1,'']]],
  ['riotboot_86',['riotboot',['../group__sys__riotboot__magic.html',1,'Magic values for riotboot'],['../group__bootloader__riotboot.html',1,'riotboot']]],
  ['riotboot_20dfu_87',['riotboot DFU',['../group__bootloader__riotboot__dfu.html',1,'']]],
  ['riotboot_20flash_20writer_88',['riotboot flash writer',['../group__sys__riotboot__flashwrite.html',1,'']]],
  ['riotboot_20flashwrite_20storage_20backend_89',['riotboot flashwrite storage backend',['../group__sys__suit__storage__flashwrite.html',1,'']]],
  ['riotboot_20serial_20bootloader_90',['riotboot serial bootloader',['../group__bootloader__riotboot__serial.html',1,'']]],
  ['riotboot_20tinyusb_20dfu_91',['riotboot tinyUSB DFU',['../group__pkg__tinyusb__dfu.html',1,'']]],
  ['riotboot_20vfs_20storage_20backend_92',['riotboot vfs storage backend',['../group__sys__suit__storage__vfs.html',1,'']]],
  ['risc_20v_20board_93',['RISC V board',['../group__boards__seeedstudio-gd32.html',1,'SeeedStudio GD32 RISC-V board'],['../group__boards__hifive1.html',1,'SiFive HiFive1 RISC-V board'],['../group__boards__hifive1b.html',1,'SiFive HiFive1b RISC-V board']]],
  ['risc_20v_20common_94',['RISC-V common',['../group__cpu__riscv__common.html',1,'']]],
  ['ritchie_95',['Kernighan and Ritchie',['../group__sys__hashes__kr.html',1,'']]],
  ['rn2483_20rn2903_20lora_20module_20driver_96',['RN2483/RN2903 LoRa module driver',['../group__drivers__rn2xx3.html',1,'']]],
  ['rn2483_20rn2903_20radio_20driver_20compile_20configuration_97',['RN2483/RN2903 Radio driver compile configuration',['../group__drivers__rn2xx3__config.html',1,'']]],
  ['rn2903_20lora_20module_20driver_98',['RN2483/RN2903 LoRa module driver',['../group__drivers__rn2xx3.html',1,'']]],
  ['rn2903_20radio_20driver_20compile_20configuration_99',['RN2483/RN2903 Radio driver compile configuration',['../group__drivers__rn2xx3__config.html',1,'']]],
  ['rnga_100',['Kinetis RNGA',['../group__cpu__kinetis__rnga.html',1,'']]],
  ['robin_20scheduler_101',['Round Robin Scheduler',['../group__sched__round__robin.html',1,'']]],
  ['rotating_102',['Rotating',['../group__sys__hashes__rotating.html',1,'']]],
  ['round_20robin_20scheduler_103',['Round Robin Scheduler',['../group__sched__round__robin.html',1,'']]],
  ['router_20list_104',['Authoritative border router list',['../group__net__gnrc__ipv6__nib__abr.html',1,'']]],
  ['routes_20in_20llns_105',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['routing_20header_20extension_106',['routing header extension',['../group__net__ipv6__ext__rh.html',1,'IPv6 routing header extension'],['../group__net__gnrc__rpl__srh.html',1,'RPL source routing header extension'],['../group__net__gnrc__ipv6__ext__rh.html',1,'Support for IPv6 routing header extension']]],
  ['rpl_107',['RPL',['../group__net__netstats__rpl.html',1,'Packet statistics for RPL'],['../group__net__gnrc__rpl.html',1,'RPL']]],
  ['rpl_20over_20ble_20for_20nimble_108',['RPL-over-BLE for NimBLE',['../group__pkg__nimble__rpble.html',1,'']]],
  ['rpl_20source_20routing_20header_20extension_109',['RPL source routing header extension',['../group__net__gnrc__rpl__srh.html',1,'']]],
  ['rpx0xx_20mcus_110',['RPx0xx MCUs',['../group__cpu__rpx0xx.html',1,'']]],
  ['rss2_111',['Atmega256RFR2 rss2',['../group__boards__avr-rss2.html',1,'']]],
  ['rtc_112',['RTC',['../group__drivers__ds1307.html',1,'DS1307 RTC'],['../group__drivers__ds3234.html',1,'DS3234 Extremely Accurate SPI RTC'],['../group__cpu__kinetis__rtc.html',1,'Kinetis RTC'],['../group__cpu__qn908x__rtc.html',1,'NXP QN908x Real-Time-Clock (RTC)'],['../group__drivers__periph__rtc.html',1,'RTC']]],
  ['rtc_20backend_113',['ztimer periph/rtc backend',['../group__sys__ztimer__periph__rtc.html',1,'']]],
  ['rtc_20driver_20compile_20configuration_114',['DS1307 RTC driver compile configuration',['../group__drivers__ds1307__config.html',1,'']]],
  ['rtc_20emulation_20on_20top_20of_20a_20rtt_115',['RTC emulation on top of a RTT',['../group__drivers__rtt__rtc.html',1,'']]],
  ['rtc_20helpers_116',['RTC helpers',['../group__sys__rtc__utils.html',1,'']]],
  ['rtc_20memory_117',['Low-Power RTC Memory',['../group__drivers__periph__rtc__mem.html',1,'']]],
  ['rtos_20sdk_20for_20the_20esp8266_20mcu_20support_118',['ESP8266 RTOS SDK for the ESP8266 MCU support',['../group__pkg__esp8266__sdk.html',1,'']]],
  ['rtt_119',['RTT',['../group__drivers__rtt__rtc.html',1,'RTC emulation on top of a RTT'],['../group__drivers__periph__rtt.html',1,'RTT'],['../group__sys__stdio__rtt.html',1,'STDIO over SEGGER RTT']]],
  ['rtt_20backend_120',['ztimer periph/rtt backend',['../group__sys__ztimer__periph__rtt.html',1,'']]],
  ['runtime_121',['WebAssembly Micro Runtime',['../group__pkg__wamr.html',1,'']]],
  ['ruuvitag_122',['RuuviTag',['../group__boards__ruuvitag.html',1,'']]],
  ['ruy_20matrix_20multiplication_20library_123',['The ruy matrix multiplication library',['../group__pkg__ruy.html',1,'']]]
];
