var searchData=
[
  ['i_20nucleo_20lrwan1_20lora_20board_0',['ST I-NUCLEO-LRWAN1 LoRa board',['../group__boards__i-nucleo-lrwan1.html',1,'']]],
  ['i_20o_1',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['i_20o_20expanders_2',['PCF857X I2C I/O expanders',['../group__drivers__pcf857x.html',1,'']]],
  ['i_20o_20utils_3',['GPIO I/O Utils',['../group__gpio__util.html',1,'']]],
  ['i2c_4',['I2C',['../group__drivers__periph__i2c.html',1,'I2C'],['../group__cpu__kinetis__i2c.html',1,'Kinetis I2C'],['../group__cpu__qn908x__i2c.html',1,'NXP QN908x I2C'],['../group__drivers__si1133.html',1,'Si1133 UV Index/Ambient Light Sensor with I2C']]],
  ['i2c_20eeproms_5',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['i2c_20i_20o_20expanders_6',['PCF857X I2C I/O expanders',['../group__drivers__pcf857x.html',1,'']]],
  ['i2c_20interface_7',['MCP47xx DAC with I2C interface',['../group__drivers__mcp47xx.html',1,'']]],
  ['i2c_20lcd_20controller_8',['AIP31068 I2C LCD controller',['../group__drivers__aip31068.html',1,'']]],
  ['i2c_20program_9',['PIO I2C program',['../group__drivers__periph__pio__i2c.html',1,'']]],
  ['i2c_20pwm_20controller_10',['I2C PWM controller',['../group__drivers__pca9633.html',1,'PCA9633 I2C PWM controller'],['../group__drivers__pca9685.html',1,'PCA9685 I2C PWM controller']]],
  ['i2c_20spi_20bme680_20sensor_11',['Driver package for I2C/SPI BME680 sensor',['../group__pkg__driver__bme680.html',1,'']]],
  ['iana_20port_20ranges_12',['IANA Port Ranges',['../group__net__iana__portrange.html',1,'']]],
  ['ibeacon_13',['Skald about iBeacon',['../group__ble__skald__ibeacon.html',1,'']]],
  ['icmpv4_14',['ICMPV4',['../group__net__icmp.html',1,'']]],
  ['icmpv6_15',['ICMPV6',['../group__net__icmpv6.html',1,'']]],
  ['icmpv6_16',['ICMPv6',['../group__net__gnrc__icmpv6.html',1,'']]],
  ['icmpv6_20echo_20messages_17',['ICMPv6 echo messages',['../group__net__gnrc__icmpv6__echo.html',1,'']]],
  ['icmpv6_20error_20messages_18',['ICMPv6 error messages',['../group__net__gnrc__icmpv6__error.html',1,'']]],
  ['id_20chip_19',['AT24MAC unique ID chip',['../group__drivers__at24mac.html',1,'']]],
  ['id_20generator_20',['Locally Unique ID Generator',['../group__sys__luid.html',1,'']]],
  ['identifier_21',['identifier',['../group__net__eui48.html',1,'IEEE EUI-48 identifier'],['../group__net__eui64.html',1,'IEEE EUI-64 identifier']]],
  ['identity_20online_202_22',['FIDO2 - Fast Identity Online 2',['../group__fido2.html',1,'']]],
  ['idf_20interface_20api_23',['ESP-IDF Interface API',['../group__cpu__esp32__esp__idf__api.html',1,'']]],
  ['ieee_20802_2015_204_24',['IEEE 802.15.4',['../group__net__ieee802154.html',1,'']]],
  ['ieee_20802_2015_204_20device_20processing_25',['Minimal netdev IEEE 802.15.4 device processing',['../group__test__utils__netdev__ieee802154__minimal.html',1,'']]],
  ['ieee_20802_2015_204_20dsme_26',['openDSME - IEEE 802.15.4 DSME',['../group__pkg__opendsme.html',1,'']]],
  ['ieee_20802_2015_204_20frame_20headers_20and_20definitions_27',['IEEE 802.15.4 frame headers and definitions',['../group__net__ieee802154__header.html',1,'']]],
  ['ieee_20802_2015_204_20security_28',['IEEE 802.15.4 security',['../group__net__ieee802154__security.html',1,'']]],
  ['ieee_20eui_2048_2064_20provider_29',['IEEE EUI-48/64 provider',['../group__net__eui__provider.html',1,'']]],
  ['ieee_20eui_2048_20identifier_30',['IEEE EUI-48 identifier',['../group__net__eui48.html',1,'']]],
  ['ieee_20eui_2064_20identifier_31',['IEEE EUI-64 identifier',['../group__net__eui64.html',1,'']]],
  ['ieee802_2015_204_20compile_20configurations_32',['IEEE802.15.4 compile configurations',['../group__net__ieee802154__conf.html',1,'']]],
  ['ieee802_2015_204_20driver_20for_20nrf52840_20socs_33',['IEEE802.15.4 Driver for nRF52840 SoCs',['../group__drivers__nrf52__802154.html',1,'']]],
  ['ieee802_2015_204_20radio_20hardware_20abstraction_20layer_34',['IEEE802.15.4 Radio Hardware Abstraction Layer',['../group__drivers__ieee802154__hal.html',1,'']]],
  ['ieee802_2015_204_20submac_20layer_35',['IEEE802.15.4 SubMAC layer',['../group__net__ieee802154__submac.html',1,'']]],
  ['ieee802_2015_204_20submac_20netdev_20layer_36',['IEEE802.15.4 SubMAC netdev layer',['../group__drivers__netdev__ieee802154__submac.html',1,'']]],
  ['ikea_20trådfri_20modules_37',['IKEA TRÅDFRI modules',['../group__boards__ikea-tradfri.html',1,'']]],
  ['ili9341_20display_20driver_38',['ILI9341 display driver',['../group__drivers__ili9341.html',1,'']]],
  ['illuminance_39',['Illuminance',['../group__lwm2m__objects__illuminance.html',1,'']]],
  ['illuminance_20sensor_40',['TSL4531x Illuminance sensor',['../group__drivers__tsl4531x.html',1,'']]],
  ['illuminance_20sensor_41',['TSL2561 illuminance sensor',['../group__drivers__tsl2561.html',1,'']]],
  ['illuminance_20sensor_20object_20compile_20configurations_42',['LwM2M Illuminance Sensor object compile configurations',['../group__lwm2m__objects__illuminance__config.html',1,'']]],
  ['im880b_43',['im880b',['../group__boards__im880b.html',1,'']]],
  ['imath_3a_20integer_20math_20functions_44',['imath: Integer Math functions',['../group__sys__imath.html',1,'']]],
  ['implementation_45',['GNRC netif Implementation',['../group__pkg__nimble__netif.html',1,'']]],
  ['implementation_46',['implementation',['../group__net__telnet.html',1,'basic Telnet server implementation'],['../group__sys__congure__mock.html',1,'CongURE mock implementation'],['../group__net__gcoap__dns.html',1,'DNS over CoAP client implementation'],['../group__pkg__opendsme__dsmemessage.html',1,'DSME Message interface implementation.'],['../group__pkg__opendsme__dsmeplatform.html',1,'DSME Platform interface implementation.'],['../group__pkg__lwext4.html',1,'lightweight ext2/3/4 implementation'],['../group__net__nanocoap__cache.html',1,'nanoCoAP-Cache implementation'],['../group__cpu__nrf52__nrfusb.html',1,'NRF usb peripheral implementation'],['../group__pkg__semtech-loramac.html',1,'Semtech LoRaMAC implementation'],['../group__pkg__nanors.html',1,'small Reed-Solomon code implementation'],['../group__sys__tiny__strerror.html',1,'Tiny strerror() implementation']]],
  ['implementation_20api_47',['Test Utils Result Output Implementation API',['../group__turo__API.html',1,'']]],
  ['implementation_20compile_20configurations_48',['GNRC sock implementation compile configurations',['../group__net__gnrc__sock__conf.html',1,'']]],
  ['implementation_20for_20the_20uwb_20core_20driver_20for_20decawave_20dw1000_20transceiver_49',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['implementation_20in_20gnrc_50',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['implementation_20of_20bottom_20half_20processor_51',['implementation of Bottom Half Processor',['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['implementation_20of_20quic_20s_20cc_52',['CongURE implementation of QUIC&apos;s CC',['../group__sys__congure__quic.html',1,'']]],
  ['implementation_20of_20sock_20api_53',['lwIP-specific implementation of sock API',['../group__pkg__lwip__sock.html',1,'']]],
  ['implementation_20of_20tcp_20abe_54',['CongURE implementation of TCP ABE',['../group__sys__congure__abe.html',1,'']]],
  ['implementation_20of_20tcp_20reno_55',['CongURE implementation of TCP Reno',['../group__sys__congure__reno.html',1,'']]],
  ['implementation_20of_20the_20sock_20api_56',['implementation of the sock API',['../group__net__gnrc__sock.html',1,'GNRC-specific implementation of the sock API'],['../group__pkg__openwsn__sock.html',1,'OpenWSN-specific implementation of the sock API']]],
  ['implementations_57',['LwM2M Object implementations',['../group__lwm2m__objects.html',1,'']]],
  ['impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_58',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['in_20cbor_59',['Module for encoding PSA keys in CBOR',['../group__sys__psa__crypto__cbor__encoder.html',1,'']]],
  ['in_20cpu_20transceiver_20driver_20compile_20configuration_60',['KW41Z, KW21Z in-cpu transceiver driver compile configuration',['../group__drivers__kw41zrf__config.html',1,'']]],
  ['in_20gnrc_61',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['in_20llns_62',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['in_20peripheral_20gpio_20low_20level_20api_63',['IRQ Support in Peripheral GPIO Low-Level API',['../group__drivers__periph__gpio__ll__irq.html',1,'']]],
  ['in_20stdio_20uart_64',['Support for DOS line endings in STDIO-UART',['../group__sys__stdio__uart__onlcr.html',1,'']]],
  ['in_20tt_20string_20h_20tt_65',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['ina2xx_20current_20power_20monitor_66',['INA2XX current/power monitor',['../group__drivers__ina2xx.html',1,'']]],
  ['ina3221_20current_20power_20monitor_67',['INA3221 current/power monitor',['../group__drivers__ina3221.html',1,'']]],
  ['independent_20access_20to_20architecture_68',['Platform-independent access to architecture',['../group__sys__architecture.html',1,'']]],
  ['independent_20helpers_20for_20ipv6_20over_20x_69',['Stack-independent helpers for IPv6 over X',['../group__net__l2util.html',1,'']]],
  ['independent_20interface_20mii_70',['Ethernet Media-Independent Interface (MII)',['../group__drivers__mii.html',1,'']]],
  ['independent_20layer_20of_20the_20arduino_20cores_71',['Hardware independent layer of the Arduino cores',['../group__pkg__arduino__api.html',1,'']]],
  ['index_20ambient_20light_20sensor_20with_20i2c_72',['Si1133 UV Index/Ambient Light Sensor with I2C',['../group__drivers__si1133.html',1,'']]],
  ['influence_20the_20order_20of_20auto_20initialized_20modules_73',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['information_20base_20fib_74',['Forwarding Information Base (FIB)',['../group__net__fib.html',1,'']]],
  ['information_20base_20for_20ipv6_75',['Neighbor Information Base for IPv6',['../group__net__gnrc__ipv6__nib.html',1,'']]],
  ['infrared_20thermopile_20sensor_76',['TMP006/TMP007 Infrared Thermopile Sensor',['../group__drivers__tmp00x.html',1,'']]],
  ['infrared_20thermopile_20sensor_20driver_20compile_20configuration_77',['TMP006/TMP007 Infrared Thermopile Sensor driver compile configuration',['../group__drivers__tmp00x__config.html',1,'']]],
  ['infrastructure_78',['Layered PM Infrastructure',['../group__sys__pm__layered.html',1,'']]],
  ['infrastructure_79',['SUIT secure firmware OTA upgrade infrastructure',['../group__sys__suit.html',1,'']]],
  ['initialisation_80',['Initialisation',['../group__auto__init__saul.html',1,'SAUL Auto Initialisation'],['../group__drivers__saul__init__devs.html',1,'SAUL Device Initialisation']]],
  ['initialization_81',['Secure Element Driver Initialization',['../group__se__init.html',1,'']]],
  ['initialization_82',['initialization',['../group__sys__auto__init.html',1,'Auto-initialization'],['../group__drivers__periph__init.html',1,'Common peripheral initialization'],['../group__sys__auto__init__gnrc__netif.html',1,'GNRC netif drivers auto-initialization'],['../group__sys__auto__init__lwip__netif.html',1,'lwIP netif drivers auto-initialization'],['../group__sys__auto__init__multimedia.html',1,'Multimedia driver auto-initialization'],['../group__sys__auto__init__saul.html',1,'SAUL drivers auto-initialization']]],
  ['initialization_20compile_20configuration_83',['Core initialization compile configuration',['../group__core__init__config.html',1,'']]],
  ['initialization_20of_20usb_20device_20firmware_84',['Initialization of USB Device Firmware',['../group__sys__riotboot__usb__dfu.html',1,'']]],
  ['initialized_20modules_85',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['ink_20spi_20display_20driver_86',['Generic black/white e-paper/e-ink SPI display driver.',['../group__drivers__epd__bw__spi.html',1,'']]],
  ['instances_87',['C++ constructor guards for static instances',['../group__sys__cxx__ctor__guards.html',1,'']]],
  ['integer_20division_20functions_88',['Integer division functions',['../group__sys__div.html',1,'']]],
  ['integer_20math_20functions_89',['imath: Integer Math functions',['../group__sys__imath.html',1,'']]],
  ['integer_20mathematical_20statistics_20library_90',['Matstat - Integer mathematical statistics library',['../group__sys__matstat.html',1,'']]],
  ['integer_20operations_91',['Fractional integer operations',['../group__sys__frac.html',1,'']]],
  ['integration_92',['RIOT Integration',['../group__pkg__nimble__contrib.html',1,'']]],
  ['integration_93',['integration',['../group__sys__fatfs.html',1,'FatFs integration'],['../group__sys__littlefs.html',1,'littlefs integration'],['../group__sys__littlefs2.html',1,'littlefs v2 integration'],['../group__sys__lwext4.html',1,'lwEXT4 integration'],['../group__sys__fs__native.html',1,'native fs integration'],['../group__sys__spiffs.html',1,'SPIFFS integration']]],
  ['integration_20of_20the_20servo_20driver_94',['SAUL integration of the servo driver',['../group__drivers__servo__saul.html',1,'']]],
  ['interactive_20synchronization_95',['Test interactive synchronization',['../group__test__utils__interactive__sync.html',1,'']]],
  ['interface_96',['Interface',['../group__drivers__periph.html',1,'Peripheral Driver Interface'],['../group__drivers__soft__periph.html',1,'Soft Peripheral Driver Interface']]],
  ['interface_97',['interface',['../group__drivers__candev.html',1,'CAN device driver interface'],['../group__drivers__can__trx.html',1,'CAN transceiver interface'],['../group__cpu__cc2538__rfcore.html',1,'CC2538 RF core interface'],['../group__cpu__esp__common__esp__now.html',1,'ESP-NOW netdev interface'],['../group__cpu__esp__common__esp__wifi.html',1,'ESP-WiFi netdev interface'],['../group__cpu__esp32__esp__eth.html',1,'ESP32 Ethernet netdev interface'],['../group__cpu__esp8266__sdk.html',1,'ESP8266 SDK interface'],['../group__net__gnrc__netapi.html',1,'GNRC communication interface'],['../group__drivers__mcp47xx.html',1,'MCP47xx DAC with I2C interface'],['../group__drivers__nrf24l01p.html',1,'NRF24L01+ driver interface']]],
  ['interface_20api_98',['ESP-IDF Interface API',['../group__cpu__esp32__esp__idf__api.html',1,'']]],
  ['interface_20api_99',['Network interface API',['../group__net__gnrc__netif.html',1,'']]],
  ['interface_20configurations_100',['GNRC network interface configurations',['../group__net__gnrc__netif__conf.html',1,'']]],
  ['interface_20driver_101',['STM32 FMC/FSMC LCD low-level parallel interface driver',['../group__cpu__stm32__lcd__fmc.html',1,'']]],
  ['interface_20header_102',['Generic network interface header',['../group__net__gnrc__netif__hdr.html',1,'']]],
  ['interface_20implementation_103',['interface implementation',['../group__pkg__opendsme__dsmemessage.html',1,'DSME Message interface implementation.'],['../group__pkg__opendsme__dsmeplatform.html',1,'DSME Platform interface implementation.']]],
  ['interface_20mii_104',['Ethernet Media-Independent Interface (MII)',['../group__drivers__mii.html',1,'']]],
  ['interface_20on_20device_20level_105',['Packet interface on device level',['../group__net__packet.html',1,'']]],
  ['interface_20spi_106',['NXP QN908x Serial Peripheral Interface (SPI)',['../group__cpu__qn908x__spi.html',1,'']]],
  ['interface_20standard_107',['Nuclei MCU Software Interface Standard',['../group__pkg__nmsis__sdk.html',1,'']]],
  ['interfaces_108',['Network interfaces',['../group__net__netif.html',1,'']]],
  ['interfaces_20compile_20configurations_109',['Network interfaces compile configurations',['../group__net__netif__conf.html',1,'']]],
  ['internal_20flash_110',['Helpers to manipulate partitions (slots) on internal flash',['../group__sys__riotboot__slot.html',1,'']]],
  ['internal_20functions_111',['SX1261/2/8 and LLCC68 internal functions',['../group__drivers__sx126x__internal.html',1,'']]],
  ['internal_20temperature_20sensor_112',['EFM32 internal temperature sensor',['../group__cpu__efm32__drivers__coretemp.html',1,'']]],
  ['internals_113',['internals',['../group__sys__usb__board__reset__internal.html',1,'Board reset via USB CDC ACM internals'],['../group__sys__malloc__monitor__internals.html',1,'Heap Memory Usage Monitor internals']]],
  ['internet_20checksum_114',['Internet Checksum',['../group__net__inet__csum.html',1,'']]],
  ['internet_20of_20things_115',['Ultra-lightweight Javascript for Internet Of Things',['../group__pkg__jerryscript.html',1,'']]],
  ['interpreter_116',['uBASIC interpreter',['../group__pkg__ubasic.html',1,'']]],
  ['interrupt_20driver_117',['Power-and-interrupt driver',['../group__boards__common__silabs__drivers__pic.html',1,'']]],
  ['interval_20event_20timers_118',['Millisecond interval event timers',['../group__sys__evtimer.html',1,'']]],
  ['inverse_20semaphores_119',['inverse Semaphores',['../group__sys__sema__inv.html',1,'']]],
  ['io_120',['IO',['../group__sys__iolist.html',1,'iolist scatter / gather IO'],['../group__usbus__hid__io.html',1,'USBUS HID IO']]],
  ['io_20driver_121',['Disk IO Driver',['../group__drivers__diskio.html',1,'']]],
  ['io_20pio_122',['Programmable IO (PIO)',['../group__drivers__periph__pio.html',1,'']]],
  ['io1_20xplained_20extension_20board_123',['Atmel IO1 Xplained Extension board',['../group__drivers__io1__xplained.html',1,'']]],
  ['iolist_20scatter_20gather_20io_124',['iolist scatter / gather IO',['../group__sys__iolist.html',1,'']]],
  ['iot_125',['IoT',['../group__boards__arduino-nano-33-iot.html',1,'Arduino Nano 33 IoT'],['../group__boards__msbiot.html',1,'MSB-IoT']]],
  ['iot_20lab_20a8_20m3_20open_20node_126',['IoT-LAB A8 M3 open node',['../group__boards__iotlab-a8-m3.html',1,'']]],
  ['iot_20lab_20m3_20open_20node_127',['IoT-LAB M3 open node',['../group__boards__iotlab-m3.html',1,'']]],
  ['iot01a_128',['ST B-L475E-IOT01A',['../group__boards__b-l475e-iot01a.html',1,'']]],
  ['iot02a_129',['STM32 B-U585I-IOT02A',['../group__boards__b-u585i-iot02a.html',1,'']]],
  ['iotlab_20common_130',['IoTlab Common',['../group__boards__common__iotlab.html',1,'']]],
  ['ip_131',['SOME/IP',['../group__net__someip.html',1,'']]],
  ['ipc_132',['IPC',['../group__core__msg.html',1,'Messaging / IPC'],['../group__sys__pipe.html',1,'Pipe IPC']]],
  ['ipc_20extension_133',['Mailbox IPC extension',['../group__net__gnrc__netapi__mbox.html',1,'']]],
  ['iphc_134',['IPv6 header compression (IPHC)',['../group__net__gnrc__sixlowpan__iphc.html',1,'']]],
  ['ipso_20sensor_20base_20object_135',['IPSO Sensor base object',['../group__lwm2m__objects__ipso__sensor__base.html',1,'']]],
  ['ipso_20sensor_20base_20object_20compile_20configurations_136',['LwM2M IPSO Sensor base object compile configurations',['../group__lwm2m__objects__ipso__sensor__base__config.html',1,'']]],
  ['ipv4_137',['IPv4',['../group__net__ipv4.html',1,'']]],
  ['ipv4_20addresses_138',['IPv4 addresses',['../group__net__ipv4__addr.html',1,'']]],
  ['ipv4_20header_139',['IPv4 header',['../group__net__ipv4__hdr.html',1,'']]],
  ['ipv4_20ipv6_20sock_20api_140',['Raw IPv4/IPv6 sock API',['../group__net__sock__ip.html',1,'']]],
  ['ipv6_141',['IPv6',['../group__net__gnrc__ipv6.html',1,'IPv6'],['../group__net__ipv6.html',1,'IPv6'],['../group__net__gnrc__ipv6__nib.html',1,'Neighbor Information Base for IPv6']]],
  ['ipv6_20address_20blacklist_142',['IPv6 address blacklist',['../group__net__gnrc__ipv6__blacklist.html',1,'']]],
  ['ipv6_20address_20blacklisting_20compile_20configurations_143',['GNRC IPv6 address blacklisting compile configurations',['../group__net__gnrc__ipv6__blacklist__conf.html',1,'']]],
  ['ipv6_20address_20whitelist_144',['IPv6 address whitelist',['../group__net__gnrc__ipv6__whitelist.html',1,'']]],
  ['ipv6_20address_20whitelisting_20compile_20configurations_145',['GNRC IPv6 address whitelisting compile configurations',['../group__net__gnrc__ipv6__whitelist__conf.html',1,'']]],
  ['ipv6_20addresses_146',['IPv6 addresses',['../group__net__ipv6__addr.html',1,'']]],
  ['ipv6_20compile_20configurations_147',['GNRC IPv6 compile configurations',['../group__net__gnrc__ipv6__conf.html',1,'']]],
  ['ipv6_20destination_20and_20hop_20by_20hop_20options_148',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['ipv6_20dhcpv6_149',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['ipv6_20extension_20header_20compile_20configurations_150',['GNRC IPv6 extension header compile configurations',['../group__net__gnrc__ipv6__ext__conf.html',1,'']]],
  ['ipv6_20extension_20headers_151',['IPv6 extension headers',['../group__net__ipv6__ext.html',1,'IPv6 extension headers'],['../group__net__gnrc__ipv6__ext.html',1,'IPv6 extension headers.']]],
  ['ipv6_20fragmentation_20extension_152',['IPv6 fragmentation extension',['../group__net__ipv6__ext__frag.html',1,'IPv6 fragmentation extension'],['../group__net__gnrc__ipv6__ext__frag.html',1,'Support for IPv6 fragmentation extension']]],
  ['ipv6_20header_153',['IPv6 header',['../group__net__ipv6__hdr.html',1,'']]],
  ['ipv6_20header_20compression_20iphc_154',['IPv6 header compression (IPHC)',['../group__net__gnrc__sixlowpan__iphc.html',1,'']]],
  ['ipv6_20header_20definitions_155',['IPv6 header definitions',['../group__net__gnrc__ipv6__hdr.html',1,'']]],
  ['ipv6_20neighbor_20discovery_156',['IPv6 neighbor discovery',['../group__net__ndp.html',1,'']]],
  ['ipv6_20neighbor_20discovery_20v2_157',['IPv6 neighbor discovery (v2)',['../group__net__gnrc__ndp.html',1,'']]],
  ['ipv6_20nib_20compile_20configurations_158',['GNRC IPv6 NIB compile configurations',['../group__net__gnrc__ipv6__nib__conf.html',1,'']]],
  ['ipv6_20option_20extension_20headers_159',['Support for IPv6 option extension headers',['../group__net__gnrc__ipv6__ext__opt.html',1,'']]],
  ['ipv6_20over_20x_160',['Stack-independent helpers for IPv6 over X',['../group__net__l2util.html',1,'']]],
  ['ipv6_20routing_20header_20extension_161',['IPv6 routing header extension',['../group__net__ipv6__ext__rh.html',1,'IPv6 routing header extension'],['../group__net__gnrc__ipv6__ext__rh.html',1,'Support for IPv6 routing header extension']]],
  ['ipv6_20sock_20api_162',['Raw IPv4/IPv6 sock API',['../group__net__sock__ip.html',1,'']]],
  ['ir_20nec_20remote_20receiver_163',['IR NEC Remote receiver',['../group__drivers__ir__nec.html',1,'']]],
  ['ir_20uwb_20transceiver_20s_164',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['irq_20disable_20debug_20helper_165',['IRQ Disable Debug helper',['../group__debug__irq__disable.html',1,'']]],
  ['irq_20handling_166',['IRQ Handling',['../group__core__irq.html',1,'']]],
  ['irq_20support_20in_20peripheral_20gpio_20low_20level_20api_167',['IRQ Support in Peripheral GPIO Low-Level API',['../group__drivers__periph__gpio__ll__irq.html',1,'']]],
  ['isl29020_20light_20sensor_168',['ISL29020 light sensor',['../group__drivers__isl29020.html',1,'']]],
  ['isl29020_20light_20sensor_20driver_20compile_20configuration_169',['ISL29020 light sensor driver compile configuration',['../group__drivers__isl29020__config.html',1,'']]],
  ['isl29125_20rgb_20light_20sensor_170',['ISL29125 RGB light sensor',['../group__drivers__isl29125.html',1,'']]],
  ['iso_20transport_20protocol_20over_20can_171',['ISO transport protocol over CAN',['../group__sys__can__isotp.html',1,'']]],
  ['isr_20pipe_172',['ISR Pipe',['../group__isr__pipe.html',1,'']]],
  ['isr_20pipe_173',['Read timeouts with ISR pipe',['../group__isr__pipe__read__timeout.html',1,'']]],
  ['itg320x_203_20axis_20gyroscope_174',['ITG320X 3-axis gyroscope',['../group__drivers__itg320x.html',1,'']]],
  ['itsybitsy_20m4_175',['Adafruit-Itsybitsy-M4',['../group__boards__adafruit-itsybitsy-m4.html',1,'']]],
  ['itsybitsy_20nrf52_176',['Adafruit-Itsybitsy-nRF52',['../group__boards__adafruit-itsybitsy-nrf52.html',1,'']]]
];
