var searchData=
[
  ['v_20board_0',['V board',['../group__boards__seeedstudio-gd32.html',1,'SeeedStudio GD32 RISC-V board'],['../group__boards__hifive1.html',1,'SiFive HiFive1 RISC-V board'],['../group__boards__hifive1b.html',1,'SiFive HiFive1b RISC-V board']]],
  ['v_20common_1',['RISC-V common',['../group__cpu__riscv__common.html',1,'']]],
  ['v1_200_20board_2',['ESP32-Ethernet-Kit V1.0 Board',['../group__boards__esp32__esp-ethernet-kit-v1__0.html',1,'']]],
  ['v1_201_20board_3',['ESP32-Ethernet-Kit V1.1 Board',['../group__boards__esp32__esp-ethernet-kit-v1__1.html',1,'']]],
  ['v1_202_4',['Waspmote PRO v1.2',['../group__boards__waspmote-pro.html',1,'']]],
  ['v1_202_20board_5',['ESP32-Ethernet-Kit V1.2 Board',['../group__boards__esp32__esp-ethernet-kit-v1__2.html',1,'']]],
  ['v2_6',['v2',['../group__boards__microbit__v2.html',1,'BBC micro:bit v2'],['../group__net__gnrc__ndp.html',1,'IPv6 neighbor discovery (v2)']]],
  ['v2_20boards_7',['Heltec WiFi LoRa 32 V2 boards',['../group__boards__esp32__heltec-lora32-v2.html',1,'']]],
  ['v2_20integration_8',['littlefs v2 integration',['../group__sys__littlefs2.html',1,'']]],
  ['v2_20x_20y_20file_20system_9',['littlefs v2.x.y file system',['../group__pkg__littlefs2.html',1,'']]],
  ['v3_10',['ESP-WROVER-KIT V3',['../group__boards__esp32__esp-wrover-kit.html',1,'']]],
  ['values_20for_20riotboot_11',['Magic values for riotboot',['../group__sys__riotboot__magic.html',1,'']]],
  ['variable_12',['Condition Variable',['../group__core__sync__cond.html',1,'']]],
  ['vcdiff_13',['Tiny VCDIFF',['../group__pkg__tinyvcdiff.html',1,'']]],
  ['vcnl4010_20vcnl4020_20vcnl4040_20proximity_20and_20ambient_20light_20sensors_14',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['vcnl4020_20vcnl4040_20proximity_20and_20ambient_20light_20sensors_15',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['vcnl4040_20proximity_20and_20ambient_20light_20sensors_16',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['veml6070_20uv_20sensor_17',['VEML6070 UV sensor',['../group__drivers__veml6070.html',1,'']]],
  ['vendor_20driver_20package_18',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['vendor_20library_20for_20efm_20efr_20ezr32_20mcus_19',['Vendor library for EFM/EFR/EZR32 MCUs',['../group__pkg__gecko__sdk.html',1,'']]],
  ['version_20',['ztimer 64bit version',['../group__sys__ztimer64.html',1,'']]],
  ['version_201_21',['LimiFrog Version 1',['../group__boards__limifrog-v1.html',1,'']]],
  ['vfs_20helper_20functions_22',['VFS helper functions',['../group__sys__vfs__util.html',1,'']]],
  ['vfs_20layer_23',['Virtual File System (VFS) layer',['../group__sys__vfs.html',1,'']]],
  ['vfs_20storage_20backend_24',['riotboot vfs storage backend',['../group__sys__suit__storage__vfs.html',1,'']]],
  ['vfs_20transport_25',['SUIT secure firmware OTA VFS transport',['../group__sys__suit__transport__vfs.html',1,'']]],
  ['vfs_5fauto_5fformat_26',['vfs_auto_format',['../group__pseudomodule__vfs__auto__format.html',1,'']]],
  ['vfs_5fauto_5fmount_27',['vfs_auto_mount',['../group__pseudomodule__vfs__auto__mount.html',1,'']]],
  ['vfs_5fdefault_28',['vfs_default',['../group__pseudomodule__vfs__default.html',1,'']]],
  ['via_20ethos_29',['STDIO via ethos',['../group__drivers__ethos__stdio.html',1,'']]],
  ['via_20slip_30',['STDIO via SLIP',['../group__drivers__slipdev__stdio.html',1,'']]],
  ['via_20usb_20cdc_20acm_31',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['via_20usb_20cdc_20acm_20internals_32',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['virtual_20file_20system_20vfs_20layer_33',['Virtual File System (VFS) layer',['../group__sys__vfs.html',1,'']]],
  ['virtual_20reassembly_20buffer_34',['Virtual reassembly buffer',['../group__net__gnrc__sixlowpan__frag__vrb.html',1,'']]],
  ['vl6180x_20ranging_20and_20ambient_20light_20sensing_20als_20module_35',['VL6180X Ranging and Ambient Light Sensing (ALS) module',['../group__drivers__vl6180x.html',1,'']]],
  ['volatile_20accesses_36',['Helpers for volatile accesses',['../group__sys__atomic__utils__volatile.html',1,'']]],
  ['volatile_20ram_37',['Non-volatile RAM',['../group__drivers__nvram.html',1,'']]],
  ['voltage_38',['Voltage',['../group__lwm2m__objects__voltage.html',1,'']]],
  ['voltage_20sensor_20object_20compile_20configurations_39',['LwM2M Voltage Sensor object compile configurations',['../group__lwm2m__objects__voltage__config.html',1,'']]]
];
