var searchData=
[
  ['p_20l496g_20cell02_0',['ST P-L496G-CELL02',['../group__boards__p-l496g-cell02.html',1,'']]],
  ['p_20nucleo_20wb55_1',['STM32 p-nucleo-wb55',['../group__boards__p-nucleo-wb55.html',1,'']]],
  ['p2p_20routes_20in_20llns_2',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['package_3',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['package_4',['package',['../group__lwm2m__platform.html',1,'Platform adaption for Wakaama package'],['../group__pkg__tinyusb.html',1,'TinyUSB package']]],
  ['package_20compile_20configurations_5',['Mbed TLS package compile configurations',['../group__pkg__mbedtls__config.html',1,'']]],
  ['package_20for_20i2c_20spi_20bme680_20sensor_6',['Driver package for I2C/SPI BME680 sensor',['../group__pkg__driver__bme680.html',1,'']]],
  ['packages_7',['Packages',['../group__pkg.html',1,'']]],
  ['packet_8',['Packet',['../group__net__ntp__packet.html',1,'NTP Packet'],['../group__net__gnrc__pkt.html',1,'Packet']]],
  ['packet_20buffer_9',['Packet buffer',['../group__net__gnrc__pktbuf.html',1,'']]],
  ['packet_20interface_20on_20device_20level_10',['Packet interface on device level',['../group__net__packet.html',1,'']]],
  ['packet_20queue_11',['Packet queue',['../group__net__gnrc__pktqueue.html',1,'']]],
  ['packet_20queue_20for_20gnrc_12',['Priority packet queue for GNRC',['../group__net__gnrc__priority__pktqueue.html',1,'']]],
  ['packet_20statistics_20for_20rpl_13',['Packet statistics for RPL',['../group__net__netstats__rpl.html',1,'']]],
  ['packet_20statistics_20per_20module_14',['Packet statistics per module',['../group__net__netstats.html',1,'']]],
  ['packets_15',['Dump Network Packets',['../group__net__gnrc__pktdump.html',1,'']]],
  ['page_20driver_16',['Flash page driver',['../group__drivers__periph__flashpage.html',1,'']]],
  ['paho_20mqtt_20framework_17',['PAHO MQTT framework',['../group__pkg__paho__mqtt.html',1,'']]],
  ['pandora_18',['Alientek Pandora',['../group__boards__alientek-pandora.html',1,'']]],
  ['panel_20driver_19',['FocalTech FT5x06 touch panel driver',['../group__drivers__ft5x06.html',1,'']]],
  ['paper_20e_20ink_20spi_20display_20driver_20',['Generic black/white e-paper/e-ink SPI display driver.',['../group__drivers__epd__bw__spi.html',1,'']]],
  ['parallel_20interface_20driver_21',['STM32 FMC/FSMC LCD low-level parallel interface driver',['../group__cpu__stm32__lcd__fmc.html',1,'']]],
  ['parser_22',['parser',['../group__sys__uri__parser.html',1,'A minimal, non-destructive URI parser'],['../group__pkg__yxml.html',1,'Yxml XML parser']]],
  ['parser_20and_20composer_23',['DNS message parser and composer',['../group__net__dns__msg.html',1,'']]],
  ['parser_20library_24',['parser library',['../group__pkg__minmea.html',1,'GPS parser library'],['../group__pkg__jsmn.html',1,'JSON parser library'],['../group__pkg__libbase58.html',1,'JSON parser library']]],
  ['parsing_20and_20composition_20configuration_25',['DNS message parsing and composition configuration',['../group__net__dns__msg__conf.html',1,'']]],
  ['particle_20argon_26',['Particle Argon',['../group__boards__particle-argon.html',1,'']]],
  ['particle_20boron_27',['Particle Boron',['../group__boards__particle-boron.html',1,'']]],
  ['particle_20mesh_20common_28',['Particle Mesh common',['../group__boards__common__particle-mesh.html',1,'']]],
  ['particle_20xenon_29',['Particle Xenon',['../group__boards__particle-xenon.html',1,'']]],
  ['particulate_20matter_20sensor_30',['Particulate Matter Sensor',['../group__drivers__hm330x.html',1,'HM330X Laser Particulate Matter Sensor'],['../group__drivers__sps30.html',1,'SPS30 Particulate Matter Sensor']]],
  ['partitions_20slots_20on_20internal_20flash_31',['Helpers to manipulate partitions (slots) on internal flash',['../group__sys__riotboot__slot.html',1,'']]],
  ['payload_20lpp_32',['Cayenne Low Power Payload (LPP)',['../group__pkg__cayenne-lpp.html',1,'']]],
  ['pbkdf2_33',['PBKDF2',['../group__sys__hashes__pbkdf2.html',1,'']]],
  ['pca9633_20i2c_20pwm_20controller_34',['PCA9633 I2C PWM controller',['../group__drivers__pca9633.html',1,'']]],
  ['pca9685_20i2c_20pwm_20controller_35',['PCA9685 I2C PWM controller',['../group__drivers__pca9685.html',1,'']]],
  ['pcd8544_20lcd_20driver_36',['PCD8544 LCD driver',['../group__drivers__pcd8544.html',1,'']]],
  ['pcf857x_20i2c_20i_20o_20expanders_37',['PCF857X I2C I/O expanders',['../group__drivers__pcf857x.html',1,'']]],
  ['per_20module_38',['Packet statistics per module',['../group__net__netstats.html',1,'']]],
  ['periph_20ptp_20backend_39',['ztimer periph/ptp backend',['../group__sys__ztimer__periph__ptp.html',1,'']]],
  ['periph_20rtc_20backend_40',['ztimer periph/rtc backend',['../group__sys__ztimer__periph__rtc.html',1,'']]],
  ['periph_20rtt_20backend_41',['ztimer periph/rtt backend',['../group__sys__ztimer__periph__rtt.html',1,'']]],
  ['periph_20timer_20backend_42',['ztimer periph/timer backend',['../group__sys__ztimer__periph__timer.html',1,'']]],
  ['periph_5ftimer_5fperiodic_20based_20servo_20driver_43',['periph_timer_periodic based servo driver',['../group__drivers__servo__timer.html',1,'']]],
  ['peripheral_44',['peripheral',['../group__cpu__sam0__common__eth.html',1,'sam0 Ethernet peripheral'],['../group__cpu__sam0__common__usb.html',1,'sam0 USB peripheral'],['../group__cpu__stm32__usbdev.html',1,'stm32 USB OTG FS/HS peripheral']]],
  ['peripheral_20compile_20time_20configurations_45',['USB peripheral compile time configurations',['../group__usb__conf.html',1,'']]],
  ['peripheral_20configurations_46',['Soft Peripheral Configurations',['../group__config__drivers__soft__periph.html',1,'']]],
  ['peripheral_20driver_47',['STM32 FMC/FSMC peripheral driver',['../group__cpu__stm32__periph__fmc.html',1,'']]],
  ['peripheral_20driver_20interface_48',['Peripheral Driver Interface',['../group__drivers__periph.html',1,'Peripheral Driver Interface'],['../group__drivers__soft__periph.html',1,'Soft Peripheral Driver Interface']]],
  ['peripheral_20ethernet_20driver_49',['STM32 Peripheral Ethernet Driver',['../group__stm32__eth.html',1,'']]],
  ['peripheral_20gpio_20low_20level_20api_50',['IRQ Support in Peripheral GPIO Low-Level API',['../group__drivers__periph__gpio__ll__irq.html',1,'']]],
  ['peripheral_20implementation_51',['NRF usb peripheral implementation',['../group__cpu__nrf52__nrfusb.html',1,'']]],
  ['peripheral_20initialization_52',['Common peripheral initialization',['../group__drivers__periph__init.html',1,'']]],
  ['peripheral_20interface_20spi_53',['NXP QN908x Serial Peripheral Interface (SPI)',['../group__cpu__qn908x__spi.html',1,'']]],
  ['peripheral_20memory_20map_54',['peripheral memory map',['../group__cpu__specific__peripheral__memory__map.html',1,'TI CC26x0/CC13x0 peripheral memory map'],['../group__cpu__cc26x2__cc13x2__peripheral__memory__map.html',1,'TI CC26x2, CC13x2 peripheral memory map']]],
  ['peripherals_55',['Atmel ATxmega MCU Peripherals',['../group__cpu__atxmega__periph.html',1,'']]],
  ['persistent_20storage_20api_56',['PSA Crypto Persistent Storage API',['../group__sys__psa__crypto__pers__stor.html',1,'']]],
  ['ph_20oem_20sensor_20device_20driver_57',['pH OEM sensor device driver',['../group__drivers__ph__oem.html',1,'']]],
  ['phy_58',['PHY',['../group__drivers__at86rf215__fsk.html',1,'AT86RF215 MR-FSK PHY'],['../group__drivers__at86rf215__oqpsk.html',1,'AT86RF215 MR-O-QPSK PHY'],['../group__drivers__at86rf215__ofdm.html',1,'AT86RF215 MR-OFDM PHY']]],
  ['phydat_59',['Phydat',['../group__sys__phydat.html',1,'Phydat'],['../group__sys__senml__phydat.html',1,'SenML Phydat']]],
  ['phynode_20kw41z_60',['PhyNODE KW41Z',['../group__boards__phynode-kw41z.html',1,'']]],
  ['phytec_20reel_20board_61',['Phytec reel board',['../group__boards__reel.html',1,'']]],
  ['phywave_20kw22_20board_62',['phyWAVE-KW22 Board',['../group__boards__pba-d-01-kw2x.html',1,'']]],
  ['pi_20pico_63',['Raspberry Pi Pico',['../group__boards__rpi__pico.html',1,'']]],
  ['pi_20pico_20w_64',['Raspberry Pi Pico W',['../group__boards__rpi__pico__w.html',1,'']]],
  ['pico_65',['Raspberry Pi Pico',['../group__boards__rpi__pico.html',1,'']]],
  ['pico_20w_66',['Raspberry Pi Pico W',['../group__boards__rpi__pico__w.html',1,'']]],
  ['pin_20control_20for_20debugging_20profiling_67',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['pinetime_68',['PineTime',['../group__boards__pinetime.html',1,'']]],
  ['pins_69',['pins',['../group__cpu__stm32__wl__debug__subghz__radio.html',1,'STM32WL Sub-GHz Radio debug pins'],['../group__cpu__stm32__wl__debug__subghz__spi.html',1,'STM32WL Sub-GHz SPI debug pins']]],
  ['pio_70',['Programmable IO (PIO)',['../group__drivers__periph__pio.html',1,'']]],
  ['pio_20i2c_20program_71',['PIO I2C program',['../group__drivers__periph__pio__i2c.html',1,'']]],
  ['pipe_72',['ISR Pipe',['../group__isr__pipe.html',1,'']]],
  ['pipe_73',['Read timeouts with ISR pipe',['../group__isr__pipe__read__timeout.html',1,'']]],
  ['pipe_20ipc_74',['Pipe IPC',['../group__sys__pipe.html',1,'']]],
  ['pir_20motion_20sensor_75',['PIR Motion Sensor',['../group__drivers__pir.html',1,'']]],
  ['pir_20motion_20sensor_20driver_20compile_20configuration_76',['PIR Motion Sensor driver compile configuration',['../group__drivers__pir__config.html',1,'']]],
  ['pk6068a_20starter_20kit_77',['Silicon Labs xG23-PK6068A starter kit',['../group__boards__xg23-pk6068a.html',1,'']]],
  ['pktbuf_20compile_20configurations_78',['GNRC PKTBUF compile configurations',['../group__net__gnrc__pktbuf__conf.html',1,'']]],
  ['pktdump_20compile_20configurations_79',['GNRC PKTDUMP compile configurations',['../group__net__gnrc__pktdump__conf.html',1,'']]],
  ['plain_2064bit_20carithmetic_80',['plain 64bit carithmetic',['../group__sys__ztimer__convert__muldiv64.html',1,'']]],
  ['plain_20text_81',['Test result output plain text',['../group__test__utils__result__output__txt.html',1,'']]],
  ['platform_20adaption_82',['Wakaama LwM2M platform adaption',['../group__lwm2m__platform__conf.html',1,'']]],
  ['platform_20adaption_20for_20wakaama_20package_83',['Platform adaption for Wakaama package',['../group__lwm2m__platform.html',1,'']]],
  ['platform_20fixed_20point_20maths_20library_84',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['platform_20independent_20access_20to_20architecture_85',['Platform-independent access to architecture',['../group__sys__architecture.html',1,'']]],
  ['platform_20interface_20implementation_86',['DSME Platform interface implementation.',['../group__pkg__opendsme__dsmeplatform.html',1,'']]],
  ['player_87',['DFPlayer Mini MP3 Player',['../group__drivers__dfplayer.html',1,'']]],
  ['plus_88',['ESP32-S3 WT32-SC01 Plus',['../group__boards__esp32s3__wt32__sc01__plus.html',1,'']]],
  ['pm_20infrastructure_89',['Layered PM Infrastructure',['../group__sys__pm__layered.html',1,'']]],
  ['pm_20sensor_20driver_20compile_20configuration_90',['SPS30 PM Sensor driver compile configuration',['../group__drivers__SPS30__config.html',1,'']]],
  ['pmp_5fnoexec_5fram_91',['pmp_noexec_ram',['../group__pseudomodule__pmp__noexec__ram.html',1,'']]],
  ['pn532_20nfc_20radio_20driver_20compile_20configuration_92',['PN532 NFC Radio driver compile configuration',['../group__drivers__pn532__config.html',1,'']]],
  ['pn532_20nfc_20reader_93',['PN532 NFC Reader',['../group__drivers__pn532.html',1,'']]],
  ['point_20maths_20library_94',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['point_20protocol_20header_95',['Point-to-Point Protocol Header',['../group__net__ppphdr.html',1,'']]],
  ['point_20protocol_20ppp_20data_20link_20layer_96',['Point-to-Point Protocol (PPP) Data Link Layer',['../group__net__ppp.html',1,'']]],
  ['point_20to_20point_20protocol_20header_97',['Point-to-Point Protocol Header',['../group__net__ppphdr.html',1,'']]],
  ['point_20to_20point_20protocol_20ppp_20data_20link_20layer_98',['Point-to-Point Protocol (PPP) Data Link Layer',['../group__net__ppp.html',1,'']]],
  ['pointer_20compression_99',['Pointer Compression',['../group__sys__util__zptr.html',1,'']]],
  ['pointer_20tagging_100',['Helpers for pointer tagging',['../group__sys__ptrtag.html',1,'']]],
  ['points_101',['points',['../group__net__wifi__scan__list.html',1,'List of scanned WiFis access points'],['../group__net__l2scanlist.html',1,'Scan List - List of wireless access points']]],
  ['poly1305_102',['poly1305',['../group__sys__crypto__poly1305.html',1,'']]],
  ['port_103',['MicroPython RIOT port',['../group__pkg__micropython.html',1,'']]],
  ['port_20ranges_104',['IANA Port Ranges',['../group__net__iana__portrange.html',1,'']]],
  ['ported_20to_20riot_105',['Lua ported to RIOT',['../group__pkg__lua.html',1,'']]],
  ['porting_20layer_106',['Porting layer',['../group__pkg__lwip__sys.html',1,'']]],
  ['posix_20select_107',['POSIX select',['../group__posix__select.html',1,'']]],
  ['posix_20semaphores_108',['POSIX semaphores',['../group__posix__semaphore.html',1,'']]],
  ['posix_20sockets_109',['POSIX sockets',['../group__posix__sockets.html',1,'']]],
  ['posix_20threads_110',['POSIX threads',['../group__pthread.html',1,'']]],
  ['posix_20wrapper_20compile_20configurations_111',['POSIX wrapper compile configurations',['../group__config__posix.html',1,'']]],
  ['posix_20wrapper_20for_20riot_112',['POSIX wrapper for RIOT',['../group__posix.html',1,'']]],
  ['power_20and_20interrupt_20driver_113',['Power-and-interrupt driver',['../group__boards__common__silabs__drivers__pic.html',1,'']]],
  ['power_20management_114',['Power Management',['../group__drivers__periph__pm.html',1,'']]],
  ['power_20monitor_115',['power monitor',['../group__drivers__ina2xx.html',1,'INA2XX current/power monitor'],['../group__drivers__ina3221.html',1,'INA3221 current/power monitor']]],
  ['power_20payload_20lpp_116',['Cayenne Low Power Payload (LPP)',['../group__pkg__cayenne-lpp.html',1,'']]],
  ['power_20rtc_20memory_117',['Low-Power RTC Memory',['../group__drivers__periph__rtc__mem.html',1,'']]],
  ['power_20supply_20drivers_118',['Power Supply Drivers',['../group__drivers__power.html',1,'']]],
  ['ppp_20data_20link_20layer_119',['Point-to-Point Protocol (PPP) Data Link Layer',['../group__net__ppp.html',1,'']]],
  ['prefix_20list_120',['Prefix list',['../group__net__gnrc__ipv6__nib__pl.html',1,'']]],
  ['pressure_20and_20humidity_20sensor_121',['BMP280/BME280 temperature, pressure and humidity sensor',['../group__drivers__bmx280.html',1,'']]],
  ['pressure_20gas_20sensor_122',['BME680 Temperature/Humidity/Pressure/Gas sensor',['../group__drivers__bme680.html',1,'']]],
  ['pressure_20sensor_123',['MPL3115A2 Pressure Sensor',['../group__drivers__mpl3115a2.html',1,'']]],
  ['pressure_20sensor_124',['pressure sensor',['../group__drivers__bmp180.html',1,'BMP180 temperature and pressure sensor'],['../group__drivers__hsc.html',1,'HSC temperature and pressure sensor'],['../group__drivers__sdp3x.html',1,'SDP3x temperature and differential pressure sensor']]],
  ['pressure_20sensor_20driver_20compile_20configuration_125',['MPL3115A2 Pressure Sensor driver compile configuration',['../group__drivers__mpl3115a2__config.html',1,'']]],
  ['pressure_20sensors_20driver_126',['LPS331AP/LPS25HB/LPS22HB Pressure Sensors Driver',['../group__drivers__lpsxxx.html',1,'']]],
  ['priority_20packet_20queue_20for_20gnrc_127',['Priority packet queue for GNRC',['../group__net__gnrc__priority__pktqueue.html',1,'']]],
  ['pro_128',['Pro',['../group__boards__atmega256rfr2-xpro.html',1,'Atmega256RFR2 Xplained Pro'],['../group__boards__samd20-xpro.html',1,'Atmel SAM D20 Xplained Pro'],['../group__boards__samd21-xpro.html',1,'Atmel SAM D21 Xplained Pro'],['../group__boards__saml21-xpro.html',1,'Atmel SAM L21 Xplained Pro'],['../group__boards__samr21-xpro.html',1,'Atmel SAM R21 Xplained Pro'],['../group__boards__samr30-xpro.html',1,'Atmel SAM R30 Xplained Pro'],['../group__boards__same54-xpro.html',1,'Microchip SAM E54 Xplained Pro'],['../group__boards__samr34-xpro.html',1,'Microchip SAM R34 Xplained Pro'],['../group__boards__saml10-xpro.html',1,'Microchip SAML10 Xplained Pro'],['../group__boards__saml11-xpro.html',1,'Microchip SAML11 Xplained Pro'],['../group__boards__esp32__wemos-lolin-d32-pro.html',1,'Wemos LOLIN D32 Pro']]],
  ['pro_20board_129',['ATxmega-A1U Xplained Pro board',['../group__boards__atxmega-a1u-xpro.html',1,'']]],
  ['pro_20development_20kit_130',['Seeeduino Arch Pro development kit',['../group__boards__seeduino__arch-pro.html',1,'']]],
  ['pro_20v1_202_131',['Waspmote PRO v1.2',['../group__boards__waspmote-pro.html',1,'']]],
  ['processing_132',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['processing_133',['processing',['../group__test__utils__netdev__eth__minimal.html',1,'Minimal netdev Ethernet device processing'],['../group__test__utils__netdev__ieee802154__minimal.html',1,'Minimal netdev IEEE 802.15.4 device processing']]],
  ['processor_134',['Processor',['../group__sys__bhp.html',1,'Bottom Half Processor'],['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['processor_135',['URI template processor',['../group__sys__ut__process.html',1,'']]],
  ['profiling_136',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['program_137',['PIO I2C program',['../group__drivers__periph__pio__i2c.html',1,'']]],
  ['programmable_20io_20pio_138',['Programmable IO (PIO)',['../group__drivers__periph__pio.html',1,'']]],
  ['progress_20bar_139',['A terminal progress bar',['../group__sys__progress__bar.html',1,'']]],
  ['pros3_20board_140',['ESP32 ProS3 Board',['../group__boards__esp32s3__pros3.html',1,'']]],
  ['protector_141',['Stack Smashing Protector',['../group__sys__ssp.html',1,'']]],
  ['protocol_142',['Protocol',['../group__sys__riotboot__serial.html',1,'Serial Bootloader Protocol'],['../group__net__sntp.html',1,'Simple Network Time Protocol'],['../group__net__zep.html',1,'ZigBee Encapsulation Protocol']]],
  ['protocol_20arp_143',['Address resolution protocol (ARP)',['../group__net__arp.html',1,'']]],
  ['protocol_20buffers_20library_144',['small Protocol Buffers library',['../group__pkg__nanopb.html',1,'']]],
  ['protocol_20for_20ipv6_20dhcpv6_145',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['protocol_20header_146',['Point-to-Point Protocol Header',['../group__net__ppphdr.html',1,'']]],
  ['protocol_20numbers_147',['Protocol Numbers',['../group__net__protnum.html',1,'']]],
  ['protocol_20over_20can_148',['ISO transport protocol over CAN',['../group__sys__can__isotp.html',1,'']]],
  ['protocol_20ppp_20data_20link_20layer_149',['Point-to-Point Protocol (PPP) Data Link Layer',['../group__net__ppp.html',1,'']]],
  ['protocol_20registry_150',['Network protocol registry',['../group__net__gnrc__netreg.html',1,'']]],
  ['protocol_20type_151',['gnrc_nettype: Protocol type',['../group__net__gnrc__nettype.html',1,'']]],
  ['prototype_20a_152',['RE-Mote Prototype A',['../group__boards__remote-pa.html',1,'']]],
  ['provided_20by_20most_20libcs_153',['endian conversions as provided by most libcs',['../group__sys__endian.html',1,'']]],
  ['provider_154',['IEEE EUI-48/64 provider',['../group__net__eui__provider.html',1,'']]],
  ['proximity_20and_20ambient_20light_20sensors_155',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['proximity_20and_20ambient_20light_20sensors_156',['APDS99XX proximity and ambient light sensors',['../group__drivers__apds99xx.html',1,'']]],
  ['proximity_20sensors_157',['Si1145/6/7 UV/Ambient light/Proximity sensors',['../group__drivers__si114x.html',1,'']]],
  ['proxy_158',['GCoAP Forward Proxy',['../group__net__gcoap__forward__proxy.html',1,'']]],
  ['proxy_20thread_159',['GCoAP Forward Proxy Thread',['../group__net__gcoap__forward__proxy__thread.html',1,'']]],
  ['ps_160',['PS',['../group__sys__ps.html',1,'']]],
  ['psa_20crypto_20algorithm_20dispatcher_161',['PSA Crypto Algorithm Dispatcher',['../group__sys__psa__crypto__alg__disp.html',1,'']]],
  ['psa_20crypto_20key_20slot_20management_162',['PSA Crypto Key Slot Management',['../group__sys__psa__crypto__slot__mgmt.html',1,'']]],
  ['psa_20crypto_20location_20dispatcher_163',['PSA Crypto Location Dispatcher',['../group__sys__psa__crypto__loc__disp.html',1,'']]],
  ['psa_20crypto_20persistent_20storage_20api_164',['PSA Crypto Persistent Storage API',['../group__sys__psa__crypto__pers__stor.html',1,'']]],
  ['psa_20crypto_20se_20management_165',['PSA Crypto SE Management',['../group__psa__crypto__se__mgmt.html',1,'']]],
  ['psa_20crypto_20secure_20element_20wrapper_166',['PSA Crypto Secure Element Wrapper',['../group__sys__psa__crypto__se__driver.html',1,'']]],
  ['psa_20cryptographic_20api_167',['PSA Cryptographic API',['../group__sys__psa__crypto.html',1,'']]],
  ['psa_20keys_20in_20cbor_168',['Module for encoding PSA keys in CBOR',['../group__sys__psa__crypto__cbor__encoder.html',1,'']]],
  ['psa_20wrapper_20functions_3a_20cipher_169',['PSA Wrapper Functions: Cipher',['../group__sys__psa__crypto__cipher.html',1,'']]],
  ['psa_20wrapper_20functions_3a_20ecc_170',['PSA Wrapper Functions: ECC',['../group__sys__psa__crypto__ecc.html',1,'']]],
  ['psa_20wrapper_20functions_3a_20hashes_171',['PSA Wrapper Functions: Hashes',['../group__sys__psa__crypto__hashes.html',1,'']]],
  ['psa_20wrapper_20functions_3a_20mac_172',['PSA Wrapper Functions: MAC',['../group__sys__psa__crypto__mac.html',1,'']]],
  ['pseudomodules_173',['Generic pseudomodules',['../group__pseudomodules.html',1,'']]],
  ['ptp_20backend_174',['ztimer periph/ptp backend',['../group__sys__ztimer__periph__ptp.html',1,'']]],
  ['ptp_20clock_175',['PTP-Clock',['../group__drivers__periph__ptp.html',1,'']]],
  ['puf_176',['SRAM PUF',['../group__sys__puf__sram.html',1,'']]],
  ['pulse_20counter_177',['Pulse counter',['../group__drivers__pulse__counter.html',1,'']]],
  ['purpose_20i_20o_178',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['purpose_20timer_179',['CC2538 General Purpose Timer',['../group__cpu__cc2538__gptimer.html',1,'']]],
  ['puts_20log_20module_180',['log_printfnoformat: puts log module',['../group__sys__log__printfnoformat.html',1,'']]],
  ['pwm_181',['PWM',['../group__cpu__kinetis__pwm.html',1,'Kinetis PWM'],['../group__drivers__periph__pwm.html',1,'PWM']]],
  ['pwm_20based_20servo_20driver_182',['PWM based servo driver',['../group__drivers__servo__pwm.html',1,'']]],
  ['pwm_20controller_183',['PWM controller',['../group__drivers__pca9633.html',1,'PCA9633 I2C PWM controller'],['../group__drivers__pca9685.html',1,'PCA9685 I2C PWM controller']]],
  ['pybadge_184',['Adafruit PyBadge',['../group__boards__adafruit-pybadge.html',1,'']]],
  ['pyboard_185',['pyboard',['../group__boards__pyboard.html',1,'']]]
];
