var searchData=
[
  ['a_0',['A',['../group__boards__remote-pa.html',1,'RE-Mote Prototype A'],['../group__boards__remote-reva.html',1,'RE-Mote Revision A']]],
  ['a_20congestion_20control_20framework_1',['CongURE - A Congestion control framework',['../group__sys__congure.html',1,'']]],
  ['a_20ctuator_20u_20ber_20l_20ayer_2',['[S]ensor [A]ctuator [U]ber [L]ayer',['../group__drivers__saul.html',1,'']]],
  ['a_20minimal_20non_20destructive_20uri_20parser_3',['A minimal, non-destructive URI parser',['../group__sys__uri__parser.html',1,'']]],
  ['a_20rtt_4',['RTC emulation on top of a RTT',['../group__drivers__rtt__rtc.html',1,'']]],
  ['a_20terminal_20progress_20bar_5',['A terminal progress bar',['../group__sys__progress__bar.html',1,'']]],
  ['a_20time_6',['One at a time',['../group__sys__hashes__one__at__a__time.html',1,'']]],
  ['a_20tiny_20javascript_20engine_7',['Elk: a tiny Javascript engine',['../group__pkg__elk.html',1,'']]],
  ['a1_20xplained_20board_8',['ATxmega-A1 Xplained board',['../group__boards__atxmega-a1-xplained.html',1,'']]],
  ['a1u_20xplained_20pro_20board_9',['ATxmega-A1U Xplained Pro board',['../group__boards__atxmega-a1u-xpro.html',1,'']]],
  ['a2_10',['MSB-A2',['../group__boards__msba2.html',1,'']]],
  ['a3bu_20xplained_20board_11',['ATxmega-A3BU Xplained board',['../group__boards__atxmega-a3bu-xplained.html',1,'']]],
  ['a8_20m3_20open_20node_12',['IoT-LAB A8 M3 open node',['../group__boards__iotlab-a8-m3.html',1,'']]],
  ['abe_13',['ABE',['../group__sys__congure__abe.html',1,'CongURE implementation of TCP ABE'],['../group__net__gnrc__sixlowpan__frag__sfr__congure__abe.html',1,'gnrc_sixlowpan_frag_sfr_congure_abe: TCP Reno with ABE']]],
  ['about_20ibeacon_14',['Skald about iBeacon',['../group__ble__skald__ibeacon.html',1,'']]],
  ['abstract_20control_20model_15',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['abstraction_16',['HWRNG Abstraction',['../group__drivers__periph__hwrng.html',1,'']]],
  ['abstraction_17',['STDIO abstraction',['../group__sys__stdio.html',1,'']]],
  ['abstraction_20layer_18',['IEEE802.15.4 Radio Hardware Abstraction Layer',['../group__drivers__ieee802154__hal.html',1,'']]],
  ['abstraction_20layer_19',['ztimer high level timer abstraction layer',['../group__sys__ztimer.html',1,'']]],
  ['abstraction_20layer_20deprecated_20',['xtimer high level timer abstraction layer (deprecated)',['../group__sys__xtimer.html',1,'']]],
  ['accelerometer_21',['Accelerometer',['../group__drivers__lis2dh12.html',1,'LIS2DH12 Accelerometer'],['../group__drivers__mma7660.html',1,'MMA7660 Accelerometer'],['../group__drivers__mma8x5x.html',1,'MMA8x5x Accelerometer']]],
  ['accelerometer_22',['accelerometer',['../group__drivers__adxl345.html',1,'ADXL345 3-Axis accelerometer'],['../group__drivers__lis3dh.html',1,'LIS3DH accelerometer']]],
  ['accelerometer_20driver_20compile_20configuration_23',['MMA8x5x Accelerometer driver compile configuration',['../group__drivers__mma8x5x__config.html',1,'']]],
  ['accelerometer_20gyroscope_24',['LSM6DSXX 3D accelerometer/gyroscope',['../group__drivers__lsm6dsxx.html',1,'']]],
  ['accelerometer_20magnetometer_25',['accelerometer magnetometer',['../group__drivers__fxos8700.html',1,'FXOS8700 3-axis accelerometer/magnetometer'],['../group__drivers__lsm303agr.html',1,'LSM303AGR 3D accelerometer/magnetometer'],['../group__drivers__lsm303dlhc.html',1,'LSM303DLHC 3D accelerometer/magnetometer']]],
  ['accelerometer_20magnetometer_20driver_20compile_20configuration_26',['FXOS8700 accelerometer/magnetometer driver compile configuration',['../group__drivers__fxos8700__config.html',1,'']]],
  ['accelerometer_20magnetometer_20gyroscope_27',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['access_28',['access',['../group__net__sock__async.html',1,'Sock extension for asynchronous access'],['../group__sys__atomic__utils.html',1,'Utility functions for atomic access']]],
  ['access_20api_20to_20mbed_20tls_20entropy_20module_29',['Access API to Mbed TLS entropy module',['../group__pkg__mbedtls__entropy.html',1,'']]],
  ['access_20methods_30',['unaligned memory access methods',['../group__sys__unaligned.html',1,'']]],
  ['access_20points_31',['access points',['../group__net__wifi__scan__list.html',1,'List of scanned WiFis access points'],['../group__net__l2scanlist.html',1,'Scan List - List of wireless access points']]],
  ['access_20to_20architecture_32',['Platform-independent access to architecture',['../group__sys__architecture.html',1,'']]],
  ['accesses_33',['Helpers for volatile accesses',['../group__sys__atomic__utils__volatile.html',1,'']]],
  ['accurate_20spi_20rtc_34',['DS3234 Extremely Accurate SPI RTC',['../group__drivers__ds3234.html',1,'']]],
  ['acd52832_35',['ACD52832',['../group__boards__acd52832.html',1,'']]],
  ['acm_36',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['acm_20compile_20time_20configurations_37',['USBUS CDC ACM compile time configurations',['../group__usbus__cdc__acm__conf.html',1,'']]],
  ['acm_20internals_38',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['acm_20tinyusb_39',['STDIO over USB CDC-ACM (tinyUSB)',['../group__pkg__tinyusb__stdio__cdc__acm.html',1,'']]],
  ['acm_20usbus_40',['STDIO over CDC ACM (usbus)',['../group__usbus__cdc__acm__stdio.html',1,'']]],
  ['acm_20usbus_20cdc_20abstract_20control_20model_41',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['acmesystems_20yarm_20board_42',['Acmesystems YARM board',['../group__boards__yarm.html',1,'']]],
  ['actuator_20device_20configurations_43',['Actuator Device Configurations',['../group__config__drivers__actuators.html',1,'']]],
  ['actuator_20device_20drivers_44',['Actuator Device Drivers',['../group__drivers__actuators.html',1,'']]],
  ['ad_20processing_45',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['ad7746_20capacitance_20to_20digital_20converter_20driver_46',['AD7746 Capacitance-to-digital converter driver',['../group__drivers__ad7746.html',1,'']]],
  ['adafruit_20clue_47',['Adafruit Clue',['../group__boards__adafruit-clue.html',1,'']]],
  ['adafruit_20feather_20m0_48',['Adafruit Feather M0',['../group__boards__feather-m0.html',1,'']]],
  ['adafruit_20feather_20m0_20lora_49',['Adafruit Feather M0 LoRa',['../group__boards__feather-m0-lora.html',1,'']]],
  ['adafruit_20feather_20m0_20wifi_50',['Adafruit Feather M0 WiFi',['../group__boards__feather-m0-wifi.html',1,'']]],
  ['adafruit_20feather_20nrf52840_20express_51',['Adafruit Feather nRF52840 Express',['../group__boards__feather-nrf52840.html',1,'']]],
  ['adafruit_20feather_20nrf52840_20sense_52',['Adafruit Feather nRF52840 Sense',['../group__boards__feather-nrf52840-sense.html',1,'']]],
  ['adafruit_20grand_20central_20m4_20express_53',['Adafruit Grand Central M4 Express',['../group__boards__adafruit-grand-central-m4-express.html',1,'']]],
  ['adafruit_20itsybitsy_20m4_54',['Adafruit-Itsybitsy-M4',['../group__boards__adafruit-itsybitsy-m4.html',1,'']]],
  ['adafruit_20itsybitsy_20nrf52_55',['Adafruit-Itsybitsy-nRF52',['../group__boards__adafruit-itsybitsy-nrf52.html',1,'']]],
  ['adafruit_20pybadge_56',['Adafruit PyBadge',['../group__boards__adafruit-pybadge.html',1,'']]],
  ['adafruit_20seesaw_20soil_20moisture_20and_20temperature_20sensor_57',['Adafruit Seesaw Soil Moisture and Temperature Sensor',['../group__drivers__seesaw__soil.html',1,'']]],
  ['adafruit_20seesaw_20soil_20moisture_20and_20temperature_20sensor_20driver_20compile_20configuration_58',['Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration',['../group__drivers__seesaw__soil__config.html',1,'']]],
  ['adafruit_20unified_20sensor_20driver_59',['Adafruit Unified Sensor Driver',['../group__pkg__adafruit__sensor.html',1,'']]],
  ['adapter_60',['lwIP netdev adapter',['../group__pkg__lwip__netdev.html',1,'']]],
  ['adapter_20for_20nrfmin_61',['GNRC adapter for nrfmin',['../group__drivers__nrf5x__nrfmin__gnrc.html',1,'']]],
  ['adaption_62',['Wakaama LwM2M platform adaption',['../group__lwm2m__platform__conf.html',1,'']]],
  ['adaption_20for_20wakaama_20package_63',['Platform adaption for Wakaama package',['../group__lwm2m__platform.html',1,'']]],
  ['adc_64',['ADC',['../group__drivers__periph__adc.html',1,'ADC'],['../group__cpu__cc2538__adc.html',1,'CC2538 ADC'],['../group__cpu__kinetis__adc.html',1,'Kinetis ADC']]],
  ['adc_20analog_20to_20digital_20converter_65',['NXP QN908x ADC - Analog to Digital converter',['../group__cpu__qn908x__adc.html',1,'']]],
  ['adc_20device_20driver_66',['ADC device driver',['../group__drivers__adcxx1c.html',1,'ADCXX1C ADC device driver'],['../group__drivers__ads101x.html',1,'ADS101x/111x ADC device driver']]],
  ['adc_20noise_20entropy_20source_67',['ADC Noise Entropy Source',['../group__sys__entropy__source__adc.html',1,'']]],
  ['adcxx1c_20adc_20device_20driver_68',['ADCXX1C ADC device driver',['../group__drivers__adcxx1c.html',1,'']]],
  ['adcxx1c_20driver_20compile_20configurations_69',['ADCXX1C driver compile configurations',['../group__drivers__adcxx1c__config.html',1,'']]],
  ['add_20xor_70',['Shift, Add, XOR',['../group__sys__hashes__sax.html',1,'']]],
  ['additional_20data_71',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['address_20blacklist_72',['IPv6 address blacklist',['../group__net__gnrc__ipv6__blacklist.html',1,'']]],
  ['address_20blacklisting_20compile_20configurations_73',['GNRC IPv6 address blacklisting compile configurations',['../group__net__gnrc__ipv6__blacklist__conf.html',1,'']]],
  ['address_20compression_74',['Contexts for 6LoWPAN address compression',['../group__net__gnrc__sixlowpan__ctx.html',1,'']]],
  ['address_20container_75',['Universal Address Container',['../group__sys__universal__address.html',1,'']]],
  ['address_20families_76',['UNIX address families',['../group__net__af.html',1,'']]],
  ['address_20filter_77',['Link layer address filter',['../group__net__l2filter.html',1,'']]],
  ['address_20filter_20compile_20configurations_78',['Link layer address filter compile configurations',['../group__net__l2filter__conf.html',1,'']]],
  ['address_20helper_79',['Address Helper',['../group__pkg__nimble__addr.html',1,'Address Helper'],['../group__ble__bluetil__addr.html',1,'BLE Address Helper']]],
  ['address_20mapper_80',['MTD address mapper',['../group__drivers__mtd__mapper.html',1,'']]],
  ['address_20out_20of_20atmel_20edbg_81',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['address_20resolution_20protocol_20arp_82',['Address resolution protocol (ARP)',['../group__net__arp.html',1,'']]],
  ['address_20whitelist_83',['IPv6 address whitelist',['../group__net__gnrc__ipv6__whitelist.html',1,'']]],
  ['address_20whitelisting_20compile_20configurations_84',['GNRC IPv6 address whitelisting compile configurations',['../group__net__gnrc__ipv6__whitelist__conf.html',1,'']]],
  ['addresses_85',['addresses',['../group__net__ipv4__addr.html',1,'IPv4 addresses'],['../group__net__ipv6__addr.html',1,'IPv6 addresses']]],
  ['ads101_20driver_20compile_20configuration_86',['ADS101 driver compile configuration',['../group__drivers__ads101x__config.html',1,'']]],
  ['ads101x_20111x_20adc_20device_20driver_87',['ADS101x/111x ADC device driver',['../group__drivers__ads101x.html',1,'']]],
  ['adt7310_20spi_20temperature_20sensor_88',['ADT7310 SPI temperature sensor',['../group__drivers__adt7310.html',1,'']]],
  ['advanced_20energy_20monitor_20driver_89',['Advanced energy monitor driver',['../group__boards__common__silabs__drivers__aem.html',1,'']]],
  ['advertises_20to_20the_20world_90',['Skald, who advertises to the world',['../group__ble__skald.html',1,'']]],
  ['advertising_91',['Automated advertising',['../group__pkg__nimble__autoadv.html',1,'']]],
  ['advertising_20data_20ad_20processing_92',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['adxl345_203_20axis_20accelerometer_93',['ADXL345 3-Axis accelerometer',['../group__drivers__adxl345.html',1,'']]],
  ['aead_20cipher_94',['chacha20poly1305 AEAD cipher',['../group__sys__crypto__chacha20poly1305.html',1,'']]],
  ['aes128_5fcmac_95',['AES128_CMAC',['../group__sys__hashes__aes128__cmac.html',1,'']]],
  ['aff_96',['SODAQ SARA AFF',['../group__boards__sodaq-sara-aff.html',1,'']]],
  ['agent_97',['DHCPv6 relay agent',['../group__net__dhcpv6__relay.html',1,'']]],
  ['agreement_98',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['aip31068_20i2c_20lcd_20controller_99',['AIP31068 I2C LCD controller',['../group__drivers__aip31068.html',1,'']]],
  ['airfy_20beacon_100',['Airfy Beacon',['../group__boards__airfy-beacon.html',1,'']]],
  ['alcohol_20tester_101',['MQ-3 Alcohol Tester',['../group__drivers__mq3.html',1,'']]],
  ['algorithm_20dispatcher_102',['PSA Crypto Algorithm Dispatcher',['../group__sys__psa__crypto__alg__disp.html',1,'']]],
  ['alientek_20pandora_103',['Alientek Pandora',['../group__boards__alientek-pandora.html',1,'']]],
  ['allocator_104',['allocator',['../group__sys__memarray.html',1,'memory array allocator'],['../group__pkg__tlsf.html',1,'Two-Level Segregated Fit memory allocator']]],
  ['als_20module_105',['VL6180X Ranging and Ambient Light Sensing (ALS) module',['../group__drivers__vl6180x.html',1,'']]],
  ['ambient_20light_20proximity_20sensors_106',['Si1145/6/7 UV/Ambient light/Proximity sensors',['../group__drivers__si114x.html',1,'']]],
  ['ambient_20light_20sensing_20als_20module_107',['VL6180X Ranging and Ambient Light Sensing (ALS) module',['../group__drivers__vl6180x.html',1,'']]],
  ['ambient_20light_20sensor_108',['OPT3001 Ambient Light Sensor',['../group__drivers__opt3001.html',1,'']]],
  ['ambient_20light_20sensor_20driver_20compile_20configuration_109',['OPT3001 Ambient Light Sensor driver compile configuration',['../group__drivers__opt3001__config.html',1,'']]],
  ['ambient_20light_20sensor_20with_20i2c_110',['Si1133 UV Index/Ambient Light Sensor with I2C',['../group__drivers__si1133.html',1,'']]],
  ['ambient_20light_20sensors_111',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['ambient_20light_20sensors_112',['APDS99XX proximity and ambient light sensors',['../group__drivers__apds99xx.html',1,'']]],
  ['analog_20data_20conversion_20utilities_113',['Analog data conversion utilities',['../group__sys__analog__util.html',1,'']]],
  ['analog_20to_20digital_20converter_114',['NXP QN908x ADC - Analog to Digital converter',['../group__cpu__qn908x__adc.html',1,'']]],
  ['and_20agreement_115',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['and_20ambient_20light_20sensing_20als_20module_116',['VL6180X Ranging and Ambient Light Sensing (ALS) module',['../group__drivers__vl6180x.html',1,'']]],
  ['and_20ambient_20light_20sensors_117',['VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors',['../group__drivers__vcnl40x0.html',1,'']]],
  ['and_20ambient_20light_20sensors_118',['APDS99XX proximity and ambient light sensors',['../group__drivers__apds99xx.html',1,'']]],
  ['and_20bluepill_20common_20code_119',['Blackpill and Bluepill common code',['../group__boards__common__blxxxpill.html',1,'']]],
  ['and_20clones_120',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['and_20composer_121',['DNS message parser and composer',['../group__net__dns__msg.html',1,'']]],
  ['and_20composition_20configuration_122',['DNS message parsing and composition configuration',['../group__net__dns__msg__conf.html',1,'']]],
  ['and_20configuration_123',['Startup and Configuration',['../group__core__internal.html',1,'']]],
  ['and_20definitions_124',['IEEE 802.15.4 frame headers and definitions',['../group__net__ieee802154__header.html',1,'']]],
  ['and_20delete_20operator_20module_125',['C++ new and delete operator module',['../group__sys__cpp__new__delete.html',1,'']]],
  ['and_20differential_20pressure_20sensor_126',['SDP3x temperature and differential pressure sensor',['../group__drivers__sdp3x.html',1,'']]],
  ['and_20endpoint_20manager_127',['USBUS device and endpoint manager',['../group__usb__usbus.html',1,'']]],
  ['and_20friends_128',['Thread-safe wrappers for malloc and friends',['../group__sys__malloc__ts.html',1,'']]],
  ['and_20hop_20by_20hop_20options_129',['IPv6 destination and hop-by-hop options',['../group__net__ipv6__ext__opt.html',1,'']]],
  ['and_20humidity_20sensor_130',['and humidity sensor',['../group__drivers__bmx280.html',1,'BMP280/BME280 temperature, pressure and humidity sensor'],['../group__drivers__scd30.html',1,'SCD30 CO2, temperature and humidity sensor'],['../group__drivers__shtcx.html',1,'SHTCX Temperature and humidity sensor']]],
  ['and_20humidity_20sensors_131',['Si7006/13/20/21/5x temperature and humidity sensors',['../group__drivers__si70xx.html',1,'']]],
  ['and_20interrupt_20driver_132',['Power-and-interrupt driver',['../group__boards__common__silabs__drivers__pic.html',1,'']]],
  ['and_20kw2xd_20radio_20driver_20compile_20configuration_133',['CR20A and KW2xD radio driver compile configuration',['../group__drivers__kw2xrf__config.html',1,'']]],
  ['and_20llcc68_20internal_20functions_134',['SX1261/2/8 and LLCC68 internal functions',['../group__drivers__sx126x__internal.html',1,'']]],
  ['and_20llcc68_20lora_20radio_20driver_135',['SX1261/2/8 and LLCC68 LoRa radio driver',['../group__drivers__sx126x.html',1,'']]],
  ['and_20lookup_20client_136',['CoRE RD Endpoint and Lookup Client',['../group__net__cord.html',1,'']]],
  ['and_20mpu9250_20accelerometer_20magnetometer_20gyroscope_137',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['and_20pressure_20sensor_138',['and pressure sensor',['../group__drivers__bmp180.html',1,'BMP180 temperature and pressure sensor'],['../group__drivers__hsc.html',1,'HSC temperature and pressure sensor']]],
  ['and_20reassembly_20statistics_139',['Fragmentation and reassembly statistics',['../group__net__gnrc__sixlowpan__frag__stats.html',1,'']]],
  ['and_20ritchie_140',['Kernighan and Ritchie',['../group__sys__hashes__kr.html',1,'']]],
  ['and_20sx1276_20driver_20compile_20configuration_141',['Semtech SX1272 and SX1276 driver compile configuration',['../group__drivers__sx127x__config.html',1,'']]],
  ['and_20sx1276_20radios_20driver_142',['Semtech SX1272 and SX1276 radios driver',['../group__drivers__sx127x.html',1,'']]],
  ['and_20temperature_20sensor_143',['and Temperature Sensor',['../group__drivers__seesaw__soil.html',1,'Adafruit Seesaw Soil Moisture and Temperature Sensor'],['../group__drivers__hdc1000.html',1,'HDC1000 Humidity and Temperature Sensor'],['../group__drivers__sht1x.html',1,'SHT10/SHT11/SHT15 Humidity and Temperature Sensor']]],
  ['and_20temperature_20sensor_144',['SHT2x Humidity and Temperature sensor',['../group__drivers__sht2x.html',1,'']]],
  ['and_20temperature_20sensor_145',['HIH6130 humidity and temperature sensor',['../group__drivers__hih6130.html',1,'']]],
  ['and_20temperature_20sensor_20driver_20compile_20configuration_146',['and Temperature Sensor driver compile configuration',['../group__drivers__seesaw__soil__config.html',1,'Adafruit Seesaw Soil Moisture and Temperature Sensor driver compile configuration'],['../group__drivers__hdc1000__config.html',1,'HDC1000 Humidity and Temperature Sensor driver compile configuration']]],
  ['and_20temperature_20sensor_20series_147',['SHT3x Humidity and Temperature Sensor Series',['../group__drivers__sht3x.html',1,'']]],
  ['and_20temperature_20sensors_148',['DHT Family of Humidity and Temperature Sensors',['../group__drivers__dht.html',1,'']]],
  ['and_20tools_149',['RIOT header helpers and tools',['../group__sys__riotboot__hdr.html',1,'']]],
  ['and_20types_20for_150',['Utility functions, macros, and types for',['../group__sys__flash__utils.html',1,'']]],
  ['and_20utilities_151',['Math libraries and utilities',['../group__sys__math.html',1,'']]],
  ['apa102_20rgb_20led_152',['APA102 RGB LED',['../group__drivers__apa102.html',1,'']]],
  ['apds99xx_20proximity_20and_20ambient_20light_20sensors_153',['APDS99XX proximity and ambient light sensors',['../group__drivers__apds99xx.html',1,'']]],
  ['api_154',['API',['../group__sys__arduino__api.html',1,'Arduino API'],['../group__net__sock__async__event.html',1,'Asynchronous sock with event API'],['../group__drivers__disp__dev.html',1,'Display device generic API'],['../group__net__sock__dodtls.html',1,'DNS over DTLS sock API'],['../group__net__sock__dns.html',1,'DNS sock API'],['../group__net__sock__dtls.html',1,'DTLS sock API'],['../group__net__sock__dtls__creds.html',1,'DTLS sock credentials API'],['../group__cpu__esp32__esp__idf__api.html',1,'ESP-IDF Interface API'],['../group__net__gnrc__sock.html',1,'GNRC-specific implementation of the sock API'],['../group__drivers__periph__gpio__ll.html',1,'GPIO Low-Level API'],['../group__drivers__periph__gpio__ll__irq.html',1,'IRQ Support in Peripheral GPIO Low-Level API'],['../group__pkg__lwip__sock.html',1,'lwIP-specific implementation of sock API'],['../group__drivers__netdev__api.html',1,'Netdev - Network Device Driver API'],['../group__net__gnrc__netif.html',1,'Network interface API'],['../group__pkg__openwsn__sock.html',1,'OpenWSN-specific implementation of the sock API'],['../group__sys__psa__crypto__pers__stor.html',1,'PSA Crypto Persistent Storage API'],['../group__sys__psa__crypto.html',1,'PSA Cryptographic API'],['../group__net__sock__ip.html',1,'Raw IPv4/IPv6 sock API'],['../group__drivers__screen__dev.html',1,'Screen device generic API'],['../group__net__sock.html',1,'Sock API'],['../group__net__sock__tcp.html',1,'TCP sock API'],['../group__turo__API.html',1,'Test Utils Result Output Implementation API'],['../group__drivers__touch__dev.html',1,'Touch device generic API'],['../group__net__sock__udp.html',1,'UDP sock API'],['../group__drivers__periph__usbdev.html',1,'usbdev - USB Device Driver API']]],
  ['api_20fmt_5ftable_155',['Table extension of the string formatting API (fmt_table)',['../group__sys__fmt__table.html',1,'']]],
  ['api_20for_20eeprom_156',['Native extra API for EEPROM',['../group__drivers__eeprom__native.html',1,'']]],
  ['api_20sdmmc_157',['SDIO/SD/MMC Device API (SDMMC)',['../group__drivers__sdmmc.html',1,'']]],
  ['api_20to_20mbed_20tls_158',['Entropy source API to Mbed TLS',['../group__pkg__mbedtls__entropy__sources.html',1,'']]],
  ['api_20to_20mbed_20tls_20entropy_20module_159',['Access API to Mbed TLS entropy module',['../group__pkg__mbedtls__entropy.html',1,'']]],
  ['apis_160',['APIs',['../group__net__netopt.html',1,'Netopt - Configuration options for network APIs'],['../group__usb__usbopt.html',1,'usbopt - Configuration options for USB APIs']]],
  ['app_5fmetadata_161',['app_metadata',['../group__sys__app__metadata.html',1,'']]],
  ['appendix_20c_162',['gnrc_sixlowpan_frag_sfr_congure_sfr: Appendix C',['../group__net__gnrc__sixlowpan__frag__sfr__congure__sfr.html',1,'']]],
  ['arch_20pro_20development_20kit_163',['Seeeduino Arch Pro development kit',['../group__boards__seeduino__arch-pro.html',1,'']]],
  ['architecture_164',['Platform-independent access to architecture',['../group__sys__architecture.html',1,'']]],
  ['arduino_165',['Arduino',['../group__sys__arduino.html',1,'']]],
  ['arduino_20api_166',['Arduino API',['../group__sys__arduino__api.html',1,'']]],
  ['arduino_20atmega_20common_167',['Arduino Atmega Common',['../group__boards__common__arduino-atmega.html',1,'']]],
  ['arduino_20cores_168',['Hardware independent layer of the Arduino cores',['../group__pkg__arduino__api.html',1,'']]],
  ['arduino_20due_169',['Arduino Due',['../group__boards__arduino-due.html',1,'']]],
  ['arduino_20due_20common_170',['Arduino Due Common',['../group__boards__common__arduino__due.html',1,'']]],
  ['arduino_20duemilanove_171',['Arduino Duemilanove',['../group__boards__arduino-duemilanove.html',1,'']]],
  ['arduino_20leonardo_172',['Arduino Leonardo',['../group__boards__arduino-leonardo.html',1,'']]],
  ['arduino_20library_20for_20demonstration_173',['Talking LEDs - Arduino library for demonstration',['../group__pkg__talking__leds.html',1,'']]],
  ['arduino_20library_20for_20sdi_2012_20communication_174',['Arduino library for SDI-12 communication',['../group__pkg__arduino__sdi__12.html',1,'']]],
  ['arduino_20mega_202560_175',['Arduino Mega 2560',['../group__boards__arduino-mega2560.html',1,'']]],
  ['arduino_20mkr_20common_176',['Arduino MKR Common',['../group__boards__common__arduino-mkr.html',1,'']]],
  ['arduino_20mkr_20wan_201300_177',['Arduino MKR WAN 1300',['../group__boards__arduino-mkrwan1300.html',1,'']]],
  ['arduino_20mkr1000_178',['Arduino MKR1000',['../group__boards__arduino-mkr1000.html',1,'']]],
  ['arduino_20mkrfox1200_179',['Arduino MKRFOX1200',['../group__boards__arduino-mkrfox1200.html',1,'']]],
  ['arduino_20mkrzero_180',['Arduino MKRZERO',['../group__boards__arduino-mkrzero.html',1,'']]],
  ['arduino_20nano_181',['Arduino Nano',['../group__boards__arduino-nano.html',1,'']]],
  ['arduino_20nano_2033_20ble_182',['Arduino Nano 33 BLE',['../group__boards__arduino-nano-33-ble.html',1,'']]],
  ['arduino_20nano_2033_20ble_20sense_183',['Arduino Nano 33 BLE sense',['../group__boards__arduino-nano-33-ble-sense.html',1,'']]],
  ['arduino_20nano_2033_20iot_184',['Arduino Nano 33 IoT',['../group__boards__arduino-nano-33-iot.html',1,'']]],
  ['arduino_20uno_185',['Arduino Uno',['../group__boards__arduino-uno.html',1,'']]],
  ['arduino_20zero_186',['Arduino Zero',['../group__boards__arduino-zero.html',1,'']]],
  ['arduino_20zero_20and_20clones_187',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['arduino_20zero_20clone_188',['WeMos Arduino Zero Clone',['../group__boards__wemos-zero.html',1,'']]],
  ['are_20missing_20in_20tt_20string_20h_20tt_189',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['area_20network_190',['CAN (Controller Area Network)',['../group__sys__can.html',1,'']]],
  ['argon_191',['Particle Argon',['../group__boards__particle-argon.html',1,'']]],
  ['arithmetic_192',['Serial Number Arithmetic',['../group__sys__seq.html',1,'']]],
  ['arm_20cortex_20m_20common_193',['ARM Cortex-M common',['../group__cpu__cortexm__common.html',1,'']]],
  ['arm_20cryptocell_20310_20driver_194',['ARM CryptoCell 310 Driver',['../group__pkg__driver__cryptocell__310.html',1,'']]],
  ['arm_20mbed_20tls_195',['ARM Mbed TLS',['../group__pkg__mbedtls.html',1,'']]],
  ['arm7_20cpu_20common_196',['ARM7 CPU common',['../group__cpu__arm7__common.html',1,'']]],
  ['arm7tdmi_197',['GBAs ARM7TDMI',['../group__cpu__arm7tdmi__gba.html',1,'']]],
  ['arm_5fstack_5flimit_198',['arm_stack_limit',['../group__pseudomodule__arm__stack__limit.html',1,'']]],
  ['arp_199',['Address resolution protocol (ARP)',['../group__net__arp.html',1,'']]],
  ['array_20allocator_200',['memory array allocator',['../group__sys__memarray.html',1,'']]],
  ['as_20provided_20by_20most_20libcs_201',['endian conversions as provided by most libcs',['../group__sys__endian.html',1,'']]],
  ['asn_201_20decoding_20encoding_20library_202',['Lightweight ASN.1 decoding/encoding library',['../group__pkg__tiny-asn1.html',1,'']]],
  ['assurance_20cryptographic_20library_203',['HACL* High Assurance Cryptographic Library',['../group__pkg__hacl.html',1,'']]],
  ['asymcute_204',['MQTT-SN Client (Asymcute)',['../group__net__asymcute.html',1,'']]],
  ['asymcute_20mqtt_20sn_20client_20compile_20configurations_205',['Asymcute (MQTT-SN Client) compile configurations',['../group__net__asymcute__conf.html',1,'']]],
  ['asymmetric_20cryptography_206',['Secure Element Asymmetric Cryptography',['../group__se__asymmetric.html',1,'']]],
  ['asynchronous_20access_207',['Sock extension for asynchronous access',['../group__net__sock__async.html',1,'']]],
  ['asynchronous_20sock_20with_20event_20api_208',['Asynchronous sock with event API',['../group__net__sock__async__event.html',1,'']]],
  ['at_20a_20time_209',['One at a time',['../group__sys__hashes__one__at__a__time.html',1,'']]],
  ['at_20driver_20compile_20configuration_210',['AT driver compile configuration',['../group__drivers__at__config.html',1,'']]],
  ['at_20hayes_20command_20set_20library_211',['AT (Hayes) command set library',['../group__drivers__at.html',1,'']]],
  ['at24cxxx_20eeprom_20unit_212',['AT24CXXX EEPROM unit',['../group__drivers__at24cxxx.html',1,'']]],
  ['at24cxxx_20family_20of_20i2c_20eeproms_213',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['at24mac_20unique_20id_20chip_214',['AT24MAC unique ID chip',['../group__drivers__at24mac.html',1,'']]],
  ['at25xxx_20family_20of_20spi_20eeproms_215',['AT25xxx family of SPI EEPROMs',['../group__drivers__at25xxx.html',1,'AT25xxx family of SPI-EEPROMs'],['../group__drivers__mtd__at25xxx.html',1,'MTD wrapper for AT25xxx family of SPI-EEPROMs']]],
  ['at30tse75x_20temperature_20sensor_20with_20eeprom_216',['AT30TSE75x temperature sensor with EEPROM',['../group__drivers__at30tse75x.html',1,'']]],
  ['at86rf215_20based_20drivers_217',['AT86RF215 based drivers',['../group__drivers__at86rf215.html',1,'']]],
  ['at86rf215_20driver_20compile_20configuration_218',['AT86RF215 driver compile configuration',['../group__drivers__at86rf215__config.html',1,'']]],
  ['at86rf215_20mr_20fsk_20phy_219',['AT86RF215 MR-FSK PHY',['../group__drivers__at86rf215__fsk.html',1,'']]],
  ['at86rf215_20mr_20o_20qpsk_20phy_220',['AT86RF215 MR-O-QPSK PHY',['../group__drivers__at86rf215__oqpsk.html',1,'']]],
  ['at86rf215_20mr_20ofdm_20phy_221',['AT86RF215 MR-OFDM PHY',['../group__drivers__at86rf215__ofdm.html',1,'']]],
  ['at86rf2xx_20based_20drivers_222',['AT86RF2xx based drivers',['../group__drivers__at86rf2xx.html',1,'']]],
  ['ata8520e_20transceiver_223',['Microchip ATA8520E transceiver',['../group__drivers__ata8520e.html',1,'']]],
  ['atca_20driver_20compile_20configuration_224',['ATCA driver compile configuration',['../group__drivers__atca__config.html',1,'']]],
  ['atmega_20common_225',['ATmega common',['../group__boards__common__atmega.html',1,'']]],
  ['atmega_20common_226',['Arduino Atmega Common',['../group__boards__common__arduino-atmega.html',1,'']]],
  ['atmega_20cpu_3a_20common_20files_227',['Atmel ATmega CPU: common files',['../group__cpu__atmega__common.html',1,'']]],
  ['atmega1281_228',['Atmel ATmega1281',['../group__cpu__atmega1281.html',1,'']]],
  ['atmega1281_20definitions_229',['Atmel ATmega1281 Definitions',['../group__cpu__atmega1281__definitions.html',1,'']]],
  ['atmega1284p_230',['Standalone ATmega1284P',['../group__boards__atmega1284p.html',1,'']]],
  ['atmega1284p_231',['Atmel ATmega1284p',['../group__cpu__atmega1284p.html',1,'']]],
  ['atmega1284p_20definitions_232',['Atmel ATmega1284p Definitions',['../group__cpu__atmega1284p__definitions.html',1,'']]],
  ['atmega128rfa1_233',['Atmel ATmega128rfa1',['../group__cpu__atmega128rfa1.html',1,'']]],
  ['atmega2560_234',['Atmel ATmega2560',['../group__cpu__atmega2560.html',1,'']]],
  ['atmega2560_20definitions_235',['Atmel ATmega2560 Definitions',['../group__cpu__atmega2560__definitions.html',1,'']]],
  ['atmega256rfr2_236',['Atmel ATmega256rfr2',['../group__cpu__atmega256rfr2.html',1,'']]],
  ['atmega256rfr2_20rss2_237',['Atmega256RFR2 rss2',['../group__boards__avr-rss2.html',1,'']]],
  ['atmega256rfr2_20xplained_20pro_238',['Atmega256RFR2 Xplained Pro',['../group__boards__atmega256rfr2-xpro.html',1,'']]],
  ['atmega328p_239',['ATmega328p',['../group__cpu__atmega328p.html',1,'Atmel ATmega328p'],['../group__boards__atmega328p.html',1,'Standalone ATmega328p']]],
  ['atmega328p_20definitions_240',['Atmel ATmega328p Definitions',['../group__cpu__atmega328p__definitions.html',1,'']]],
  ['atmega328p_20xplained_20mini_241',['ATmega328p Xplained Mini',['../group__boards__atmega328p__xplained__mini.html',1,'']]],
  ['atmega32u4_242',['Atmel ATmega32u4',['../group__cpu__atmega32u4.html',1,'']]],
  ['atmega32u4_20definitions_243',['Atmel ATmega32u4 Definitions',['../group__cpu__atmega32u4__definitions.html',1,'']]],
  ['atmega8_244',['ATmega8',['../group__cpu__atmega8.html',1,'Atmel ATmega8'],['../group__boards__atmega8.html',1,'Standalone ATmega8']]],
  ['atmega8_20definitions_245',['Atmel ATmega8 Definitions',['../group__cpu__atmega8__definitions.html',1,'']]],
  ['atmel_20atmega_20cpu_3a_20common_20files_246',['Atmel ATmega CPU: common files',['../group__cpu__atmega__common.html',1,'']]],
  ['atmel_20atmega1281_247',['Atmel ATmega1281',['../group__cpu__atmega1281.html',1,'']]],
  ['atmel_20atmega1281_20definitions_248',['Atmel ATmega1281 Definitions',['../group__cpu__atmega1281__definitions.html',1,'']]],
  ['atmel_20atmega1284p_249',['Atmel ATmega1284p',['../group__cpu__atmega1284p.html',1,'']]],
  ['atmel_20atmega1284p_20definitions_250',['Atmel ATmega1284p Definitions',['../group__cpu__atmega1284p__definitions.html',1,'']]],
  ['atmel_20atmega128rfa1_251',['Atmel ATmega128rfa1',['../group__cpu__atmega128rfa1.html',1,'']]],
  ['atmel_20atmega2560_252',['Atmel ATmega2560',['../group__cpu__atmega2560.html',1,'']]],
  ['atmel_20atmega2560_20definitions_253',['Atmel ATmega2560 Definitions',['../group__cpu__atmega2560__definitions.html',1,'']]],
  ['atmel_20atmega256rfr2_254',['Atmel ATmega256rfr2',['../group__cpu__atmega256rfr2.html',1,'']]],
  ['atmel_20atmega328p_255',['Atmel ATmega328p',['../group__cpu__atmega328p.html',1,'']]],
  ['atmel_20atmega328p_20definitions_256',['Atmel ATmega328p Definitions',['../group__cpu__atmega328p__definitions.html',1,'']]],
  ['atmel_20atmega32u4_257',['Atmel ATmega32u4',['../group__cpu__atmega32u4.html',1,'']]],
  ['atmel_20atmega32u4_20definitions_258',['Atmel ATmega32u4 Definitions',['../group__cpu__atmega32u4__definitions.html',1,'']]],
  ['atmel_20atmega8_259',['Atmel ATmega8',['../group__cpu__atmega8.html',1,'']]],
  ['atmel_20atmega8_20definitions_260',['Atmel ATmega8 Definitions',['../group__cpu__atmega8__definitions.html',1,'']]],
  ['atmel_20atxmega_20mcu_261',['Atmel ATxmega MCU',['../group__cpu__atxmega.html',1,'']]],
  ['atmel_20atxmega_20mcu_20peripherals_262',['Atmel ATxmega MCU Peripherals',['../group__cpu__atxmega__periph.html',1,'']]],
  ['atmel_20avr_208_20cpu_3a_20common_20files_263',['Atmel AVR-8 CPU: common files',['../group__cpu__avr8__common.html',1,'']]],
  ['atmel_20edbg_264',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['atmel_20io1_20xplained_20extension_20board_265',['Atmel IO1 Xplained Extension board',['../group__drivers__io1__xplained.html',1,'']]],
  ['atmel_20sam_20common_266',['Atmel SAM common',['../group__cpu__sam__common.html',1,'']]],
  ['atmel_20sam_20d10_20xplained_20mini_267',['Atmel SAM D10 Xplained Mini',['../group__boards__samd10-xmini.html',1,'']]],
  ['atmel_20sam_20d20_20xplained_20pro_268',['Atmel SAM D20 Xplained Pro',['../group__boards__samd20-xpro.html',1,'']]],
  ['atmel_20sam_20d21_20xplained_20pro_269',['Atmel SAM D21 Xplained Pro',['../group__boards__samd21-xpro.html',1,'']]],
  ['atmel_20sam_20l21_20xplained_20pro_270',['Atmel SAM L21 Xplained Pro',['../group__boards__saml21-xpro.html',1,'']]],
  ['atmel_20sam_20r21_20xplained_20pro_271',['Atmel SAM R21 Xplained Pro',['../group__boards__samr21-xpro.html',1,'']]],
  ['atmel_20sam_20r30_20xplained_20pro_272',['Atmel SAM R30 Xplained Pro',['../group__boards__samr30-xpro.html',1,'']]],
  ['atmel_20sam0_20common_273',['Atmel SAM0 common',['../group__cpu__sam0__common.html',1,'']]],
  ['atmel_20sam3_274',['Atmel SAM3',['../group__cpu__sam3.html',1,'']]],
  ['atmel_20samd10_20samd20_20samd21_20samr21_275',['Atmel SAMD10/SAMD20/SAMD21/SAMR21',['../group__cpu__samd21.html',1,'']]],
  ['atmel_20saml21_276',['Atmel SAML21',['../group__cpu__saml21.html',1,'']]],
  ['atomic_20access_277',['Utility functions for atomic access',['../group__sys__atomic__utils.html',1,'']]],
  ['atomics_278',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['atwinc15x0_20wifi_20module_20driver_279',['ATWINC15x0 WiFi module driver',['../group__drivers__atwinc15x0.html',1,'']]],
  ['atwinc15x0_20wifi_20module_20vendor_20driver_20package_280',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['atxmega_20a1_20xplained_20board_281',['ATxmega-A1 Xplained board',['../group__boards__atxmega-a1-xplained.html',1,'']]],
  ['atxmega_20a1u_20xplained_20pro_20board_282',['ATxmega-A1U Xplained Pro board',['../group__boards__atxmega-a1u-xpro.html',1,'']]],
  ['atxmega_20a3bu_20xplained_20board_283',['ATxmega-A3BU Xplained board',['../group__boards__atxmega-a3bu-xplained.html',1,'']]],
  ['atxmega_20common_284',['ATxmega common',['../group__boards__common__atxmega.html',1,'']]],
  ['atxmega_20mcu_285',['Atmel ATxmega MCU',['../group__cpu__atxmega.html',1,'']]],
  ['atxmega_20mcu_20peripherals_286',['Atmel ATxmega MCU Peripherals',['../group__cpu__atxmega__periph.html',1,'']]],
  ['authenticated_20encryption_20with_20additional_20data_287',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['authentication_20codes_288',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['authoritative_20border_20router_20list_289',['Authoritative border router list',['../group__net__gnrc__ipv6__nib__abr.html',1,'']]],
  ['auto_20configuration_290',['Simple-Subnet auto-configuration',['../group__net__gnrc__ipv6__auto__subnets.html',1,'']]],
  ['auto_20initialisation_291',['SAUL Auto Initialisation',['../group__auto__init__saul.html',1,'']]],
  ['auto_20initialization_292',['Auto-initialization',['../group__sys__auto__init.html',1,'']]],
  ['auto_20initialization_293',['auto initialization',['../group__sys__auto__init__gnrc__netif.html',1,'GNRC netif drivers auto-initialization'],['../group__sys__auto__init__lwip__netif.html',1,'lwIP netif drivers auto-initialization'],['../group__sys__auto__init__multimedia.html',1,'Multimedia driver auto-initialization'],['../group__sys__auto__init__saul.html',1,'SAUL drivers auto-initialization']]],
  ['auto_20initialized_20modules_294',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['autoconn_295',['Autoconn',['../group__pkg__nimble__autoconn.html',1,'']]],
  ['automated_20advertising_296',['Automated advertising',['../group__pkg__nimble__autoadv.html',1,'']]],
  ['autonomo_297',['SODAQ Autonomo',['../group__boards__sodaq-autonomo.html',1,'']]],
  ['avr_208_20cpu_3a_20common_20files_298',['Atmel AVR-8 CPU: common files',['../group__cpu__avr8__common.html',1,'']]],
  ['avr8_299',['stdio wrapper for AVR8',['../group__cpu__avr8__common__stdio__wrapper.html',1,'']]],
  ['avsextrem_300',['Avsextrem',['../group__boards__avsextrem.html',1,'']]],
  ['axis_20accelerometer_301',['ADXL345 3-Axis accelerometer',['../group__drivers__adxl345.html',1,'']]],
  ['axis_20accelerometer_20magnetometer_302',['FXOS8700 3-axis accelerometer/magnetometer',['../group__drivers__fxos8700.html',1,'']]],
  ['axis_20digital_20compass_303',['HMC5883L 3-axis digital compass',['../group__drivers__hmc5883l.html',1,'']]],
  ['axis_20digital_20magnetic_20sensor_304',['QMC5883L 3-Axis Digital Magnetic Sensor',['../group__drivers__qmc5883l.html',1,'']]],
  ['axis_20digital_20magnetometer_305',['MAG3110 3-Axis Digital Magnetometer',['../group__drivers__mag3110.html',1,'']]],
  ['axis_20gyroscope_306',['ITG320X 3-axis gyroscope',['../group__drivers__itg320x.html',1,'']]],
  ['axis_20gyroscope_20sensor_20family_307',['L3Gxxxx 3-axis gyroscope sensor family',['../group__drivers__l3gxxxx.html',1,'']]],
  ['axis_20magnetometer_308',['LIS3MDL 3-axis magnetometer',['../group__drivers__lis3mdl.html',1,'']]],
  ['axis_20sensor_309',['BMX055 9-axis sensor',['../group__drivers__bmx055.html',1,'']]],
  ['ayer_310',['[S]ensor [A]ctuator [U]ber [L]ayer',['../group__drivers__saul.html',1,'']]]
];
