var searchData=
[
  ['f030r8_0',['STM32 Nucleo-F030R8',['../group__boards__nucleo-f030r8.html',1,'']]],
  ['f031k6_1',['STM32 Nucleo-F031K6',['../group__boards__nucleo-f031k6.html',1,'']]],
  ['f042k6_2',['STM32 Nucleo-F042K6',['../group__boards__nucleo-f042k6.html',1,'']]],
  ['f070rb_3',['STM32 Nucleo-F070RB',['../group__boards__nucleo-f070rb.html',1,'']]],
  ['f072rb_4',['STM32 Nucleo-F072RB',['../group__boards__nucleo-f072rb.html',1,'']]],
  ['f091rc_5',['STM32 Nucleo-F091RC',['../group__boards__nucleo-f091rc.html',1,'']]],
  ['f103rb_6',['STM32 Nucleo-F103RB',['../group__boards__nucleo-f103rb.html',1,'']]],
  ['f207zg_7',['STM32 Nucleo-F207ZG',['../group__boards__nucleo-f207zg.html',1,'']]],
  ['f2xx_20g2xx_20mcu_20family_8',['MSP430 F2xx/G2xx MCU family',['../group__cpu__msp430__f2xx__g2xx.html',1,'']]],
  ['f302r8_9',['STM32 Nucleo-F302R8',['../group__boards__nucleo-f302r8.html',1,'']]],
  ['f303k8_10',['STM32 Nucleo-F303K8',['../group__boards__nucleo-f303k8.html',1,'']]],
  ['f303re_11',['STM32 Nucleo-F303RE',['../group__boards__nucleo-f303re.html',1,'']]],
  ['f303ze_12',['STM32 Nucleo-F303ZE',['../group__boards__nucleo-f303ze.html',1,'']]],
  ['f334r8_13',['STM32 Nucleo-F334R8',['../group__boards__nucleo-f334r8.html',1,'']]],
  ['f401cc_20board_14',['WeAct-F401CC board',['../group__boards__weact-f401cc.html',1,'']]],
  ['f401ce_20board_15',['WeAct-F401CE board',['../group__boards__weact-f401ce.html',1,'']]],
  ['f401re_16',['STM32 Nucleo-F401RE',['../group__boards__nucleo-f401re.html',1,'']]],
  ['f410rb_17',['STM32 Nucleo-F410RB',['../group__boards__nucleo-f410rb.html',1,'']]],
  ['f411ce_20board_18',['WeAct-F411CE board',['../group__boards__weact-f411ce.html',1,'']]],
  ['f411re_19',['STM32 Nucleo-F411RE',['../group__boards__nucleo-f411re.html',1,'']]],
  ['f412zg_20',['STM32 Nucleo-F412ZG',['../group__boards__nucleo-f412zg.html',1,'']]],
  ['f413zh_21',['STM32 Nucleo-F413ZH',['../group__boards__nucleo-f413zh.html',1,'']]],
  ['f429zi_22',['STM32 Nucleo-F429ZI',['../group__boards__nucleo-f429zi.html',1,'']]],
  ['f439zi_23',['STM32 Nucleo-F439ZI',['../group__boards__nucleo-f439zi.html',1,'']]],
  ['f446re_24',['STM32 Nucleo-F446RE',['../group__boards__nucleo-f446re.html',1,'']]],
  ['f446ze_25',['STM32 Nucleo-F446ZE',['../group__boards__nucleo-f446ze.html',1,'']]],
  ['f4vi1_26',['F4VI1',['../group__boards__f4vi1.html',1,'']]],
  ['f4x1cx_20common_20code_27',['WeAct-F4x1Cx common code',['../group__boards__common__weact-f4x1cx.html',1,'']]],
  ['f722ze_28',['STM32 Nucleo-F722ZE',['../group__boards__nucleo-f722ze.html',1,'']]],
  ['f746zg_29',['STM32 Nucleo-F746ZG',['../group__boards__nucleo-f746zg.html',1,'']]],
  ['f767zi_30',['STM32 Nucleo-F767ZI',['../group__boards__nucleo-f767zi.html',1,'']]],
  ['fake_20functions_20framework_31',['Fake Functions Framework',['../group__pkg__fff.html',1,'']]],
  ['families_32',['UNIX address families',['../group__net__af.html',1,'']]],
  ['family_33',['family',['../group__cpu__esp32__esp32.html',1,'ESP32 family'],['../group__cpu__esp32__esp32c3.html',1,'ESP32-C3 family'],['../group__cpu__esp32__esp32s2.html',1,'ESP32-S2 family'],['../group__cpu__esp32__esp32s3.html',1,'ESP32-S3 family'],['../group__drivers__l3gxxxx.html',1,'L3Gxxxx 3-axis gyroscope sensor family'],['../group__cpu__msp430__f2xx__g2xx.html',1,'MSP430 F2xx/G2xx MCU family'],['../group__cpu__msp430__x1xx.html',1,'MSP430 x1xx MCU family'],['../group__cpu__efm32gg.html',1,'Silicon Labs EFM32GG family'],['../group__cpu__efm32hg.html',1,'Silicon Labs EFM32HG family'],['../group__cpu__efm32lg.html',1,'Silicon Labs EFM32LG family'],['../group__cpu__efm32pg12b.html',1,'Silicon Labs EFM32PG12B family'],['../group__cpu__efm32pg1b.html',1,'Silicon Labs EFM32PG1B family'],['../group__cpu__efm32zg.html',1,'Silicon Labs EFM32ZG family'],['../group__cpu__efr32mg12p.html',1,'Silicon Labs EFR32MG12P family'],['../group__cpu__efr32mg1b.html',1,'Silicon Labs EFR32MG1P family'],['../group__cpu__efr32mg1p.html',1,'Silicon Labs EFR32MG1P family'],['../group__cpu__ezr32wg.html',1,'Silicon Labs EZR32WG family']]],
  ['family_20of_20humidity_20and_20temperature_20sensors_34',['DHT Family of Humidity and Temperature Sensors',['../group__drivers__dht.html',1,'']]],
  ['family_20of_20i2c_20eeproms_35',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['family_20of_20spi_20eeproms_36',['family of SPI EEPROMs',['../group__drivers__at25xxx.html',1,'AT25xxx family of SPI-EEPROMs'],['../group__drivers__mtd__at25xxx.html',1,'MTD wrapper for AT25xxx family of SPI-EEPROMs']]],
  ['fast_20identity_20online_202_37',['FIDO2 - Fast Identity Online 2',['../group__fido2.html',1,'']]],
  ['fat_20file_20system_38',['FAT file system',['../group__pkg__fatfs.html',1,'']]],
  ['fatfs_20integration_39',['FatFs integration',['../group__sys__fatfs.html',1,'']]],
  ['fe310_40',['SiFive fe310',['../group__cpu__fe310.html',1,'']]],
  ['feather_20m0_41',['Adafruit Feather M0',['../group__boards__feather-m0.html',1,'']]],
  ['feather_20m0_20lora_42',['Adafruit Feather M0 LoRa',['../group__boards__feather-m0-lora.html',1,'']]],
  ['feather_20m0_20wifi_43',['Adafruit Feather M0 WiFi',['../group__boards__feather-m0-wifi.html',1,'']]],
  ['feather_20nrf52840_20express_44',['Adafruit Feather nRF52840 Express',['../group__boards__feather-nrf52840.html',1,'']]],
  ['feather_20nrf52840_20sense_45',['Adafruit Feather nRF52840 Sense',['../group__boards__feather-nrf52840-sense.html',1,'']]],
  ['feetech_20driver_46',['Feetech driver',['../group__drivers__feetech.html',1,'']]],
  ['fi_47',['Wi-Fi',['../group__net__wifi.html',1,'']]],
  ['fi_20drivers_48',['Wi-Fi drivers',['../group__drivers__netdev__wifi.html',1,'']]],
  ['fib_49',['Forwarding Information Base (FIB)',['../group__net__fib.html',1,'']]],
  ['fido2_20ctap_50',['FIDO2 CTAP',['../group__fido2__ctap__ctap.html',1,'']]],
  ['fido2_20ctap_20cbor_51',['FIDO2 CTAP CBOR',['../group__fido2__ctap__cbor.html',1,'']]],
  ['fido2_20ctap_20crypto_52',['FIDO2 CTAP crypto',['../group__fido2__ctap__crypto.html',1,'']]],
  ['fido2_20ctap_20flash_53',['FIDO2 CTAP flash',['../group__fido2__ctap__mem.html',1,'']]],
  ['fido2_20ctap_20transport_54',['FIDO2 CTAP transport',['../group__fido2__ctap__transport.html',1,'']]],
  ['fido2_20ctap_20utils_55',['FIDO2 CTAP utils',['../group__fido2__ctap__utils.html',1,'']]],
  ['fido2_20ctaphid_56',['FIDO2 CTAPHID',['../group__fido2__ctap__transport__hid.html',1,'']]],
  ['fido2_20fast_20identity_20online_202_57',['FIDO2 - Fast Identity Online 2',['../group__fido2.html',1,'']]],
  ['file_20module_58',['Blob file module',['../group__utils__blob.html',1,'']]],
  ['file_20server_59',['CoAP file server',['../group__net__nanocoap__fileserver.html',1,'']]],
  ['file_20system_60',['file system',['../group__sys__fs__constfs.html',1,'ConstFS static file system'],['../group__sys__fs__devfs.html',1,'DevFS device file system'],['../group__pkg__fatfs.html',1,'FAT file system'],['../group__pkg__littlefs.html',1,'littlefs file system'],['../group__pkg__littlefs2.html',1,'littlefs v2.x.y file system'],['../group__pkg__spiffs.html',1,'SPI flash file system']]],
  ['file_20system_20vfs_20layer_61',['Virtual File System (VFS) layer',['../group__sys__vfs.html',1,'']]],
  ['file_20systems_62',['File systems',['../group__sys__fs.html',1,'']]],
  ['files_63',['files',['../group__cpu__atmega__common.html',1,'Atmel ATmega CPU: common files'],['../group__cpu__avr8__common.html',1,'Atmel AVR-8 CPU: common files']]],
  ['files_20of_20arduino_20zero_20and_20clones_64',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['filter_65',['filter',['../group__sys__bloom.html',1,'Bloom filter'],['../group__net__l2filter.html',1,'Link layer address filter']]],
  ['filter_20compile_20configurations_66',['Link layer address filter compile configurations',['../group__net__l2filter__conf.html',1,'']]],
  ['finder_67',['srf04 ultra sonic range finder',['../group__drivers__srf04.html',1,'']]],
  ['firefly_20board_68',['Firefly Board',['../group__boards__firefly.html',1,'']]],
  ['firmware_69',['Initialization of USB Device Firmware',['../group__sys__riotboot__usb__dfu.html',1,'']]],
  ['firmware_20coap_20transport_70',['SUIT firmware CoAP transport',['../group__sys__suit__transport__coap.html',1,'']]],
  ['firmware_20ota_20mock_20transport_71',['SUIT secure firmware OTA mock transport',['../group__sys__suit__transport__mock.html',1,'']]],
  ['firmware_20ota_20upgrade_20infrastructure_72',['SUIT secure firmware OTA upgrade infrastructure',['../group__sys__suit.html',1,'']]],
  ['firmware_20ota_20upgrade_20storage_73',['SUIT secure firmware OTA upgrade storage',['../group__sys__suit__storage.html',1,'']]],
  ['firmware_20ota_20vfs_20transport_74',['SUIT secure firmware OTA VFS transport',['../group__sys__suit__transport__vfs.html',1,'']]],
  ['firmware_20upgrade_75',['Firmware Upgrade',['../group__usb__dfu.html',1,'DFU - USB Device Firmware Upgrade'],['../group__usbus__dfu.html',1,'USBUS DFU - USB Device Firmware Upgrade']]],
  ['firmware_20worker_20thread_76',['SUIT firmware worker thread',['../group__sys__suit__transport__worker.html',1,'']]],
  ['fit_20memory_20allocator_77',['Two-Level Segregated Fit memory allocator',['../group__pkg__tlsf.html',1,'']]],
  ['fixed_20point_20maths_20library_78',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['flags_79',['Thread Flags',['../group__core__thread__flags.html',1,'']]],
  ['flash_80',['FlashDB: Database for Flash',['../group__pkg__flashdb.html',1,'']]],
  ['flash_81',['flash',['../group__boards__blackpill__stm32f103cb.html',1,'Blackpill STM32F103CB board (128KiB flash)'],['../group__boards__bluepill__stm32f103cb.html',1,'Bluepill STM32F103CB board (128KiB flash)'],['../group__fido2__ctap__mem.html',1,'FIDO2 CTAP flash'],['../group__sys__riotboot__slot.html',1,'Helpers to manipulate partitions (slots) on internal flash'],['../group__drivers__mtd__spi__nor.html',1,'Serial NOR flash']]],
  ['flash_20file_20system_82',['SPI flash file system',['../group__pkg__spiffs.html',1,'']]],
  ['flash_20page_20driver_83',['Flash page driver',['../group__drivers__periph__flashpage.html',1,'']]],
  ['flash_20writer_84',['riotboot flash writer',['../group__sys__riotboot__flashwrite.html',1,'']]],
  ['flashdb_3a_20database_20for_20flash_85',['FlashDB: Database for Flash',['../group__pkg__flashdb.html',1,'']]],
  ['flashpage_20devices_86',['MTD wrapper for Flashpage devices',['../group__drivers__mtd__flashpage.html',1,'']]],
  ['flashwrite_20storage_20backend_87',['riotboot flashwrite storage backend',['../group__sys__suit__storage__flashwrite.html',1,'']]],
  ['flatbuffers_88',['FlatBuffers',['../group__pkg__flatbuffers.html',1,'']]],
  ['fletcher16_89',['Fletcher16',['../group__sys__checksum__fletcher16.html',1,'']]],
  ['fletcher32_90',['Fletcher32',['../group__sys__checksum__fletcher32.html',1,'']]],
  ['fmc_20fsmc_20lcd_20low_20level_20parallel_20interface_20driver_91',['STM32 FMC/FSMC LCD low-level parallel interface driver',['../group__cpu__stm32__lcd__fmc.html',1,'']]],
  ['fmc_20fsmc_20peripheral_20driver_92',['STM32 FMC/FSMC peripheral driver',['../group__cpu__stm32__periph__fmc.html',1,'']]],
  ['fmt_93',['String formatting (fmt)',['../group__sys__fmt.html',1,'']]],
  ['fmt_5ftable_94',['Table extension of the string formatting API (fmt_table)',['../group__sys__fmt__table.html',1,'']]],
  ['focaltech_20ft5x06_20touch_20panel_20driver_95',['FocalTech FT5x06 touch panel driver',['../group__drivers__ft5x06.html',1,'']]],
  ['font_20mineplex_96',['5x5 Font &apos;Mineplex&apos;',['../group__sys__mineplex.html',1,'']]],
  ['for_97',['for',['../group__net__dhcpv6__client__simple__pd.html',1,'gnrc_dhcpv6_client_simple_pd: DHCPv6 client for'],['../group__sys__flash__utils.html',1,'Utility functions, macros, and types for']]],
  ['for_206lowpan_20address_20compression_98',['Contexts for 6LoWPAN address compression',['../group__net__gnrc__sixlowpan__ctx.html',1,'']]],
  ['for_206lowpan_20sfr_99',['Congestion control for 6LoWPAN SFR',['../group__net__gnrc__sixlowpan__frag__sfr__congure.html',1,'']]],
  ['for_20asynchronous_20access_100',['Sock extension for asynchronous access',['../group__net__sock__async.html',1,'']]],
  ['for_20at24cxxx_20family_20of_20i2c_20eeproms_101',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['for_20at25xxx_20family_20of_20spi_20eeproms_102',['MTD wrapper for AT25xxx family of SPI-EEPROMs',['../group__drivers__mtd__at25xxx.html',1,'']]],
  ['for_20atomic_20access_103',['Utility functions for atomic access',['../group__sys__atomic__utils.html',1,'']]],
  ['for_20avr8_104',['stdio wrapper for AVR8',['../group__cpu__avr8__common__stdio__wrapper.html',1,'']]],
  ['for_20common_20events_105',['System Buses for common events',['../group__sys__bus.html',1,'']]],
  ['for_20congure_20tcp_20reno_106',['The send driver methods for CongURE TCP Reno',['../group__sys__congure__reno__methods.html',1,'']]],
  ['for_20debugging_20profiling_107',['Direct pin control for debugging/profiling',['../group__sys__dbgpin.html',1,'']]],
  ['for_20decawave_20dw1000_20transceiver_108',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['for_20demonstration_109',['Talking LEDs - Arduino library for demonstration',['../group__pkg__talking__leds.html',1,'']]],
  ['for_20dos_20line_20endings_20in_20stdio_20uart_110',['Support for DOS line endings in STDIO-UART',['../group__sys__stdio__uart__onlcr.html',1,'']]],
  ['for_20eeprom_111',['Native extra API for EEPROM',['../group__drivers__eeprom__native.html',1,'']]],
  ['for_20efm_20efr_20ezr32_20mcus_112',['Vendor library for EFM/EFR/EZR32 MCUs',['../group__pkg__gecko__sdk.html',1,'']]],
  ['for_20embedded_20systems_113',['Color graphics library for embedded systems',['../group__pkg__ucglib.html',1,'']]],
  ['for_20emulated_20mtd_20devices_114',['MTD wrapper for emulated MTD devices',['../group__drivers__mtd__emulated.html',1,'']]],
  ['for_20encoding_20psa_20keys_20in_20cbor_115',['Module for encoding PSA keys in CBOR',['../group__sys__psa__crypto__cbor__encoder.html',1,'']]],
  ['for_20flash_116',['FlashDB: Database for Flash',['../group__pkg__flashdb.html',1,'']]],
  ['for_20flashpage_20devices_117',['MTD wrapper for Flashpage devices',['../group__drivers__mtd__flashpage.html',1,'']]],
  ['for_20getting_20mac_20address_20out_20of_20atmel_20edbg_118',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['for_20gnrc_119',['Priority packet queue for GNRC',['../group__net__gnrc__priority__pktqueue.html',1,'']]],
  ['for_20gnrc_206lowpan_20brs_120',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['for_20i2c_20spi_20bme680_20sensor_121',['Driver package for I2C/SPI BME680 sensor',['../group__pkg__driver__bme680.html',1,'']]],
  ['for_20internet_20of_20things_122',['Ultra-lightweight Javascript for Internet Of Things',['../group__pkg__jerryscript.html',1,'']]],
  ['for_20ipv6_123',['Neighbor Information Base for IPv6',['../group__net__gnrc__ipv6__nib.html',1,'']]],
  ['for_20ipv6_20dhcpv6_124',['Dynamic Host Configuration Protocol for IPv6 (DHCPv6)',['../group__net__dhcpv6.html',1,'']]],
  ['for_20ipv6_20fragmentation_20extension_125',['Support for IPv6 fragmentation extension',['../group__net__gnrc__ipv6__ext__frag.html',1,'']]],
  ['for_20ipv6_20option_20extension_20headers_126',['Support for IPv6 option extension headers',['../group__net__gnrc__ipv6__ext__opt.html',1,'']]],
  ['for_20ipv6_20over_20x_127',['Stack-independent helpers for IPv6 over X',['../group__net__l2util.html',1,'']]],
  ['for_20ipv6_20routing_20header_20extension_128',['Support for IPv6 routing header extension',['../group__net__gnrc__ipv6__ext__rh.html',1,'']]],
  ['for_20malloc_20and_20friends_129',['Thread-safe wrappers for malloc and friends',['../group__sys__malloc__ts.html',1,'']]],
  ['for_20monochome_20displays_130',['U8G2 graphic library for monochome displays',['../group__pkg__u8g2.html',1,'']]],
  ['for_20msp430_20boards_131',['Common Configuration Snippets for MSP430 boards',['../group__boards__common__msp430.html',1,'']]],
  ['for_20native_132',['for native',['../group__core__sched__native.html',1,'Scheduler for native'],['../group__cpu__native__stdio.html',1,'STDIO for native']]],
  ['for_20netif_133',['Connection State Management for netif',['../group__pkg__nimble__netif__conn.html',1,'']]],
  ['for_20network_20apis_134',['Netopt - Configuration options for network APIs',['../group__net__netopt.html',1,'']]],
  ['for_20nimble_135',['RPL-over-BLE for NimBLE',['../group__pkg__nimble__rpble.html',1,'']]],
  ['for_20nimble_20host_136',['ESP32 Bluetooth LE HCI for NimBLE host',['../group__cpu__esp32__esp__ble__nimble.html',1,'']]],
  ['for_20nrf52840_20socs_137',['IEEE802.15.4 Driver for nRF52840 SoCs',['../group__drivers__nrf52__802154.html',1,'']]],
  ['for_20nrfmin_138',['GNRC adapter for nrfmin',['../group__drivers__nrf5x__nrfmin__gnrc.html',1,'']]],
  ['for_20pointer_20tagging_139',['Helpers for pointer tagging',['../group__sys__ptrtag.html',1,'']]],
  ['for_20ref_20net_5fgnrc_5fnetif_140',['Send queue for @ref net_gnrc_netif',['../group__net__gnrc__netif__pktq.html',1,'']]],
  ['for_20riot_141',['for RIOT',['../group__cpp11-compat.html',1,'C++11 wrapper for RIOT'],['../group__pkg__libcose.html',1,'libcose for RIOT'],['../group__pkg__micro__ecc.html',1,'Micro-ECC for RIOT'],['../group__posix.html',1,'POSIX wrapper for RIOT'],['../group__pkg__qcbor.html',1,'QCBOR for RIOT'],['../group__pkg__relic.html',1,'Relic toolkit for RIOT'],['../group__pkg__tinydtls.html',1,'TinyDTLS for RIOT']]],
  ['for_20riotboot_142',['Magic values for riotboot',['../group__sys__riotboot__magic.html',1,'']]],
  ['for_20rpl_143',['Packet statistics for RPL',['../group__net__netstats__rpl.html',1,'']]],
  ['for_20sam0_20sdhc_20devices_144',['MTD wrapper for SAM0 SDHC devices',['../group__drivers__mtd__sam0__sdhc.html',1,'']]],
  ['for_20sd_20mmc_20devices_145',['MTD wrapper for SD/MMC devices',['../group__drivers__mtd__sdmmc.html',1,'']]],
  ['for_20sdi_2012_20communication_146',['Arduino library for SDI-12 communication',['../group__pkg__arduino__sdi__12.html',1,'']]],
  ['for_20spi_20sd_20cards_147',['MTD wrapper for SPI SD Cards',['../group__drivers__mtd__sdcard.html',1,'']]],
  ['for_20static_20instances_148',['C++ constructor guards for static instances',['../group__sys__cxx__ctor__guards.html',1,'']]],
  ['for_20synchronizing_20with_20transmission_149',['Helpers for synchronizing with transmission.',['../group__net__gnrc__tx__sync.html',1,'']]],
  ['for_20the_20decawave_20impulse_20radio_20ultra_20wideband_20ir_20uwb_20transceiver_20s_150',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['for_20the_20esp32_20c3_20soc_151',['ESP32 SDK Bluetooth library for the ESP32-C3 SoC',['../group__pkg__esp32__sdk__lib__bt__esp32c3.html',1,'']]],
  ['for_20the_20esp32_20mcu_20support_152',['ESP32 SDK for the ESP32 MCU support',['../group__pkg__esp32__sdk.html',1,'']]],
  ['for_20the_20esp32_20soc_153',['ESP32 SDK Bluetooth library for the ESP32 SoC',['../group__pkg__esp32__sdk__lib__bt__esp32.html',1,'']]],
  ['for_20the_20esp32_20soc_20support_154',['ESP32 SDK libraries for the ESP32 SoC support',['../group__pkg__esp32__sdk__lib__phy.html',1,'']]],
  ['for_20the_20esp32_20wifi_20support_155',['ESP32 SDK libraries for the ESP32 WiFi support',['../group__pkg__esp32__sdk__lib__wifi.html',1,'']]],
  ['for_20the_20esp8266_20mcu_20support_156',['ESP8266 RTOS SDK for the ESP8266 MCU support',['../group__pkg__esp8266__sdk.html',1,'']]],
  ['for_20the_20uwb_20core_20driver_20for_20decawave_20dw1000_20transceiver_157',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['for_20usb_20apis_158',['usbopt - Configuration options for USB APIs',['../group__usb__usbopt.html',1,'']]],
  ['for_20volatile_20accesses_159',['Helpers for volatile accesses',['../group__sys__atomic__utils__volatile.html',1,'']]],
  ['for_20wakaama_20package_160',['Platform adaption for Wakaama package',['../group__lwm2m__platform.html',1,'']]],
  ['format_161',['CoRE Link Format',['../group__sys__clif.html',1,'']]],
  ['formatter_20functions_162',['USBUS descriptor formatter functions',['../group__usb__usbus__fmt.html',1,'']]],
  ['formatting_20api_20fmt_5ftable_163',['Table extension of the string formatting API (fmt_table)',['../group__sys__fmt__table.html',1,'']]],
  ['formatting_20fmt_164',['String formatting (fmt)',['../group__sys__fmt.html',1,'']]],
  ['forward_20proxy_165',['GCoAP Forward Proxy',['../group__net__gcoap__forward__proxy.html',1,'']]],
  ['forward_20proxy_20thread_166',['GCoAP Forward Proxy Thread',['../group__net__gcoap__forward__proxy__thread.html',1,'']]],
  ['forwarding_167',['Minimal fragment forwarding',['../group__net__gnrc__sixlowpan__frag__minfwd.html',1,'']]],
  ['forwarding_20information_20base_20fib_168',['Forwarding Information Base (FIB)',['../group__net__fib.html',1,'']]],
  ['forwarding_20table_169',['Forwarding table',['../group__net__gnrc__ipv6__nib__ft.html',1,'']]],
  ['fowler–noll–vo_170',['Fowler–Noll–Vo',['../group__sys__hashes__fnv.html',1,'']]],
  ['fractional_20integer_20operations_171',['Fractional integer operations',['../group__sys__frac.html',1,'']]],
  ['fragment_20forwarding_172',['Minimal fragment forwarding',['../group__net__gnrc__sixlowpan__frag__minfwd.html',1,'']]],
  ['fragment_20recovery_173',['fragment recovery',['../group__net__gnrc__sixlowpan__frag__sfr.html',1,'6LoWPAN selective fragment recovery'],['../group__net__sixlowpan__sfr.html',1,'6LoWPAN selective fragment recovery']]],
  ['fragment_20size_20hint_174',['Fragment size hint',['../group__net__gnrc__sixlowpan__frag__hint.html',1,'']]],
  ['fragmentation_175',['6LoWPAN Fragmentation',['../group__net__gnrc__sixlowpan__frag.html',1,'']]],
  ['fragmentation_20and_20reassembly_20statistics_176',['Fragmentation and reassembly statistics',['../group__net__gnrc__sixlowpan__frag__stats.html',1,'']]],
  ['fragmentation_20buffer_177',['6LoWPAN fragmentation buffer',['../group__net__gnrc__sixlowpan__frag__fb.html',1,'']]],
  ['fragmentation_20extension_178',['fragmentation extension',['../group__net__ipv6__ext__frag.html',1,'IPv6 fragmentation extension'],['../group__net__gnrc__ipv6__ext__frag.html',1,'Support for IPv6 fragmentation extension']]],
  ['frame_20headers_20and_20definitions_179',['IEEE 802.15.4 frame headers and definitions',['../group__net__ieee802154__header.html',1,'']]],
  ['framework_180',['Fake Functions Framework',['../group__pkg__fff.html',1,'']]],
  ['framework_181',['framework',['../group__sys__congure.html',1,'CongURE - A Congestion control framework'],['../group__pkg__paho__mqtt.html',1,'PAHO MQTT framework']]],
  ['framework_20shell_20commands_182',['CongURE test framework shell commands',['../group__sys__congure__test.html',1,'']]],
  ['frdm_20common_183',['NXP FRDM Common',['../group__boards__common__frdm.html',1,'']]],
  ['frdm_20k22f_20board_184',['NXP FRDM-K22F Board',['../group__boards__frdm-k22f.html',1,'']]],
  ['frdm_20k64f_20board_185',['NXP FRDM-K64F Board',['../group__boards__frdm-k64f.html',1,'']]],
  ['frdm_20kl43z_20board_186',['NXP FRDM-KL43Z Board',['../group__boards__frdm-kl43z.html',1,'']]],
  ['frdm_20kw41z_20board_187',['Freescale FRDM-KW41Z Board',['../group__boards__frdm-kw41z.html',1,'']]],
  ['freertos_20corejson_188',['FreeRTOS coreJSON',['../group__pkg__corejson.html',1,'']]],
  ['freescale_20frdm_20kw41z_20board_189',['Freescale FRDM-KW41Z Board',['../group__boards__frdm-kw41z.html',1,'']]],
  ['freqm_190',['FREQM',['../group__drivers__periph__freqm.html',1,'']]],
  ['frequency_20conversion_20layer_191',['ztimer_convert_frac frequency conversion layer',['../group__sys__ztimer__convert__frac.html',1,'']]],
  ['frequency_20conversion_20modules_192',['ztimer frequency conversion modules',['../group__sys__ztimer__convert.html',1,'']]],
  ['friends_193',['Thread-safe wrappers for malloc and friends',['../group__sys__malloc__ts.html',1,'']]],
  ['from_20dresden_20elektronik_194',['from Dresden Elektronik',['../group__boards__deRFmega128.html',1,'deRFmega128 modules from Dresden Elektronik'],['../group__boards__deRFmega256.html',1,'deRFmega256 modules from Dresden Elektronik']]],
  ['fs_20hs_20peripheral_195',['stm32 USB OTG FS/HS peripheral',['../group__cpu__stm32__usbdev.html',1,'']]],
  ['fs_20integration_196',['native fs integration',['../group__sys__fs__native.html',1,'']]],
  ['fsk_20phy_197',['AT86RF215 MR-FSK PHY',['../group__drivers__at86rf215__fsk.html',1,'']]],
  ['fsmc_20lcd_20low_20level_20parallel_20interface_20driver_198',['STM32 FMC/FSMC LCD low-level parallel interface driver',['../group__cpu__stm32__lcd__fmc.html',1,'']]],
  ['fsmc_20peripheral_20driver_199',['STM32 FMC/FSMC peripheral driver',['../group__cpu__stm32__periph__fmc.html',1,'']]],
  ['ft5x06_20touch_20panel_20driver_200',['FocalTech FT5x06 touch panel driver',['../group__drivers__ft5x06.html',1,'']]],
  ['function_201',['expect() utility function',['../group__test__utils__expect.html',1,'']]],
  ['functionalities_202',['Common LwM2M Object functionalities',['../group__lwm2m__objects__common.html',1,'']]],
  ['functions_203',['functions',['../group__sys__imath.html',1,'imath: Integer Math functions'],['../group__sys__div.html',1,'Integer division functions'],['../group__sys__hashes__keyed.html',1,'Keyed cryptographic hash functions'],['../group__net__utils.html',1,'Network helper functions'],['../group__sys__hashes__non__crypto.html',1,'Non-cryptographic hash functions'],['../group__net__sock__util.html',1,'sock utility functions'],['../group__drivers__sx126x__internal.html',1,'SX1261/2/8 and LLCC68 internal functions'],['../group__sys__hashes__unkeyed.html',1,'Unkeyed cryptographic hash functions'],['../group__usb__usbus__fmt.html',1,'USBUS descriptor formatter functions'],['../group__usbus__msc.html',1,'USBUS Mass Storage Class functions'],['../group__sys__vfs__util.html',1,'VFS helper functions']]],
  ['functions_20compile_20configurations_204',['SOCK utility functions compile configurations',['../group__net__sock__util__conf.html',1,'']]],
  ['functions_20for_20atomic_20access_205',['Utility functions for atomic access',['../group__sys__atomic__utils.html',1,'']]],
  ['functions_20framework_206',['Fake Functions Framework',['../group__pkg__fff.html',1,'']]],
  ['functions_20macros_20and_20types_20for_207',['Utility functions, macros, and types for',['../group__sys__flash__utils.html',1,'']]],
  ['functions_20that_20are_20missing_20in_20tt_20string_20h_20tt_208',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['functions_3a_20cipher_209',['PSA Wrapper Functions: Cipher',['../group__sys__psa__crypto__cipher.html',1,'']]],
  ['functions_3a_20ecc_210',['PSA Wrapper Functions: ECC',['../group__sys__psa__crypto__ecc.html',1,'']]],
  ['functions_3a_20hashes_211',['PSA Wrapper Functions: Hashes',['../group__sys__psa__crypto__hashes.html',1,'']]],
  ['functions_3a_20mac_212',['PSA Wrapper Functions: MAC',['../group__sys__psa__crypto__mac.html',1,'']]],
  ['fuzzing_20utilities_213',['FUZZING utilities',['../group__sys__fuzzing.html',1,'']]],
  ['fxos8700_203_20axis_20accelerometer_20magnetometer_214',['FXOS8700 3-axis accelerometer/magnetometer',['../group__drivers__fxos8700.html',1,'']]],
  ['fxos8700_20accelerometer_20magnetometer_20driver_20compile_20configuration_215',['FXOS8700 accelerometer/magnetometer driver compile configuration',['../group__drivers__fxos8700__config.html',1,'']]]
];
