var searchData=
[
  ['k22f_20board_0',['NXP FRDM-K22F Board',['../group__boards__frdm-k22f.html',1,'']]],
  ['k64f_20board_1',['NXP FRDM-K64F Board',['../group__boards__frdm-k64f.html',1,'']]],
  ['kernel_2',['Kernel',['../group__core.html',1,'']]],
  ['kernel_20utilities_3',['Kernel Utilities',['../group__core__util.html',1,'']]],
  ['kernighan_20and_20ritchie_4',['Kernighan and Ritchie',['../group__sys__hashes__kr.html',1,'']]],
  ['key_20derivation_20and_20agreement_5',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['key_20management_6',['Secure Element Key Management',['../group__se__key__management.html',1,'']]],
  ['key_20slot_20management_7',['PSA Crypto Key Slot Management',['../group__sys__psa__crypto__slot__mgmt.html',1,'']]],
  ['keyed_20cryptographic_20hash_20functions_8',['Keyed cryptographic hash functions',['../group__sys__hashes__keyed.html',1,'']]],
  ['keypad_9',['Matrix Keypad',['../group__drivers__matrix__keypad.html',1,'']]],
  ['keys_20in_20cbor_10',['Module for encoding PSA keys in CBOR',['../group__sys__psa__crypto__cbor__encoder.html',1,'']]],
  ['khz_11',['DCF77 long wave receiver with 77,5 kHz',['../group__drivers__dcf77.html',1,'']]],
  ['kinetis_12',['NXP Kinetis',['../group__cpu__kinetis.html',1,'']]],
  ['kinetis_20adc_13',['Kinetis ADC',['../group__cpu__kinetis__adc.html',1,'']]],
  ['kinetis_20bit_20manipulation_20engine_20bme_14',['Kinetis Bit Manipulation Engine (BME)',['../group__cpu__kinetis__bme.html',1,'']]],
  ['kinetis_20cpuid_15',['Kinetis CPUID',['../group__cpu__kinetis__cpuid.html',1,'']]],
  ['kinetis_20gpio_16',['Kinetis GPIO',['../group__cpu__kinetis__gpio.html',1,'']]],
  ['kinetis_20i2c_17',['Kinetis I2C',['../group__cpu__kinetis__i2c.html',1,'']]],
  ['kinetis_20mcg_18',['Kinetis MCG',['../group__cpu__kinetis__mcg.html',1,'']]],
  ['kinetis_20pwm_19',['Kinetis PWM',['../group__cpu__kinetis__pwm.html',1,'']]],
  ['kinetis_20rnga_20',['Kinetis RNGA',['../group__cpu__kinetis__rnga.html',1,'']]],
  ['kinetis_20rtc_21',['Kinetis RTC',['../group__cpu__kinetis__rtc.html',1,'']]],
  ['kinetis_20spi_22',['Kinetis SPI',['../group__cpu__kinetis__spi.html',1,'']]],
  ['kinetis_20timer_23',['Kinetis Timer',['../group__cpu__kinetis__timer.html',1,'']]],
  ['kinetis_20uart_24',['Kinetis UART',['../group__cpu__kinetis__uart.html',1,'']]],
  ['kinetis_20wdog_25',['Kinetis WDOG',['../group__cpu__kinetis__wdog.html',1,'']]],
  ['kit_26',['Kit',['../group__boards__esp32__esp-ethernet-kit.html',1,'ESP32-Ethernet-Kit'],['../group__boards__nrf51dk.html',1,'nRF51DK Development Kit'],['../group__boards__nrf6310.html',1,'NRF6310 (Nordic NRF Hardware Development Kit)'],['../group__boards__waveshare__nrf52840__eval__kit.html',1,'Waveshare nRF52840 Eval Kit']]],
  ['kit_27',['kit',['../group__boards__mbed__lpc1768.html',1,'mbed LPC1768 development kit'],['../group__boards__seeduino__arch-pro.html',1,'Seeeduino Arch Pro development kit'],['../group__boards__slstk3400a.html',1,'Silicon Labs SLSTK3400A starter kit'],['../group__boards__slstk3401a.html',1,'Silicon Labs SLSTK3401A starter kit'],['../group__boards__slstk3402a.html',1,'Silicon Labs SLSTK3402A starter kit'],['../group__boards__slstk3701a.html',1,'Silicon Labs SLSTK3701A starter kit'],['../group__boards__sltb001a.html',1,'Silicon Labs SLTB001A starter kit'],['../group__boards__sltb009a.html',1,'Silicon Labs SLTB009A starter kit'],['../group__boards__common__slwstk6000b.html',1,'Silicon Labs SLWSTK6000B starter kit'],['../group__boards__slwstk6220a.html',1,'Silicon Labs SLWSTK6220A starter kit'],['../group__boards__stk3200.html',1,'Silicon Labs STK3200 starter kit'],['../group__boards__stk3600.html',1,'Silicon Labs STK3600 starter kit'],['../group__boards__stk3700.html',1,'Silicon Labs STK3700 starter kit'],['../group__boards__xg23-pk6068a.html',1,'Silicon Labs xG23-PK6068A starter kit']]],
  ['kit_20v1_200_20board_28',['ESP32-Ethernet-Kit V1.0 Board',['../group__boards__esp32__esp-ethernet-kit-v1__0.html',1,'']]],
  ['kit_20v1_201_20board_29',['ESP32-Ethernet-Kit V1.1 Board',['../group__boards__esp32__esp-ethernet-kit-v1__1.html',1,'']]],
  ['kit_20v1_202_20board_30',['ESP32-Ethernet-Kit V1.2 Board',['../group__boards__esp32__esp-ethernet-kit-v1__2.html',1,'']]],
  ['kit_20v3_31',['ESP-WROVER-KIT V3',['../group__boards__esp32__esp-wrover-kit.html',1,'']]],
  ['kl43z_20board_32',['NXP FRDM-KL43Z Board',['../group__boards__frdm-kl43z.html',1,'']]],
  ['knuth_33',['Donald E. Knuth',['../group__sys__hashes__dek.html',1,'']]],
  ['kw21z_20in_20cpu_20transceiver_20driver_20compile_20configuration_34',['KW41Z, KW21Z in-cpu transceiver driver compile configuration',['../group__drivers__kw41zrf__config.html',1,'']]],
  ['kw22_20board_35',['phyWAVE-KW22 Board',['../group__boards__pba-d-01-kw2x.html',1,'']]],
  ['kw2x_20radio_20driver_36',['KW2x radio-driver',['../group__drivers__kw2xrf.html',1,'']]],
  ['kw2xd_20radio_20driver_20compile_20configuration_37',['CR20A and KW2xD radio driver compile configuration',['../group__drivers__kw2xrf__config.html',1,'']]],
  ['kw41z_38',['PhyNODE KW41Z',['../group__boards__phynode-kw41z.html',1,'']]],
  ['kw41z_20board_39',['KW41Z Board',['../group__boards__frdm-kw41z.html',1,'Freescale FRDM-KW41Z Board'],['../group__boards__usb-kw41z.html',1,'NXP USB-KW41Z Board']]],
  ['kw41z_20common_40',['KW41Z common',['../group__boards__common__kw41z.html',1,'']]],
  ['kw41z_20kw21z_20in_20cpu_20transceiver_20driver_20compile_20configuration_41',['KW41Z, KW21Z in-cpu transceiver driver compile configuration',['../group__drivers__kw41zrf__config.html',1,'']]],
  ['kw41z_20mini_20256kib_20board_42',['openlabs.co kw41z-mini-256kib board',['../group__boards__openlabs-kw41z-mini-256kib.html',1,'']]],
  ['kw41z_20mini_20board_43',['openlabs.co kw41z-mini board',['../group__boards__openlabs-kw41z-mini.html',1,'']]],
  ['kw41z_20radio_20driver_44',['KW41Z radio-driver',['../group__drivers__kw41zrf.html',1,'']]]
];
