var searchData=
[
  ['u_20ber_20l_20ayer_0',['[S]ensor [A]ctuator [U]ber [L]ayer',['../group__drivers__saul.html',1,'']]],
  ['u201_1',['Ublox C030-U201',['../group__boards__ublox-c030-u201.html',1,'']]],
  ['u575zi_20q_2',['STM32 Nucleo-U575ZI-Q',['../group__boards__nucleo-u575zi-q.html',1,'']]],
  ['u585i_20iot02a_3',['STM32 B-U585I-IOT02A',['../group__boards__b-u585i-iot02a.html',1,'']]],
  ['u8g2_20graphic_20library_20for_20monochome_20displays_4',['U8G2 graphic library for monochome displays',['../group__pkg__u8g2.html',1,'']]],
  ['uart_5',['UART',['../group__cpu__cc2538__uart.html',1,'CC2538 UART'],['../group__cpu__kinetis__uart.html',1,'Kinetis UART'],['../group__cpu__qn908x__uart.html',1,'NXP QN908x UART'],['../group__drivers__soft__uart.html',1,'Software UART'],['../group__sys__stdio__uart.html',1,'STDIO over UART'],['../group__sys__stdio__uart__onlcr.html',1,'Support for DOS line endings in STDIO-UART'],['../group__drivers__periph__uart.html',1,'UART']]],
  ['uart_20driver_6',['half-duplex UART Driver',['../group__drivers__uart__half__duplex.html',1,'']]],
  ['ubasic_20interpreter_7',['uBASIC interpreter',['../group__pkg__ubasic.html',1,'']]],
  ['ublox_20c030_20u201_8',['Ublox C030-U201',['../group__boards__ublox-c030-u201.html',1,'']]],
  ['udoo_9',['UDOO',['../group__boards__udoo.html',1,'']]],
  ['udp_10',['UDP',['../group__sys__stdio__udp.html',1,'STDIO over UDP'],['../group__net__gnrc__udp.html',1,'UDP'],['../group__net__udp.html',1,'UDP']]],
  ['udp_20benchmark_11',['UDP benchmark',['../group__test__utils__benchmark__udp.html',1,'']]],
  ['udp_20compile_20configurations_12',['GNRC UDP compile configurations',['../group__net__gnrc__udp__conf.html',1,'']]],
  ['udp_20sock_20api_13',['UDP sock API',['../group__net__sock__udp.html',1,'']]],
  ['uhcp_14',['UHCP',['../group__net__uhcp.html',1,'']]],
  ['ultra_20lightweight_20javascript_20for_20internet_20of_20things_15',['Ultra-lightweight Javascript for Internet Of Things',['../group__pkg__jerryscript.html',1,'']]],
  ['ultra_20sonic_20range_20finder_16',['srf04 ultra sonic range finder',['../group__drivers__srf04.html',1,'']]],
  ['ultra_20wideband_20ir_20uwb_20transceiver_20s_17',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['ultrasonic_20range_20sensor_18',['ultrasonic range sensor',['../group__drivers__srf02.html',1,'SRF02 ultrasonic range sensor'],['../group__drivers__srf08.html',1,'SRF08 ultrasonic range sensor']]],
  ['unaligned_20memory_20access_20methods_19',['unaligned memory access methods',['../group__sys__unaligned.html',1,'']]],
  ['under_20native_20',['Stack backtrace (only under native)',['../group__backtrace.html',1,'']]],
  ['unified_20sensor_20driver_21',['Adafruit Unified Sensor Driver',['../group__pkg__adafruit__sensor.html',1,'']]],
  ['unique_20id_20chip_22',['AT24MAC unique ID chip',['../group__drivers__at24mac.html',1,'']]],
  ['unique_20id_20generator_23',['Locally Unique ID Generator',['../group__sys__luid.html',1,'']]],
  ['unit_24',['AT24CXXX EEPROM unit',['../group__drivers__at24cxxx.html',1,'']]],
  ['unit_20representations_25',['Time unit representations',['../group__sys__time__units.html',1,'']]],
  ['unittests_26',['Unittests',['../group__unittests__cpp.html',1,'C++ Unittests'],['../group__unittests.html',1,'Unittests']]],
  ['universal_20address_20container_27',['Universal Address Container',['../group__sys__universal__address.html',1,'']]],
  ['unix_20address_20families_28',['UNIX address families',['../group__net__af.html',1,'']]],
  ['unkeyed_20cryptographic_20hash_20functions_29',['Unkeyed cryptographic hash functions',['../group__sys__hashes__unkeyed.html',1,'']]],
  ['uno_30',['Arduino Uno',['../group__boards__arduino-uno.html',1,'']]],
  ['upgrade_31',['Upgrade',['../group__usb__dfu.html',1,'DFU - USB Device Firmware Upgrade'],['../group__usbus__dfu.html',1,'USBUS DFU - USB Device Firmware Upgrade']]],
  ['upgrade_20infrastructure_32',['SUIT secure firmware OTA upgrade infrastructure',['../group__sys__suit.html',1,'']]],
  ['upgrade_20storage_33',['SUIT secure firmware OTA upgrade storage',['../group__sys__suit__storage.html',1,'']]],
  ['uri_20parser_34',['A minimal, non-destructive URI parser',['../group__sys__uri__parser.html',1,'']]],
  ['uri_20template_20processor_35',['URI template processor',['../group__sys__ut__process.html',1,'']]],
  ['usage_20monitor_36',['Heap Memory Usage Monitor',['../group__sys__malloc__monitor.html',1,'']]],
  ['usage_20monitor_20internals_37',['Heap Memory Usage Monitor internals',['../group__sys__malloc__monitor__internals.html',1,'']]],
  ['usage_20tables_38',['USB HID usage tables',['../group__usb__hid__usage.html',1,'']]],
  ['usb_39',['USB',['../group__usb.html',1,'']]],
  ['usb_20apis_40',['usbopt - Configuration options for USB APIs',['../group__usb__usbopt.html',1,'']]],
  ['usb_20cdc_20acm_41',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]],
  ['usb_20cdc_20acm_20internals_42',['Board reset via USB CDC ACM internals',['../group__sys__usb__board__reset__internal.html',1,'']]],
  ['usb_20cdc_20acm_20tinyusb_43',['STDIO over USB CDC-ACM (tinyUSB)',['../group__pkg__tinyusb__stdio__cdc__acm.html',1,'']]],
  ['usb_20communications_20device_20class_44',['USB communications device class',['../group__usb__cdc.html',1,'CDC - USB communications device class'],['../group__usb__hid.html',1,'HID - USB communications device class']]],
  ['usb_20descriptors_45',['USB descriptors',['../group__usb__descriptor.html',1,'']]],
  ['usb_20device_20driver_20api_46',['usbdev - USB Device Driver API',['../group__drivers__periph__usbdev.html',1,'']]],
  ['usb_20device_20firmware_47',['Initialization of USB Device Firmware',['../group__sys__riotboot__usb__dfu.html',1,'']]],
  ['usb_20device_20firmware_20upgrade_48',['USB Device Firmware Upgrade',['../group__usb__dfu.html',1,'DFU - USB Device Firmware Upgrade'],['../group__usbus__dfu.html',1,'USBUS DFU - USB Device Firmware Upgrade']]],
  ['usb_20dongle_49',['nRF52840 MDK USB Dongle',['../group__boards__nrf52840-mdk-dongle.html',1,'']]],
  ['usb_20hid_20descriptor_20helpers_50',['USB HID descriptor helpers',['../group__usb__hid__descriptor.html',1,'']]],
  ['usb_20hid_20usage_20tables_51',['USB HID usage tables',['../group__usb__hid__usage.html',1,'']]],
  ['usb_20kw41z_20board_52',['NXP USB-KW41Z Board',['../group__boards__usb-kw41z.html',1,'']]],
  ['usb_20otg_20board_53',['ESP32-S3-USB-OTG Board',['../group__boards__esp32s3__usb__otg.html',1,'']]],
  ['usb_20otg_20fs_20hs_20peripheral_54',['stm32 USB OTG FS/HS peripheral',['../group__cpu__stm32__usbdev.html',1,'']]],
  ['usb_20peripheral_55',['sam0 USB peripheral',['../group__cpu__sam0__common__usb.html',1,'']]],
  ['usb_20peripheral_20compile_20time_20configurations_56',['USB peripheral compile time configurations',['../group__usb__conf.html',1,'']]],
  ['usb_20peripheral_20implementation_57',['NRF usb peripheral implementation',['../group__cpu__nrf52__nrfusb.html',1,'']]],
  ['usbdev_20mockup_20device_58',['USBdev mockup device',['../group__drivers__usbdev__mock.html',1,'']]],
  ['usbdev_20usb_20device_20driver_20api_59',['usbdev - USB Device Driver API',['../group__drivers__periph__usbdev.html',1,'']]],
  ['usbopt_20configuration_20options_20for_20usb_20apis_60',['usbopt - Configuration options for USB APIs',['../group__usb__usbopt.html',1,'']]],
  ['usbus_61',['STDIO over CDC ACM (usbus)',['../group__usbus__cdc__acm__stdio.html',1,'']]],
  ['usbus_20cdc_20abstract_20control_20model_62',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['usbus_20cdc_20acm_20compile_20time_20configurations_63',['USBUS CDC ACM compile time configurations',['../group__usbus__cdc__acm__conf.html',1,'']]],
  ['usbus_20cdc_20acm_20usbus_20cdc_20abstract_20control_20model_64',['USBUS CDC ACM - USBUS CDC abstract control model',['../group__usbus__cdc__acm.html',1,'']]],
  ['usbus_20cdc_20ecm_20usbus_20cdc_20ethernet_20control_20model_65',['USBUS CDC ECM - USBUS CDC ethernet control model',['../group__usbus__cdc__ecm.html',1,'']]],
  ['usbus_20cdc_20ethernet_20control_20model_66',['USBUS CDC ECM - USBUS CDC ethernet control model',['../group__usbus__cdc__ecm.html',1,'']]],
  ['usbus_20compile_20time_20configurations_67',['USBUS compile time configurations',['../group__usb__usbus__conf.html',1,'']]],
  ['usbus_20descriptor_20formatter_20functions_68',['USBUS descriptor formatter functions',['../group__usb__usbus__fmt.html',1,'']]],
  ['usbus_20device_20and_20endpoint_20manager_69',['USBUS device and endpoint manager',['../group__usb__usbus.html',1,'']]],
  ['usbus_20dfu_20usb_20device_20firmware_20upgrade_70',['USBUS DFU - USB Device Firmware Upgrade',['../group__usbus__dfu.html',1,'']]],
  ['usbus_20hid_71',['USBUS HID',['../group__usbus__hid.html',1,'']]],
  ['usbus_20hid_20io_72',['USBUS HID IO',['../group__usbus__hid__io.html',1,'']]],
  ['usbus_20mass_20storage_20class_20functions_73',['USBUS Mass Storage Class functions',['../group__usbus__msc.html',1,'']]],
  ['user_20mode_20gpio_20driver_74',['Linux User Mode GPIO Driver',['../group__drivers__gpio__linux.html',1,'']]],
  ['user_20mode_20spi_20driver_75',['Linux User Mode SPI Driver',['../group__drivers__spidev__linux.html',1,'']]],
  ['using_20shifts_76',['conversion using shifts',['../group__sys__ztimer__convert__shift.html',1,'']]],
  ['using_20wakaama_77',['LwM2M Client using Wakaama',['../group__lwm2m__client.html',1,'']]],
  ['utensor_78',['uTensor',['../group__pkg__utensor.html',1,'']]],
  ['utilities_79',['Utilities',['../group__core__util.html',1,'Kernel Utilities'],['../group__utils.html',1,'Utilities']]],
  ['utilities_80',['utilities',['../group__sys__analog__util.html',1,'Analog data conversion utilities'],['../group__sys__fuzzing.html',1,'FUZZING utilities'],['../group__sys__math.html',1,'Math libraries and utilities']]],
  ['utilities_20to_20influence_20the_20order_20of_20auto_20initialized_20modules_81',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['utility_82',['ztimer overhead utility',['../group__sys__ztimer__overhead.html',1,'']]],
  ['utility_20function_83',['expect() utility function',['../group__test__utils__expect.html',1,'']]],
  ['utility_20functions_84',['sock utility functions',['../group__net__sock__util.html',1,'']]],
  ['utility_20functions_20compile_20configurations_85',['SOCK utility functions compile configurations',['../group__net__sock__util__conf.html',1,'']]],
  ['utility_20functions_20for_20atomic_20access_86',['Utility functions for atomic access',['../group__sys__atomic__utils.html',1,'']]],
  ['utility_20functions_20macros_20and_20types_20for_87',['Utility functions, macros, and types for',['../group__sys__flash__utils.html',1,'']]],
  ['utility_20functions_20that_20are_20missing_20in_20tt_20string_20h_20tt_88',['Utility functions that are missing in &lt;tt&gt;string.h&lt;/tt&gt;',['../group__sys__string__utils.html',1,'']]],
  ['utils_89',['GPIO I/O Utils',['../group__gpio__util.html',1,'']]],
  ['utils_90',['FIDO2 CTAP utils',['../group__fido2__ctap__utils.html',1,'']]],
  ['utils_20result_20output_20helpers_91',['Test Utils Result Output Helpers',['../group__turo__helpers.html',1,'']]],
  ['utils_20result_20output_20implementation_20api_92',['Test Utils Result Output Implementation API',['../group__turo__API.html',1,'']]],
  ['utlist_93',['utlist',['../group__sys__ut.html',1,'']]],
  ['uuid_20s_94',['RFC 4122 compliant UUID&apos;s',['../group__sys__uuid.html',1,'']]],
  ['uv_20ambient_20light_20proximity_20sensors_95',['Si1145/6/7 UV/Ambient light/Proximity sensors',['../group__drivers__si114x.html',1,'']]],
  ['uv_20index_20ambient_20light_20sensor_20with_20i2c_96',['Si1133 UV Index/Ambient Light Sensor with I2C',['../group__drivers__si1133.html',1,'']]],
  ['uv_20sensor_97',['VEML6070 UV sensor',['../group__drivers__veml6070.html',1,'']]],
  ['uwb_20core_20driver_20for_20decawave_20dw1000_20transceiver_98',['Driver implementation for the uwb-core driver for Decawave DW1000 transceiver',['../group__pkg__uwb__dw1000.html',1,'']]],
  ['uwb_20transceiver_20s_99',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['uzlib_100',['uzlib',['../group__pkg__uzlib.html',1,'']]]
];
