var searchData=
[
  ['w_0',['Raspberry Pi Pico W',['../group__boards__rpi__pico__w.html',1,'']]],
  ['w5100_20ethernet_20driver_1',['W5100 ethernet driver',['../group__drivers__w5100.html',1,'']]],
  ['w5100_20ethernet_20shield_20driver_2',['W5100 Ethernet Shield driver',['../group__drivers__shield__w5100.html',1,'']]],
  ['w5500_20ethernet_20driver_3',['W5500 ethernet driver',['../group__drivers__w5500.html',1,'']]],
  ['waiting_20low_20level_20helpers_4',['Busy Waiting low-level helpers',['../group__busy__wait.html',1,'']]],
  ['wakaama_5',['LwM2M Client using Wakaama',['../group__lwm2m__client.html',1,'']]],
  ['wakaama_20lwm2m_20client_20configuration_6',['Wakaama LwM2M Client configuration',['../group__lwm2m__client__config.html',1,'']]],
  ['wakaama_20lwm2m_20platform_20adaption_7',['Wakaama LwM2M platform adaption',['../group__lwm2m__platform__conf.html',1,'']]],
  ['wakaama_20package_8',['Platform adaption for Wakaama package',['../group__lwm2m__platform.html',1,'']]],
  ['wan_201300_9',['Arduino MKR WAN 1300',['../group__boards__arduino-mkrwan1300.html',1,'']]],
  ['waspmote_20pro_20v1_202_10',['Waspmote PRO v1.2',['../group__boards__waspmote-pro.html',1,'']]],
  ['watch_11',['ztimer stop watch',['../group__sys__ztimer__stopwatch.html',1,'']]],
  ['watchdog_20timer_20wdt_12',['NXP QN908x Watchdog timer (WDT)',['../group__cpu__qn908x__wdt.html',1,'']]],
  ['wave_20receiver_20with_2077_205_20khz_13',['DCF77 long wave receiver with 77,5 kHz',['../group__drivers__dcf77.html',1,'']]],
  ['waveshare_20nrf52840_20eval_20kit_14',['Waveshare nRF52840 Eval Kit',['../group__boards__waveshare__nrf52840__eval__kit.html',1,'']]],
  ['wb55_15',['STM32 p-nucleo-wb55',['../group__boards__p-nucleo-wb55.html',1,'']]],
  ['wdog_16',['Kinetis WDOG',['../group__cpu__kinetis__wdog.html',1,'']]],
  ['wdt_17',['WDT',['../group__cpu__qn908x__wdt.html',1,'NXP QN908x Watchdog timer (WDT)'],['../group__drivers__periph__wdt.html',1,'WDT']]],
  ['wdt_20compile_20configurations_18',['WDT compile configurations',['../group__drivers__periph__wdt__conf.html',1,'']]],
  ['weact_20f401cc_20board_19',['WeAct-F401CC board',['../group__boards__weact-f401cc.html',1,'']]],
  ['weact_20f401ce_20board_20',['WeAct-F401CE board',['../group__boards__weact-f401ce.html',1,'']]],
  ['weact_20f411ce_20board_21',['WeAct-F411CE board',['../group__boards__weact-f411ce.html',1,'']]],
  ['weact_20f4x1cx_20common_20code_22',['WeAct-F4x1Cx common code',['../group__boards__common__weact-f4x1cx.html',1,'']]],
  ['weact_20g030f6_20board_23',['WeAct-G030F6 board',['../group__boards__weact-g030f6.html',1,'']]],
  ['webassembly_20micro_20runtime_24',['WebAssembly Micro Runtime',['../group__pkg__wamr.html',1,'']]],
  ['wemos_20arduino_20zero_20clone_25',['WeMos Arduino Zero Clone',['../group__boards__wemos-zero.html',1,'']]],
  ['wemos_20esp32_20c3_20mini_26',['Wemos ESP32-C3 mini',['../group__boards__esp32c3__wemos__mini.html',1,'']]],
  ['wemos_20lolin_20d32_20pro_27',['Wemos LOLIN D32 Pro',['../group__boards__esp32__wemos-lolin-d32-pro.html',1,'']]],
  ['wemos_20s2_20mini_20board_28',['Wemos S2 mini Board',['../group__boards__esp32s2-wemos-mini.html',1,'']]],
  ['white_20e_20paper_20e_20ink_20spi_20display_20driver_29',['Generic black/white e-paper/e-ink SPI display driver.',['../group__drivers__epd__bw__spi.html',1,'']]],
  ['whitelist_30',['IPv6 address whitelist',['../group__net__gnrc__ipv6__whitelist.html',1,'']]],
  ['whitelisting_20compile_20configurations_31',['GNRC IPv6 address whitelisting compile configurations',['../group__net__gnrc__ipv6__whitelist__conf.html',1,'']]],
  ['who_20advertises_20to_20the_20world_32',['Skald, who advertises to the world',['../group__ble__skald.html',1,'']]],
  ['wi_20fi_33',['Wi-Fi',['../group__net__wifi.html',1,'']]],
  ['wi_20fi_20drivers_34',['Wi-Fi drivers',['../group__drivers__netdev__wifi.html',1,'']]],
  ['wideband_20ir_20uwb_20transceiver_20s_35',['Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)',['../group__pkg__uwb__core.html',1,'']]],
  ['wifi_36',['Adafruit Feather M0 WiFi',['../group__boards__feather-m0-wifi.html',1,'']]],
  ['wifi_20esp8266_20dev_37',['Olimex MOD-WIFI-ESP8266-DEV',['../group__boards__esp8266__olimex-mod.html',1,'']]],
  ['wifi_20lora_2032_20v2_20boards_38',['Heltec WiFi LoRa 32 V2 boards',['../group__boards__esp32__heltec-lora32-v2.html',1,'']]],
  ['wifi_20module_20driver_39',['ATWINC15x0 WiFi module driver',['../group__drivers__atwinc15x0.html',1,'']]],
  ['wifi_20module_20vendor_20driver_20package_40',['ATWINC15x0 WiFi Module Vendor Driver Package',['../group__pkg__driver__atwinc15x0.html',1,'']]],
  ['wifi_20netdev_20interface_41',['ESP-WiFi netdev interface',['../group__cpu__esp__common__esp__wifi.html',1,'']]],
  ['wifi_20support_42',['ESP32 SDK libraries for the ESP32 WiFi support',['../group__pkg__esp32__sdk__lib__wifi.html',1,'']]],
  ['wifis_20access_20points_43',['List of scanned WiFis access points',['../group__net__wifi__scan__list.html',1,'']]],
  ['wire_20can_20transceiver_44',['NCV7356 Single Wire CAN Transceiver',['../group__drivers__ncv7356.html',1,'']]],
  ['wireless_20access_20points_45',['Scan List - List of wireless access points',['../group__net__l2scanlist.html',1,'']]],
  ['with_2077_205_20khz_46',['DCF77 long wave receiver with 77,5 kHz',['../group__drivers__dcf77.html',1,'']]],
  ['with_20abe_47',['gnrc_sixlowpan_frag_sfr_congure_abe: TCP Reno with ABE',['../group__net__gnrc__sixlowpan__frag__sfr__congure__abe.html',1,'']]],
  ['with_20additional_20data_48',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['with_20c11_20atomics_49',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['with_20eeprom_50',['AT30TSE75x temperature sensor with EEPROM',['../group__drivers__at30tse75x.html',1,'']]],
  ['with_20event_20api_51',['Asynchronous sock with event API',['../group__net__sock__async__event.html',1,'']]],
  ['with_20i2c_52',['Si1133 UV Index/Ambient Light Sensor with I2C',['../group__drivers__si1133.html',1,'']]],
  ['with_20i2c_20interface_53',['MCP47xx DAC with I2C interface',['../group__drivers__mcp47xx.html',1,'']]],
  ['with_20isr_20pipe_54',['Read timeouts with ISR pipe',['../group__isr__pipe__read__timeout.html',1,'']]],
  ['with_20json_55',['Test result output with JSON',['../group__test__utils__result__output__json.html',1,'']]],
  ['with_20samd21_56',['SenseBox MCU with SAMD21',['../group__boards__sensebox__samd21.html',1,'']]],
  ['with_20tft_57',['Sipeed Longan Nano with TFT',['../group__boards__sipeed__longan__nano__tft.html',1,'']]],
  ['with_20transmission_58',['Helpers for synchronizing with transmission.',['../group__net__gnrc__tx__sync.html',1,'']]],
  ['wl55jc_59',['STM32 Nucleo-WL55JC',['../group__boards__nucleo-wl55jc.html',1,'']]],
  ['wolfssl_20embedded_20ssl_20tls_20library_60',['WolfSSL Embedded SSL/TLS library',['../group__pkg__wolfssl.html',1,'']]],
  ['worker_20thread_61',['SUIT firmware worker thread',['../group__sys__suit__transport__worker.html',1,'']]],
  ['world_62',['Skald, who advertises to the world',['../group__ble__skald.html',1,'']]],
  ['wrapper_63',['PSA Crypto Secure Element Wrapper',['../group__sys__psa__crypto__se__driver.html',1,'']]],
  ['wrapper_64',['wrapper',['../group__sys__ztimer64__xtimer__compat.html',1,'ztimer64_xtimer_compat: 64 Bit xtimer wrapper'],['../group__sys__ztimer__xtimer__compat.html',1,'ztimer_xtimer_compat: xtimer wrapper']]],
  ['wrapper_20compile_20configurations_65',['POSIX wrapper compile configurations',['../group__config__posix.html',1,'']]],
  ['wrapper_20for_20at24cxxx_20family_20of_20i2c_20eeproms_66',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['wrapper_20for_20at25xxx_20family_20of_20spi_20eeproms_67',['MTD wrapper for AT25xxx family of SPI-EEPROMs',['../group__drivers__mtd__at25xxx.html',1,'']]],
  ['wrapper_20for_20avr8_68',['stdio wrapper for AVR8',['../group__cpu__avr8__common__stdio__wrapper.html',1,'']]],
  ['wrapper_20for_20emulated_20mtd_20devices_69',['MTD wrapper for emulated MTD devices',['../group__drivers__mtd__emulated.html',1,'']]],
  ['wrapper_20for_20flashpage_20devices_70',['MTD wrapper for Flashpage devices',['../group__drivers__mtd__flashpage.html',1,'']]],
  ['wrapper_20for_20riot_71',['wrapper for RIOT',['../group__cpp11-compat.html',1,'C++11 wrapper for RIOT'],['../group__posix.html',1,'POSIX wrapper for RIOT']]],
  ['wrapper_20for_20sam0_20sdhc_20devices_72',['MTD wrapper for SAM0 SDHC devices',['../group__drivers__mtd__sam0__sdhc.html',1,'']]],
  ['wrapper_20for_20sd_20mmc_20devices_73',['MTD wrapper for SD/MMC devices',['../group__drivers__mtd__sdmmc.html',1,'']]],
  ['wrapper_20for_20spi_20sd_20cards_74',['MTD wrapper for SPI SD Cards',['../group__drivers__mtd__sdcard.html',1,'']]],
  ['wrapper_20functions_3a_20cipher_75',['PSA Wrapper Functions: Cipher',['../group__sys__psa__crypto__cipher.html',1,'']]],
  ['wrapper_20functions_3a_20ecc_76',['PSA Wrapper Functions: ECC',['../group__sys__psa__crypto__ecc.html',1,'']]],
  ['wrapper_20functions_3a_20hashes_77',['PSA Wrapper Functions: Hashes',['../group__sys__psa__crypto__hashes.html',1,'']]],
  ['wrapper_20functions_3a_20mac_78',['PSA Wrapper Functions: MAC',['../group__sys__psa__crypto__mac.html',1,'']]],
  ['wrappers_20for_20malloc_20and_20friends_79',['Thread-safe wrappers for malloc and friends',['../group__sys__malloc__ts.html',1,'']]],
  ['writer_80',['riotboot flash writer',['../group__sys__riotboot__flashwrite.html',1,'']]],
  ['wroom_2032_20boards_81',['Generic ESP32-WROOM-32 boards',['../group__boards__esp32__wroom-32.html',1,'']]],
  ['wrover_20kit_20v3_82',['ESP-WROVER-KIT V3',['../group__boards__esp32__esp-wrover-kit.html',1,'']]],
  ['ws2812_20sk6812_20rgb_20led_20neopixel_83',['WS2812/SK6812 RGB LED (NeoPixel)',['../group__drivers__ws281x.html',1,'']]],
  ['wt32_20sc01_20plus_84',['ESP32-S3 WT32-SC01 Plus',['../group__boards__esp32s3__wt32__sc01__plus.html',1,'']]]
];
