var searchData=
[
  ['g030f6_20board_0',['WeAct-G030F6 board',['../group__boards__weact-g030f6.html',1,'']]],
  ['g070rb_1',['STM32 Nucleo-G070RB',['../group__boards__nucleo-g070rb.html',1,'']]],
  ['g071rb_2',['STM32 Nucleo-G071RB',['../group__boards__nucleo-g071rb.html',1,'']]],
  ['g2xx_20mcu_20family_3',['MSP430 F2xx/G2xx MCU family',['../group__cpu__msp430__f2xx__g2xx.html',1,'']]],
  ['g431rb_4',['STM32 Nucleo-G431RB',['../group__boards__nucleo-g431rb.html',1,'']]],
  ['g474re_5',['STM32 Nucleo-G474RE',['../group__boards__nucleo-g474re.html',1,'']]],
  ['gas_20sensor_6',['SGP30 Gas Sensor',['../group__drivers__sgp30.html',1,'']]],
  ['gas_20sensor_7',['BME680 Temperature/Humidity/Pressure/Gas sensor',['../group__drivers__bme680.html',1,'']]],
  ['gas_20sensor_8',['CCS 811 digital gas sensor',['../group__drivers__ccs811.html',1,'']]],
  ['gather_20io_9',['iolist scatter / gather IO',['../group__sys__iolist.html',1,'']]],
  ['gba_10',['GBA',['../group__boards__gba__cartridge.html',1,'']]],
  ['gbas_20arm7tdmi_11',['GBAs ARM7TDMI',['../group__cpu__arm7tdmi__gba.html',1,'']]],
  ['gcoap_12',['GCoAP',['../group__net__gcoap.html',1,'']]],
  ['gcoap_20compile_20configurations_13',['GCoAP compile configurations',['../group__net__gcoap__conf.html',1,'']]],
  ['gcoap_20dns_20over_20coap_20client_20configuration_14',['GCoAP DNS over CoAP client configuration',['../group__gcoap__dns__config.html',1,'']]],
  ['gcoap_20forward_20proxy_15',['GCoAP Forward Proxy',['../group__net__gcoap__forward__proxy.html',1,'']]],
  ['gcoap_20forward_20proxy_20thread_16',['GCoAP Forward Proxy Thread',['../group__net__gcoap__forward__proxy__thread.html',1,'']]],
  ['gd32_20risc_20v_20board_17',['SeeedStudio GD32 RISC-V board',['../group__boards__seeedstudio-gd32.html',1,'']]],
  ['gd32v_18',['GD32V',['../group__cpu__gd32v.html',1,'']]],
  ['gd32v_20common_20configuration_19',['GD32V Common Configuration',['../group__boards__common__gd32v.html',1,'']]],
  ['gd32vf103c_20start_20',['GD32VF103C-START',['../group__boards__gd32vf103c__start.html',1,'']]],
  ['gemm_20general_20matrix_20multiplication_20library_21',['GEMM (General Matrix Multiplication) library',['../group__pkg__gemmlowp.html',1,'']]],
  ['general_20matrix_20multiplication_20library_22',['GEMM (General Matrix Multiplication) library',['../group__pkg__gemmlowp.html',1,'']]],
  ['general_20purpose_20i_20o_23',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['general_20purpose_20timer_24',['CC2538 General Purpose Timer',['../group__cpu__cc2538__gptimer.html',1,'']]],
  ['generator_25',['Locally Unique ID Generator',['../group__sys__luid.html',1,'']]],
  ['generator_26',['generator',['../group__pkg__qr-code-generator.html',1,'QR Code generator'],['../group__sys__random__shaxprng.html',1,'SHAX random number generator']]],
  ['generic_20api_27',['generic API',['../group__drivers__disp__dev.html',1,'Display device generic API'],['../group__drivers__screen__dev.html',1,'Screen device generic API'],['../group__drivers__touch__dev.html',1,'Touch device generic API']]],
  ['generic_20black_20white_20e_20paper_20e_20ink_20spi_20display_20driver_28',['Generic black/white e-paper/e-ink SPI display driver.',['../group__drivers__epd__bw__spi.html',1,'']]],
  ['generic_20ble_20defines_29',['Generic BLE defines',['../group__ble__defs.html',1,'']]],
  ['generic_20cc2538_20cc2592_20dk_20board_30',['Generic CC2538-CC2592-DK Board',['../group__boards__generic__cc2538__cc2592__dk.html',1,'']]],
  ['generic_20esp32_20wroom_2032_20boards_31',['Generic ESP32-WROOM-32 boards',['../group__boards__esp32__wroom-32.html',1,'']]],
  ['generic_20gnrc_20network_20stack_32',['Generic (GNRC) network stack',['../group__net__gnrc.html',1,'']]],
  ['generic_20network_20interface_20header_33',['Generic network interface header',['../group__net__gnrc__netif__hdr.html',1,'']]],
  ['generic_20pseudomodules_34',['Generic pseudomodules',['../group__pseudomodules.html',1,'']]],
  ['gesture_20recognition_35',['Touch device gesture recognition',['../group__drivers__touch__dev__gestures.html',1,'']]],
  ['getting_20mac_20address_20out_20of_20atmel_20edbg_36',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['ghz_20radio_20debug_20pins_37',['STM32WL Sub-GHz Radio debug pins',['../group__cpu__stm32__wl__debug__subghz__radio.html',1,'']]],
  ['ghz_20spi_20debug_20pins_38',['STM32WL Sub-GHz SPI debug pins',['../group__cpu__stm32__wl__debug__subghz__spi.html',1,'']]],
  ['ghz_20transceiver_20driver_39',['GHz transceiver driver',['../group__drivers__cc110x.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver'],['../group__drivers__cc110x__config.html',1,'CC1100/CC1100e/CC1101 Sub-GHz transceiver driver']]],
  ['ghz_20trasceiver_20driver_40',['NRF24L01+ (NG) 2.4 GHz trasceiver driver',['../group__drivers__nrf24l01p__ng.html',1,'']]],
  ['gnrc_41',['GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC'],['../group__net__gnrc__priority__pktqueue.html',1,'Priority packet queue for GNRC']]],
  ['gnrc_206lowpan_20brs_42',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['gnrc_206lowpan_20compile_20configurations_43',['GNRC 6LoWPAN compile configurations',['../group__net__gnrc__sixlowpan__config.html',1,'']]],
  ['gnrc_20adapter_20for_20nrfmin_44',['GNRC adapter for nrfmin',['../group__drivers__nrf5x__nrfmin__gnrc.html',1,'']]],
  ['gnrc_20communication_20interface_45',['GNRC communication interface',['../group__net__gnrc__netapi.html',1,'']]],
  ['gnrc_20compile_20configurations_46',['GNRC compile configurations',['../group__net__gnrc__conf.html',1,'']]],
  ['gnrc_20gomach_20compile_20configuration_47',['GNRC GoMacH compile configuration',['../group__net__gnrc__gomach__conf.html',1,'']]],
  ['gnrc_20ipv6_20address_20blacklisting_20compile_20configurations_48',['GNRC IPv6 address blacklisting compile configurations',['../group__net__gnrc__ipv6__blacklist__conf.html',1,'']]],
  ['gnrc_20ipv6_20address_20whitelisting_20compile_20configurations_49',['GNRC IPv6 address whitelisting compile configurations',['../group__net__gnrc__ipv6__whitelist__conf.html',1,'']]],
  ['gnrc_20ipv6_20compile_20configurations_50',['GNRC IPv6 compile configurations',['../group__net__gnrc__ipv6__conf.html',1,'']]],
  ['gnrc_20ipv6_20extension_20header_20compile_20configurations_51',['GNRC IPv6 extension header compile configurations',['../group__net__gnrc__ipv6__ext__conf.html',1,'']]],
  ['gnrc_20ipv6_20nib_20compile_20configurations_52',['GNRC IPv6 NIB compile configurations',['../group__net__gnrc__ipv6__nib__conf.html',1,'']]],
  ['gnrc_20lorawan_53',['GNRC LoRaWAN',['../group__net__gnrc__lorawan.html',1,'']]],
  ['gnrc_20lorawan_20compile_20configurations_54',['GNRC LoRaWAN compile configurations',['../group__net__gnrc__lorawan__conf.html',1,'']]],
  ['gnrc_20lwmac_20compile_20configurations_55',['GNRC LWMAC compile configurations',['../group__net__gnrc__lwmac__conf.html',1,'']]],
  ['gnrc_20mac_20compile_20configurations_56',['GNRC MAC compile configurations',['../group__net__gnrc__mac__conf.html',1,'']]],
  ['gnrc_20netif_20drivers_20auto_20initialization_57',['GNRC netif drivers auto-initialization',['../group__sys__auto__init__gnrc__netif.html',1,'']]],
  ['gnrc_20netif_20implementation_58',['GNRC netif Implementation',['../group__pkg__nimble__netif.html',1,'']]],
  ['gnrc_20network_20interface_20configurations_59',['GNRC network interface configurations',['../group__net__gnrc__netif__conf.html',1,'']]],
  ['gnrc_20network_20stack_60',['Generic (GNRC) network stack',['../group__net__gnrc.html',1,'']]],
  ['gnrc_20pktbuf_20compile_20configurations_61',['GNRC PKTBUF compile configurations',['../group__net__gnrc__pktbuf__conf.html',1,'']]],
  ['gnrc_20pktdump_20compile_20configurations_62',['GNRC PKTDUMP compile configurations',['../group__net__gnrc__pktdump__conf.html',1,'']]],
  ['gnrc_20sock_20implementation_20compile_20configurations_63',['GNRC sock implementation compile configurations',['../group__net__gnrc__sock__conf.html',1,'']]],
  ['gnrc_20specific_20implementation_20of_20the_20sock_20api_64',['GNRC-specific implementation of the sock API',['../group__net__gnrc__sock.html',1,'']]],
  ['gnrc_20tcp_20compile_20configurations_65',['GNRC TCP compile configurations',['../group__net__gnrc__tcp__conf.html',1,'']]],
  ['gnrc_20udp_20compile_20configurations_66',['GNRC UDP compile configurations',['../group__net__gnrc__udp__conf.html',1,'']]],
  ['gnrc_5fdhcpv6_5fclient_3a_20basic_20dhcpv6_20client_20implementation_20in_20gnrc_67',['gnrc_dhcpv6_client: Basic DHCPv6 client implementation in GNRC',['../group__net__gnrc__dhcpv6__client.html',1,'']]],
  ['gnrc_5fdhcpv6_5fclient_5f6lbr_3a_20basic_20client_20for_20gnrc_206lowpan_20brs_68',['gnrc_dhcpv6_client_6lbr: Basic client for GNRC 6LoWPAN BRs',['../group__net__gnrc__dhcpv6__client__6lbr.html',1,'']]],
  ['gnrc_5fdhcpv6_5fclient_5fsimple_5fpd_3a_20dhcpv6_20client_20for_69',['gnrc_dhcpv6_client_simple_pd: DHCPv6 client for',['../group__net__dhcpv6__client__simple__pd.html',1,'']]],
  ['gnrc_5fnettype_3a_20protocol_20type_70',['gnrc_nettype: Protocol type',['../group__net__gnrc__nettype.html',1,'']]],
  ['gnrc_5fnettype_5fccn_71',['gnrc_nettype_ccn',['../group__net__gnrc__nettype__ccn.html',1,'']]],
  ['gnrc_5fnettype_5fgomac_72',['gnrc_nettype_gomac',['../group__net__gnrc__nettype__gomac.html',1,'']]],
  ['gnrc_5fnettype_5ficmpv6_73',['gnrc_nettype_icmpv6',['../group__net__gnrc__nettype__icmpv6.html',1,'']]],
  ['gnrc_5fnettype_5fipv6_74',['gnrc_nettype_ipv6',['../group__net__gnrc__nettype__ipv6.html',1,'']]],
  ['gnrc_5fnettype_5fipv6_5fext_75',['gnrc_nettype_ipv6_ext',['../group__net__gnrc__nettype__ipv6__ext.html',1,'']]],
  ['gnrc_5fnettype_5florawan_76',['gnrc_nettype_lorawan',['../group__net__gnrc__nettype__lorawan.html',1,'']]],
  ['gnrc_5fnettype_5flwmac_77',['gnrc_nettype_lwmac',['../group__net__gnrc__nettype__lwmac.html',1,'']]],
  ['gnrc_5fnettype_5fndn_78',['gnrc_nettype_ndn',['../group__net__gnrc__nettype__ndn.html',1,'']]],
  ['gnrc_5fnettype_5fsixlowpan_79',['gnrc_nettype_sixlowpan',['../group__net__gnrc__nettype__sixlowpan.html',1,'']]],
  ['gnrc_5fnettype_5ftcp_80',['gnrc_nettype_tcp',['../group__net__gnrc__nettype__tcp.html',1,'']]],
  ['gnrc_5fnettype_5fudp_81',['gnrc_nettype_udp',['../group__net__gnrc__nettype__udp.html',1,'']]],
  ['gnrc_5fsixlowpan_5ffrag_5fsfr_5fcongure_5fabe_3a_20tcp_20reno_20with_20abe_82',['gnrc_sixlowpan_frag_sfr_congure_abe: TCP Reno with ABE',['../group__net__gnrc__sixlowpan__frag__sfr__congure__abe.html',1,'']]],
  ['gnrc_5fsixlowpan_5ffrag_5fsfr_5fcongure_5fquic_3a_20quic_20cc_83',['gnrc_sixlowpan_frag_sfr_congure_quic: QUIC CC',['../group__net__gnrc__sixlowpan__frag__sfr__congure__quic.html',1,'']]],
  ['gnrc_5fsixlowpan_5ffrag_5fsfr_5fcongure_5freno_3a_20tcp_20reno_84',['gnrc_sixlowpan_frag_sfr_congure_reno: TCP Reno',['../group__net__gnrc__sixlowpan__frag__sfr__congure__reno.html',1,'']]],
  ['gnrc_5fsixlowpan_5ffrag_5fsfr_5fcongure_5fsfr_3a_20appendix_20c_85',['gnrc_sixlowpan_frag_sfr_congure_sfr: Appendix C',['../group__net__gnrc__sixlowpan__frag__sfr__congure__sfr.html',1,'']]],
  ['gomach_86',['GoMacH',['../group__net__gnrc__gomach.html',1,'']]],
  ['gomach_20compile_20configuration_87',['GNRC GoMacH compile configuration',['../group__net__gnrc__gomach__conf.html',1,'']]],
  ['gp2y10xx_20driver_20compile_20configurations_88',['GP2Y10xx driver compile configurations',['../group__drivers__gp2y10xx__config.html',1,'']]],
  ['gp2y10xx_20optical_20dust_20sensor_20device_20driver_89',['GP2Y10xx Optical Dust Sensor device driver',['../group__drivers__gp2y10xx.html',1,'']]],
  ['gpio_90',['GPIO',['../group__drivers__periph__gpio.html',1,'GPIO'],['../group__cpu__kinetis__gpio.html',1,'Kinetis GPIO'],['../group__cpu__qn908x__gpio.html',1,'NXP QN908x GPIO']]],
  ['gpio_20driver_91',['Linux User Mode GPIO Driver',['../group__drivers__gpio__linux.html',1,'']]],
  ['gpio_20i_20o_20utils_92',['GPIO I/O Utils',['../group__gpio__util.html',1,'']]],
  ['gpio_20low_20level_20api_93',['GPIO Low Level API',['../group__drivers__periph__gpio__ll.html',1,'GPIO Low-Level API'],['../group__drivers__periph__gpio__ll__irq.html',1,'IRQ Support in Peripheral GPIO Low-Level API']]],
  ['gps_20parser_20library_94',['GPS parser library',['../group__pkg__minmea.html',1,'']]],
  ['grand_20central_20m4_20express_95',['Adafruit Grand Central M4 Express',['../group__boards__adafruit-grand-central-m4-express.html',1,'']]],
  ['graphic_20library_20for_20monochome_20displays_96',['U8G2 graphic library for monochome displays',['../group__pkg__u8g2.html',1,'']]],
  ['graphics_20library_20for_20embedded_20systems_97',['Color graphics library for embedded systems',['../group__pkg__ucglib.html',1,'']]],
  ['groups_98',['Common Board Groups',['../group__boards__common.html',1,'']]],
  ['grove_20ledbar_99',['Grove ledbar',['../group__drivers__grove__ledbar.html',1,'']]],
  ['guards_20for_20static_20instances_100',['C++ constructor guards for static instances',['../group__sys__cxx__ctor__guards.html',1,'']]],
  ['gui_20library_101',['LVGL - Open-Source Embedded GUI Library',['../group__pkg__lvgl.html',1,'']]],
  ['gyroscope_102',['gyroscope',['../group__drivers__itg320x.html',1,'ITG320X 3-axis gyroscope'],['../group__drivers__l3g4200d.html',1,'L3G4200D gyroscope'],['../group__drivers__lsm6dsxx.html',1,'LSM6DSXX 3D accelerometer/gyroscope'],['../group__drivers__mpu9x50.html',1,'MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope']]],
  ['gyroscope_20driver_20compile_20configuration_103',['L3G4200D gyroscope driver compile configuration',['../group__drivers__l3g4200d__config.html',1,'']]],
  ['gyroscope_20sensor_20family_104',['L3Gxxxx 3-axis gyroscope sensor family',['../group__drivers__l3gxxxx.html',1,'']]]
];
