var searchData=
[
  ['o_0',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['o_20expanders_1',['PCF857X I2C I/O expanders',['../group__drivers__pcf857x.html',1,'']]],
  ['o_20qpsk_20phy_2',['AT86RF215 MR-O-QPSK PHY',['../group__drivers__at86rf215__oqpsk.html',1,'']]],
  ['o_20utils_3',['GPIO I/O Utils',['../group__gpio__util.html',1,'']]],
  ['object_4',['object',['../group__lwm2m__objects__device.html',1,'Device LwM2M object'],['../group__lwm2m__objects__ipso__sensor__base.html',1,'IPSO Sensor base object'],['../group__lwm2m__objects__security.html',1,'Security LwM2M object']]],
  ['object_20compile_20configurations_5',['object compile configurations',['../group__lwm2m__objects__barometer__config.html',1,'LwM2M Barometer object compile configurations'],['../group__lwm2m__objects__current__config.html',1,'LwM2M Current Sensor object compile configurations'],['../group__lwm2m__objects__humidity__config.html',1,'LwM2M Humidity Sensor object compile configurations'],['../group__lwm2m__objects__illuminance__config.html',1,'LwM2M Illuminance Sensor object compile configurations'],['../group__lwm2m__objects__ipso__sensor__base__config.html',1,'LwM2M IPSO Sensor base object compile configurations'],['../group__lwm2m__objects__light__control__config.html',1,'LwM2M Light Control object compile configurations'],['../group__lwm2m__objects__security__config.html',1,'LwM2M Security object compile configurations'],['../group__lwm2m__objects__temperature__config.html',1,'LwM2M Temperature Sensor object compile configurations'],['../group__lwm2m__objects__voltage__config.html',1,'LwM2M Voltage Sensor object compile configurations']]],
  ['object_20configuration_6',['LwM2M Device Object configuration',['../group__lwm2m__objects__device__config.html',1,'']]],
  ['object_20dump_7',['Object dump',['../group__sys__od.html',1,'']]],
  ['object_20functionalities_8',['Common LwM2M Object functionalities',['../group__lwm2m__objects__common.html',1,'']]],
  ['object_20implementations_9',['LwM2M Object implementations',['../group__lwm2m__objects.html',1,'']]],
  ['oem_20sensor_20device_20driver_10',['pH OEM sensor device driver',['../group__drivers__ph__oem.html',1,'']]],
  ['of_20a_20rtt_11',['RTC emulation on top of a RTT',['../group__drivers__rtt__rtc.html',1,'']]],
  ['of_20arduino_20zero_20and_20clones_12',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['of_20atmel_20edbg_13',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['of_20auto_20initialized_20modules_14',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['of_20bottom_20half_20processor_15',['of Bottom Half Processor',['../group__sys__bhp__event.html',1,'Event based implementation of Bottom Half Processor'],['../group__sys__bhp__msg.html',1,'Message based implementation of Bottom Half Processor']]],
  ['of_20humidity_20and_20temperature_20sensors_16',['DHT Family of Humidity and Temperature Sensors',['../group__drivers__dht.html',1,'']]],
  ['of_20i2c_20eeproms_17',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['of_20p2p_20routes_20in_20llns_18',['Reactive Discovery of P2P Routes in LLNs',['../group__net__gnrc__rpl__p2p.html',1,'']]],
  ['of_20quic_20s_20cc_19',['CongURE implementation of QUIC&apos;s CC',['../group__sys__congure__quic.html',1,'']]],
  ['of_20scanned_20wifis_20access_20points_20',['List of scanned WiFis access points',['../group__net__wifi__scan__list.html',1,'']]],
  ['of_20sock_20api_21',['lwIP-specific implementation of sock API',['../group__pkg__lwip__sock.html',1,'']]],
  ['of_20spi_20eeproms_22',['of SPI EEPROMs',['../group__drivers__at25xxx.html',1,'AT25xxx family of SPI-EEPROMs'],['../group__drivers__mtd__at25xxx.html',1,'MTD wrapper for AT25xxx family of SPI-EEPROMs']]],
  ['of_20tcp_20abe_23',['CongURE implementation of TCP ABE',['../group__sys__congure__abe.html',1,'']]],
  ['of_20tcp_20reno_24',['CongURE implementation of TCP Reno',['../group__sys__congure__reno.html',1,'']]],
  ['of_20the_20arduino_20cores_25',['Hardware independent layer of the Arduino cores',['../group__pkg__arduino__api.html',1,'']]],
  ['of_20the_20servo_20driver_26',['SAUL integration of the servo driver',['../group__drivers__servo__saul.html',1,'']]],
  ['of_20the_20sock_20api_27',['of the sock API',['../group__net__gnrc__sock.html',1,'GNRC-specific implementation of the sock API'],['../group__pkg__openwsn__sock.html',1,'OpenWSN-specific implementation of the sock API']]],
  ['of_20the_20string_20formatting_20api_20fmt_5ftable_28',['Table extension of the string formatting API (fmt_table)',['../group__sys__fmt__table.html',1,'']]],
  ['of_20things_29',['Ultra-lightweight Javascript for Internet Of Things',['../group__pkg__jerryscript.html',1,'']]],
  ['of_20usb_20device_20firmware_30',['Initialization of USB Device Firmware',['../group__sys__riotboot__usb__dfu.html',1,'']]],
  ['of_20wireless_20access_20points_31',['Scan List - List of wireless access points',['../group__net__l2scanlist.html',1,'']]],
  ['ofdm_20phy_32',['AT86RF215 MR-OFDM PHY',['../group__drivers__at86rf215__ofdm.html',1,'']]],
  ['olimex_20esp32_20evb_33',['Olimex ESP32-EVB',['../group__boards__esp32__olimex-esp32-evb.html',1,'']]],
  ['olimex_20mod_20wifi_20esp8266_20dev_34',['Olimex MOD-WIFI-ESP8266-DEV',['../group__boards__esp8266__olimex-mod.html',1,'']]],
  ['olimex_20msp430_20h1611_35',['Olimex MSP430-H1611',['../group__boards__olimex__msp430__h1611.html',1,'']]],
  ['olimex_20msp430_20h2618_36',['Olimex MSP430-H2618',['../group__boards__olimex__msp430__h2618.html',1,'']]],
  ['olimexino_20stm32_37',['STM32 Olimexino-stm32',['../group__boards__olimexino-stm32.html',1,'']]],
  ['omote_38',['omote',['../group__boards__omote.html',1,'']]],
  ['on_20board_20leds_39',['Control on-board LEDs',['../group__drivers__led.html',1,'']]],
  ['on_20device_20level_40',['Packet interface on device level',['../group__net__packet.html',1,'']]],
  ['on_20internal_20flash_41',['Helpers to manipulate partitions (slots) on internal flash',['../group__sys__riotboot__slot.html',1,'']]],
  ['on_20top_20of_20a_20rtt_42',['RTC emulation on top of a RTT',['../group__drivers__rtt__rtc.html',1,'']]],
  ['one_43',['SODAQ ONE',['../group__boards__sodaq-one.html',1,'']]],
  ['one_20at_20a_20time_44',['One at a time',['../group__sys__hashes__one__at__a__time.html',1,'']]],
  ['oneway_20malloc_45',['Oneway malloc',['../group__oneway__malloc.html',1,'']]],
  ['online_202_46',['FIDO2 - Fast Identity Online 2',['../group__fido2.html',1,'']]],
  ['only_20under_20native_47',['Stack backtrace (only under native)',['../group__backtrace.html',1,'']]],
  ['open_20node_48',['open node',['../group__boards__iotlab-a8-m3.html',1,'IoT-LAB A8 M3 open node'],['../group__boards__iotlab-m3.html',1,'IoT-LAB M3 open node']]],
  ['open_20source_20embedded_20gui_20library_49',['LVGL - Open-Source Embedded GUI Library',['../group__pkg__lvgl.html',1,'']]],
  ['opencm9_2004_50',['OpenCM9.04',['../group__boards__opencm904.html',1,'']]],
  ['opendsme_20ieee_20802_2015_204_20dsme_51',['openDSME - IEEE 802.15.4 DSME',['../group__pkg__opendsme.html',1,'']]],
  ['openlabs_20co_20kw41z_20mini_20256kib_20board_52',['openlabs.co kw41z-mini-256kib board',['../group__boards__openlabs-kw41z-mini-256kib.html',1,'']]],
  ['openlabs_20co_20kw41z_20mini_20board_53',['openlabs.co kw41z-mini board',['../group__boards__openlabs-kw41z-mini.html',1,'']]],
  ['openmote_20b_54',['OpenMote-b',['../group__boards__openmote-b.html',1,'']]],
  ['openmote_20cc2538_55',['OpenMote-cc2538',['../group__boards__openmote-cc2538.html',1,'']]],
  ['openthread_56',['OpenThread',['../group__pkg__openthread__cli.html',1,'']]],
  ['openthread_20network_20stack_57',['OpenThread network stack',['../group__pkg__openthread.html',1,'']]],
  ['openwsn_20network_20stack_58',['OpenWSN network stack',['../group__pkg__openwsn.html',1,'']]],
  ['openwsn_20specific_20implementation_20of_20the_20sock_20api_59',['OpenWSN-specific implementation of the sock API',['../group__pkg__openwsn__sock.html',1,'']]],
  ['operated_20serial_20ethernet_60',['Differentially Operated Serial Ethernet',['../group__drivers__dose.html',1,'']]],
  ['operated_20serial_20ethernet_20dose_20driver_20compile_20configuration_61',['Differentially Operated Serial Ethernet (DOSE) driver compile configuration',['../group__drivers__dose__config.html',1,'']]],
  ['operations_62',['Fractional integer operations',['../group__sys__frac.html',1,'']]],
  ['operator_20module_63',['C++ new and delete operator module',['../group__sys__cpp__new__delete.html',1,'']]],
  ['opt3001_20ambient_20light_20sensor_64',['OPT3001 Ambient Light Sensor',['../group__drivers__opt3001.html',1,'']]],
  ['opt3001_20ambient_20light_20sensor_20driver_20compile_20configuration_65',['OPT3001 Ambient Light Sensor driver compile configuration',['../group__drivers__opt3001__config.html',1,'']]],
  ['optical_20dust_20sensor_20device_20driver_66',['GP2Y10xx Optical Dust Sensor device driver',['../group__drivers__gp2y10xx.html',1,'']]],
  ['option_20extension_20headers_67',['Support for IPv6 option extension headers',['../group__net__gnrc__ipv6__ext__opt.html',1,'']]],
  ['options_68',['options',['../group__net__ipv6__ext__opt.html',1,'IPv6 destination and hop-by-hop options'],['../group__pkg__lwip__opts.html',1,'lwIP options']]],
  ['options_20for_20network_20apis_69',['Netopt - Configuration options for network APIs',['../group__net__netopt.html',1,'']]],
  ['options_20for_20usb_20apis_70',['usbopt - Configuration options for USB APIs',['../group__usb__usbopt.html',1,'']]],
  ['order_20of_20auto_20initialized_20modules_71',['Utilities to influence the order of auto-initialized modules',['../group__sys__auto__init__utils.html',1,'']]],
  ['ota_20mock_20transport_72',['SUIT secure firmware OTA mock transport',['../group__sys__suit__transport__mock.html',1,'']]],
  ['ota_20upgrade_20infrastructure_73',['SUIT secure firmware OTA upgrade infrastructure',['../group__sys__suit.html',1,'']]],
  ['ota_20upgrade_20storage_74',['SUIT secure firmware OTA upgrade storage',['../group__sys__suit__storage.html',1,'']]],
  ['ota_20vfs_20transport_75',['SUIT secure firmware OTA VFS transport',['../group__sys__suit__transport__vfs.html',1,'']]],
  ['otg_20board_76',['ESP32-S3-USB-OTG Board',['../group__boards__esp32s3__usb__otg.html',1,'']]],
  ['otg_20fs_20hs_20peripheral_77',['stm32 USB OTG FS/HS peripheral',['../group__cpu__stm32__usbdev.html',1,'']]],
  ['out_20of_20atmel_20edbg_78',['Driver for getting MAC address out of Atmel EDBG',['../group__drivers__edbg__eui.html',1,'']]],
  ['output_79',['Test result output',['../group__test__utils__result__output.html',1,'']]],
  ['output_20helpers_80',['Test Utils Result Output Helpers',['../group__turo__helpers.html',1,'']]],
  ['output_20implementation_20api_81',['Test Utils Result Output Implementation API',['../group__turo__API.html',1,'']]],
  ['output_20plain_20text_82',['Test result output plain text',['../group__test__utils__result__output__txt.html',1,'']]],
  ['output_20structure_83',['Test result output structure',['../group__test__utils__result__output__check.html',1,'']]],
  ['output_20with_20json_84',['Test result output with JSON',['../group__test__utils__result__output__json.html',1,'']]],
  ['over_20ble_20for_20nimble_85',['RPL-over-BLE for NimBLE',['../group__pkg__nimble__rpble.html',1,'']]],
  ['over_20can_86',['ISO transport protocol over CAN',['../group__sys__can__isotp.html',1,'']]],
  ['over_20cdc_20acm_20usbus_87',['STDIO over CDC ACM (usbus)',['../group__usbus__cdc__acm__stdio.html',1,'']]],
  ['over_20coap_20client_20configuration_88',['GCoAP DNS over CoAP client configuration',['../group__gcoap__dns__config.html',1,'']]],
  ['over_20coap_20client_20implementation_89',['DNS over CoAP client implementation',['../group__net__gcoap__dns.html',1,'']]],
  ['over_20dtls_20compile_20time_20configuration_90',['DNS over DTLS compile-time configuration',['../group__net__sock__dodtls__conf.html',1,'']]],
  ['over_20dtls_20sock_20api_91',['DNS over DTLS sock API',['../group__net__sock__dodtls.html',1,'']]],
  ['over_20esp32_20debug_20serial_20jtag_92',['STDIO over ESP32 Debug Serial/JTAG',['../group__stdio__usb__serial__jtag.html',1,'']]],
  ['over_20nimble_93',['STDIO over NimBLE',['../group__sys__stdio__nimble.html',1,'']]],
  ['over_20segger_20rtt_94',['STDIO over SEGGER RTT',['../group__sys__stdio__rtt.html',1,'']]],
  ['over_20semihosting_95',['STDIO over Semihosting',['../group__sys__stdio__semihosting.html',1,'']]],
  ['over_20serial_20driver_96',['Ethernet-over-serial driver',['../group__drivers__ethos.html',1,'']]],
  ['over_20serial_20driver_20driver_20compile_20configuration_97',['Ethernet-over-serial driver driver compile configuration',['../group__drivers__ethos__config.html',1,'']]],
  ['over_20telnet_98',['STDIO over telnet',['../group__net__telnet__stdio.html',1,'']]],
  ['over_20uart_99',['STDIO over UART',['../group__sys__stdio__uart.html',1,'']]],
  ['over_20udp_100',['STDIO over UDP',['../group__sys__stdio__udp.html',1,'']]],
  ['over_20usb_20cdc_20acm_20tinyusb_101',['STDIO over USB CDC-ACM (tinyUSB)',['../group__pkg__tinyusb__stdio__cdc__acm.html',1,'']]],
  ['over_20x_102',['Stack-independent helpers for IPv6 over X',['../group__net__l2util.html',1,'']]],
  ['overhead_20utility_103',['ztimer overhead utility',['../group__sys__ztimer__overhead.html',1,'']]]
];
